# Generated by Django 4.2.7 on 2026-01-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
