# Generated by Django 5.0.13 on 2025-05-16 03:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('horario_atencion', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='talleres/')),
                ('calificacion_promedio', models.FloatField(default=0.0)),
                ('numero_de_calificaciones', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'taller',
                'verbose_name_plural': 'talleres',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('es_mecanico', models.BooleanField(default=False)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='MecanicoDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('disponible', models.BooleanField(default=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='mecanicos/')),
                ('disponibilidad', models.TextField(blank=True, null=True)),
                ('calificacion_promedio', models.FloatField(default=0.0)),
                ('numero_de_calificaciones', models.IntegerField(default=0)),
                ('especialidades', models.ManyToManyField(blank=True, related_name='mecanicos_domicilio', to='servicios.categoriaservicio')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mecanico_domicilio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mecánico a domicilio',
                'verbose_name_plural': 'mecánicos a domicilio',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_hora_resena', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='usuarios.cliente')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='usuarios.mecanicodomicilio')),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='usuarios.taller')),
            ],
            options={
                'verbose_name': 'reseña',
                'verbose_name_plural': 'reseñas',
            },
        ),
        migrations.CreateModel(
            name='ZonaCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poligono_cobertura', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_cobertura', to='usuarios.mecanicodomicilio')),
            ],
            options={
                'verbose_name': 'zona de cobertura',
                'verbose_name_plural': 'zonas de cobertura',
            },
        ),
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.CheckConstraint(check=models.Q(('taller__isnull', False), ('mecanico__isnull', False), _connector='OR'), name='resena_debe_tener_taller_o_mecanico'),
        ),
    ]
