# Generated by Django 5.0.13 on 2025-05-16 14:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('etiqueta', models.CharField(choices=[('Casa', 'Casa'), ('Trabajo', 'Trabajo'), ('Otro', 'Otro')], default='Casa', max_length=50)),
                ('detalles', models.CharField(blank=True, max_length=255, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dirección de usuario',
                'verbose_name_plural': 'direcciones de usuario',
                'ordering': ['-es_principal', '-fecha_actualizacion'],
            },
        ),
    ]
