# Generated by Django 5.0.13 on 2026-01-12 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0002_initial'),
        ('servicios', '0002_initial'),
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='marcas_atendidas',
            field=models.ManyToManyField(blank=True, help_text='Marcas de vehículos que atiende el mecánico', related_name='mecanicos_domicilio', to='vehiculos.marcavehiculo'),
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mecanico_domicilio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='verificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario administrador que verificó el proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_verificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horarioproveedor',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_configurados', to='usuarios.mecanicodomicilio'),
        ),
        migrations.AddField(
            model_name='documentoonboarding',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_onboarding', to='usuarios.mecanicodomicilio'),
        ),
        migrations.AddField(
            model_name='connectionstatus',
            name='proveedor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_status', to='usuarios.mecanicodomicilio'),
        ),
        migrations.AddField(
            model_name='configuracionsemanalproveedor',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.mecanicodomicilio', verbose_name='Mecánico'),
        ),
        migrations.AddField(
            model_name='mechanicservicearea',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='usuarios.mecanicodomicilio', verbose_name='Mecánico'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='verificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario administrador que verificó el proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_verificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resena',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='resena',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='usuarios.mecanicodomicilio'),
        ),
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(help_text='Cliente que hizo la reseña', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='service_order',
            field=models.OneToOneField(help_text='Orden de servicio asociada', on_delete=django.db.models.deletion.CASCADE, to='ordenes.solicitudservicio'),
        ),
        migrations.AddField(
            model_name='taller',
            name='especialidades',
            field=models.ManyToManyField(blank=True, help_text='Especialidades del taller', related_name='talleres', to='servicios.categoriaservicio'),
        ),
        migrations.AddField(
            model_name='taller',
            name='marcas_atendidas',
            field=models.ManyToManyField(blank=True, help_text='Marcas de vehículos que atiende el taller', related_name='talleres', to='vehiculos.marcavehiculo'),
        ),
        migrations.AddField(
            model_name='taller',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taller',
            name='verificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario administrador que verificó el proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_verificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resena',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='usuarios.taller'),
        ),
        migrations.AddField(
            model_name='horarioproveedor',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_configurados', to='usuarios.taller'),
        ),
        migrations.AddField(
            model_name='documentoonboarding',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_onboarding', to='usuarios.taller'),
        ),
        migrations.AddField(
            model_name='connectionstatus',
            name='taller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_status', to='usuarios.taller'),
        ),
        migrations.AddField(
            model_name='configuracionsemanalproveedor',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.taller', verbose_name='Taller'),
        ),
        migrations.AddField(
            model_name='tallerdireccion',
            name='taller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_fisica', to='usuarios.taller'),
        ),
        migrations.AddField(
            model_name='zonacobertura',
            name='mecanico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_cobertura', to='usuarios.mecanicodomicilio'),
        ),
        migrations.AddIndex(
            model_name='mechanicservicearea',
            index=models.Index(fields=['mechanic', 'is_active'], name='usuarios_me_mechani_70135c_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanicservicearea',
            index=models.Index(fields=['area_type', 'is_active'], name='usuarios_me_area_ty_c0176f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('client', 'provider_type', 'provider_id', 'service_order')},
        ),
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.CheckConstraint(check=models.Q(('taller__isnull', False), ('mecanico__isnull', False), _connector='OR'), name='resena_debe_tener_taller_o_mecanico'),
        ),
        migrations.AddConstraint(
            model_name='horarioproveedor',
            constraint=models.CheckConstraint(check=models.Q(('taller__isnull', False), ('mecanico__isnull', False), _connector='OR'), name='horario_debe_tener_taller_o_mecanico'),
        ),
        migrations.AddConstraint(
            model_name='horarioproveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('taller__isnull', False)), fields=('taller', 'dia_semana'), name='unique_taller_dia_semana'),
        ),
        migrations.AddConstraint(
            model_name='horarioproveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('mecanico__isnull', False)), fields=('mecanico', 'dia_semana'), name='unique_mecanico_dia_semana'),
        ),
        migrations.AddConstraint(
            model_name='documentoonboarding',
            constraint=models.CheckConstraint(check=models.Q(('taller__isnull', False), ('mecanico__isnull', False), _connector='OR'), name='documento_debe_tener_taller_o_mecanico'),
        ),
    ]
