# Generated by Django 5.0.13 on 2025-05-17 04:43

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_direccionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='radio_cobertura',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Radio de cobertura en kilómetros', max_digits=5),
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='capacidad_diaria',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='taller',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mecanicodomicilio',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores/'),
        ),
        migrations.AlterField(
            model_name='mecanicodomicilio',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='taller',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores/'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
