# Generated by Django 4.2.7 on 2026-01-17 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token de Expo Push Notification', max_length=255, unique=True)),
                ('dispositivo', models.CharField(blank=True, help_text='Nombre o identificador del dispositivo', max_length=100, null=True)),
                ('plataforma', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('unknown', 'Desconocido')], default='unknown', help_text='Plataforma del dispositivo', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el token está activo y debe recibir notificaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del token')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('ultima_notificacion_enviada', models.DateTimeField(blank=True, help_text='Fecha de la última notificación enviada a este token', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del token', on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Token',
                'verbose_name_plural': 'Push Tokens',
                'db_table': 'usuarios_push_tokens',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['usuario', 'activo'], name='usuarios_pu_usuario_6e9b6e_idx'), models.Index(fields=['token'], name='usuarios_pu_token_fbd4f9_idx')],
            },
        ),
    ]
