# Generated by Django 5.0.13 on 2025-05-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_refactorizacion_fase1'),
        ('usuarios', 'manual_refactorizacion_20250517_005634_tqagrz'),
    ]

    operations = [
    ]
