# Generated by Django 5.2.1 on 2026-01-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='expo_push_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
