# Generated by Django 4.2.7 on 2026-01-18 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_expo_push_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('health_alert', 'Alerta de Salud'), ('payment_reminder', 'Recordatorio de Pago'), ('order_update', 'Actualización de Orden'), ('system', 'Sistema')], help_text='Tipo de notificación', max_length=50)),
                ('titulo', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('mensaje', models.TextField(help_text='Mensaje de la notificación')),
                ('leida', models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída')),
                ('fecha_leida', models.DateTimeField(blank=True, help_text='Fecha en que se marcó como leída', null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Metadatos adicionales en formato JSON')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la notificación')),
                ('usuario', models.ForeignKey(help_text='Usuario destinatario de la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'usuarios_notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', '-fecha_creacion'], name='usuarios_no_usuario_e45db9_idx'), models.Index(fields=['usuario', 'leida'], name='usuarios_no_usuario_b76e82_idx')],
            },
        ),
    ]
