# Generated by Django 5.2.1 on 2025-05-26 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_merge_20250516_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana (0=Lunes, 6=Domingo)')),
                ('hora_apertura', models.TimeField(help_text='Hora de apertura del taller')),
                ('hora_cierre', models.TimeField(help_text='Hora de cierre del taller')),
                ('activo', models.BooleanField(default=True, help_text='Si el taller atiende este día')),
                ('duracion_slot', models.PositiveIntegerField(default=60, help_text='Duración de cada slot en minutos')),
                ('tiempo_descanso', models.PositiveIntegerField(default=0, help_text='Tiempo de descanso entre slots en minutos')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='usuarios.taller')),
            ],
            options={
                'verbose_name': 'horario de taller',
                'verbose_name_plural': 'horarios de talleres',
                'ordering': ['taller', 'dia_semana'],
                'unique_together': {('taller', 'dia_semana')},
            },
        ),
    ]
