# Generated by Django 5.0.13 on 2025-06-03 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_horariotaller'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del proveedor', null=True),
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='dni',
            field=models.CharField(blank=True, help_text='DNI/RUT Personal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='estado_verificacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', help_text='Estado de verificación del proveedor', max_length=20),
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='experiencia_anos',
            field=models.PositiveIntegerField(blank=True, help_text='Años de experiencia', null=True),
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando fue verificado el proveedor', null=True),
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='onboarding_completado',
            field=models.BooleanField(default=False, help_text='Indica si el proveedor completó el proceso de onboarding'),
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT/CUIT/ID Fiscal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='verificado',
            field=models.BooleanField(default=False, help_text='Indica si el proveedor ha sido verificado y puede aparecer en la app de clientes'),
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='verificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario administrador que verificó el proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_verificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taller',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del proveedor', null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='dni',
            field=models.CharField(blank=True, help_text='DNI/RUT Personal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='estado_verificacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', help_text='Estado de verificación del proveedor', max_length=20),
        ),
        migrations.AddField(
            model_name='taller',
            name='experiencia_anos',
            field=models.PositiveIntegerField(blank=True, help_text='Años de experiencia', null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando fue verificado el proveedor', null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='onboarding_completado',
            field=models.BooleanField(default=False, help_text='Indica si el proveedor completó el proceso de onboarding'),
        ),
        migrations.AddField(
            model_name='taller',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT/CUIT/ID Fiscal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='verificado',
            field=models.BooleanField(default=False, help_text='Indica si el proveedor ha sido verificado y puede aparecer en la app de clientes'),
        ),
        migrations.AddField(
            model_name='taller',
            name='verificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario administrador que verificó el proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_verificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocumentoOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('dni_frontal', 'DNI/ID Personal (Frontal)'), ('dni_trasero', 'DNI/ID Personal (Trasero)'), ('rut_fiscal', 'RUT/CUIT/ID Fiscal del Negocio'), ('licencia_conducir', 'Licencia de Conducir'), ('foto_fachada', 'Foto de la Fachada del Taller'), ('foto_interior', 'Foto del Interior del Taller'), ('foto_equipos', 'Foto de Equipos/Herramientas'), ('foto_herramientas', 'Foto de Herramientas Portátiles'), ('foto_vehiculo', 'Foto de Vehículo de Trabajo')], max_length=50)),
                ('archivo', models.ImageField(upload_to='documentos_onboarding/')),
                ('nombre_original', models.CharField(help_text='Nombre original del archivo', max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('verificado', models.BooleanField(default=False)),
                ('comentarios_verificacion', models.TextField(blank=True, null=True)),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_onboarding', to='usuarios.mecanicodomicilio')),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_onboarding', to='usuarios.taller')),
            ],
            options={
                'verbose_name': 'documento de onboarding',
                'verbose_name_plural': 'documentos de onboarding',
            },
        ),
        migrations.AddConstraint(
            model_name='documentoonboarding',
            constraint=models.CheckConstraint(check=models.Q(('taller__isnull', False), ('mecanico__isnull', False), _connector='OR'), name='documento_debe_tener_taller_o_mecanico'),
        ),
    ]
