# Generated by Django 4.2.7 on 2026-01-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionusuario',
            name='etiqueta',
            field=models.CharField(default='Casa', max_length=50),
        ),
    ]
