# Generated by Django 4.2.7 on 2026-01-26 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_initial'),
        ('usuarios', '0006_alter_direccionusuario_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='solicitud',
            field=models.OneToOneField(blank=True, help_text='Solicitud de servicio asociada a esta reseña', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resena', to='ordenes.solicitudservicio'),
        ),
        migrations.CreateModel(
            name='ResenaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Foto adjunta a la reseña', upload_to='resenas/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='usuarios.resena')),
            ],
            options={
                'verbose_name': 'foto de reseña',
                'verbose_name_plural': 'fotos de reseñas',
            },
        ),
    ]
