# Generated by Django 5.0.13 on 2025-06-03 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_mecanicodomicilio_descripcion_mecanicodomicilio_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taller', to=settings.AUTH_USER_MODEL),
        ),
    ]
