# Generated by Django 5.0.13 on 2025-06-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_add_usuario_to_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='onboarding_iniciado',
            field=models.BooleanField(default=False, help_text='Indica si el proveedor inició el proceso de onboarding'),
        ),
        migrations.AddField(
            model_name='taller',
            name='onboarding_iniciado',
            field=models.BooleanField(default=False, help_text='Indica si el proveedor inició el proceso de onboarding'),
        ),
    ]
