# Generated by Django 5.0.13 on 2025-06-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_repuesto_solicitudrepuesto_serviciorepuesto'),
        ('usuarios', '0008_add_onboarding_iniciado'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='marcas_atendidas',
            field=models.ManyToManyField(blank=True, help_text='Marcas de vehículos que atiende el mecánico', related_name='mecanicos_domicilio', to='vehiculos.marcavehiculo'),
        ),
        migrations.AddField(
            model_name='taller',
            name='especialidades',
            field=models.ManyToManyField(blank=True, help_text='Especialidades del taller', related_name='talleres', to='servicios.categoriaservicio'),
        ),
        migrations.AddField(
            model_name='taller',
            name='marcas_atendidas',
            field=models.ManyToManyField(blank=True, help_text='Marcas de vehículos que atiende el taller', related_name='talleres', to='vehiculos.marcavehiculo'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='capacidad_diaria',
            field=models.IntegerField(default=10, help_text='Capacidad de servicios por día'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT del taller', max_length=20, null=True),
        ),
    ]
