# Generated by Django 5.0.13 on 2025-06-04 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_add_especialidades_y_marcas'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana (0=Lunes, 6=Domingo)')),
                ('activo', models.BooleanField(default=True, help_text='Si el proveedor atiende este día')),
                ('hora_inicio', models.TimeField(default='08:00', help_text='Hora de inicio de atención')),
                ('hora_fin', models.TimeField(default='18:00', help_text='Hora de fin de atención')),
                ('duracion_slot', models.PositiveIntegerField(default=60, help_text='Duración de cada slot en minutos')),
                ('tiempo_descanso', models.PositiveIntegerField(default=0, help_text='Tiempo libre entre servicios en minutos')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_configurados', to='usuarios.mecanicodomicilio')),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_configurados', to='usuarios.taller')),
            ],
            options={
                'verbose_name': 'horario de proveedor',
                'verbose_name_plural': 'horarios de proveedores',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.DeleteModel(
            name='HorarioTaller',
        ),
        migrations.AddConstraint(
            model_name='horarioproveedor',
            constraint=models.CheckConstraint(check=models.Q(('taller__isnull', False), ('mecanico__isnull', False), _connector='OR'), name='horario_debe_tener_taller_o_mecanico'),
        ),
        migrations.AddConstraint(
            model_name='horarioproveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('taller__isnull', False)), fields=('taller', 'dia_semana'), name='unique_taller_dia_semana'),
        ),
        migrations.AddConstraint(
            model_name='horarioproveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('mecanico__isnull', False)), fields=('mecanico', 'dia_semana'), name='unique_mecanico_dia_semana'),
        ),
    ]
