# Generated by Django 5.0.13 on 2025-06-05 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_crear_horario_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSemanalProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio_global', models.TimeField(default='08:00', help_text='Hora de inicio que se aplicará a todos los días habilitados', verbose_name='Hora de inicio (global)')),
                ('hora_fin_global', models.TimeField(default='18:00', help_text='Hora de fin que se aplicará a todos los días habilitados', verbose_name='Hora de fin (global)')),
                ('duracion_slot_global', models.PositiveIntegerField(default=60, help_text='Duración en minutos de cada slot de atención', verbose_name='Duración de slot (minutos)')),
                ('tiempo_descanso_global', models.PositiveIntegerField(default=0, help_text='Tiempo de descanso entre slots', verbose_name='Tiempo de descanso (minutos)')),
                ('lunes_activo', models.BooleanField(default=True, verbose_name='Lunes')),
                ('martes_activo', models.BooleanField(default=True, verbose_name='Martes')),
                ('miercoles_activo', models.BooleanField(default=True, verbose_name='Miércoles')),
                ('jueves_activo', models.BooleanField(default=True, verbose_name='Jueves')),
                ('viernes_activo', models.BooleanField(default=True, verbose_name='Viernes')),
                ('sabado_activo', models.BooleanField(default=False, verbose_name='Sábado')),
                ('domingo_activo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('lunes_hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Lunes - Hora inicio')),
                ('lunes_hora_fin', models.TimeField(blank=True, null=True, verbose_name='Lunes - Hora fin')),
                ('martes_hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Martes - Hora inicio')),
                ('martes_hora_fin', models.TimeField(blank=True, null=True, verbose_name='Martes - Hora fin')),
                ('miercoles_hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Miércoles - Hora inicio')),
                ('miercoles_hora_fin', models.TimeField(blank=True, null=True, verbose_name='Miércoles - Hora fin')),
                ('jueves_hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Jueves - Hora inicio')),
                ('jueves_hora_fin', models.TimeField(blank=True, null=True, verbose_name='Jueves - Hora fin')),
                ('viernes_hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Viernes - Hora inicio')),
                ('viernes_hora_fin', models.TimeField(blank=True, null=True, verbose_name='Viernes - Hora fin')),
                ('sabado_hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Sábado - Hora inicio')),
                ('sabado_hora_fin', models.TimeField(blank=True, null=True, verbose_name='Sábado - Hora fin')),
                ('domingo_hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Domingo - Hora inicio')),
                ('domingo_hora_fin', models.TimeField(blank=True, null=True, verbose_name='Domingo - Hora fin')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.mecanicodomicilio', verbose_name='Mecánico')),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.taller', verbose_name='Taller')),
            ],
            options={
                'verbose_name': 'Configuración Semanal de Horarios',
                'verbose_name_plural': 'Configuraciones Semanales de Horarios',
            },
        ),
    ]
