# Generated by Cursor on 2026-04-30

from django.db import migrations, models
from django.core.validators import MaxValueValidator, MinValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0010_notificacion_tipos_suscripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="resena",
            name="puntualidad",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Puntualidad del proveedor (1-5)",
                validators=[MinValueValidator(1), MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="resena",
            name="recepcion_a_tiempo",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Recepción/entrega a tiempo (taller) (1-5)",
                validators=[MinValueValidator(1), MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="resena",
            name="limpieza_auto",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Limpieza del auto (taller) (1-5)",
                validators=[MinValueValidator(1), MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="resena",
            name="zona_limpia",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Limpieza de la zona (domicilio) (1-5)",
                validators=[MinValueValidator(1), MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="resena",
            name="claridad_explicacion",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Claridad al explicar fallas/solución (1-5)",
                validators=[MinValueValidator(1), MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="resena",
            name="informacion_relevante",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Envió información relevante del servicio (1-5)",
                validators=[MinValueValidator(1), MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="resena",
            name="trato",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Trato y educación (1-5)",
                validators=[MinValueValidator(1), MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="resena",
            name="entrego_repuestos",
            field=models.BooleanField(
                blank=True,
                null=True,
                help_text="Entregó repuestos al cliente (True/False) o null si no aplica",
            ),
        ),
    ]

