# Generated by Django 5.2.1 on 2025-07-10 02:25

import mecanimovilapp.apps.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_add_configuracion_semanal_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoonboarding',
            name='archivo',
            field=models.FileField(help_text='Archivos permitidos: JPG, PNG, PDF (máximo 10MB)', upload_to='documentos_onboarding/', validators=[mecanimovilapp.apps.usuarios.models.validar_archivo_documento]),
        ),
    ]
