# Generated by Django 5.0.13 on 2025-07-25 14:36

import django.db.models.deletion
import mecanimovilapp.apps.usuarios.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_change_documento_archivo_to_filefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChileanCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código oficial de la comuna', max_length=10, unique=True, verbose_name='Código Comuna')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre Comuna')),
                ('region_code', models.CharField(max_length=10, verbose_name='Código Región')),
                ('region_name', models.CharField(max_length=100, verbose_name='Nombre Región')),
                ('province_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Provincia')),
                ('is_active', models.BooleanField(default=True, help_text='Determina si la comuna está disponible para selección', verbose_name='Comuna Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comuna Chilena',
                'verbose_name_plural': 'Comunas Chilenas',
                'ordering': ['region_code', 'name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='usuarios_ch_is_acti_fb5c2b_idx'), models.Index(fields=['region_code', 'name'], name='usuarios_ch_region__4e07ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='MechanicServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_type', models.CharField(choices=[('COMMUNE', 'Comuna/Distrito')], default='COMMUNE', max_length=20, verbose_name='Tipo de Zona')),
                ('name', models.CharField(blank=True, help_text='Nombre descriptivo opcional (ej: "Mi Zona Central")', max_length=100, null=True, verbose_name='Nombre de la Zona')),
                ('commune_names', models.JSONField(help_text='Lista de nombres de comunas donde presta servicios', validators=[mecanimovilapp.apps.usuarios.models.validate_commune_names], verbose_name='Nombres de Comunas')),
                ('is_active', models.BooleanField(default=True, help_text='Determina si esta zona está activa para recibir órdenes', verbose_name='Zona Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='usuarios.mecanicodomicilio', verbose_name='Mecánico')),
            ],
            options={
                'verbose_name': 'Zona de Servicio',
                'verbose_name_plural': 'Zonas de Servicio',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mechanic', 'is_active'], name='usuarios_me_mechani_70135c_idx'), models.Index(fields=['area_type', 'is_active'], name='usuarios_me_area_ty_c0176f_idx')],
            },
        ),
    ]
