# Generated by Django 5.2.1 on 2025-07-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_add_service_areas_and_communes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='esta_conectado',
            field=models.BooleanField(default=False, help_text='Indica si el proveedor está actualmente conectado en la app'),
        ),
        migrations.AddField(
            model_name='mecanicodomicilio',
            name='ultima_conexion',
            field=models.DateTimeField(blank=True, help_text='Última vez que el proveedor estuvo conectado en la app', null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='esta_conectado',
            field=models.BooleanField(default=False, help_text='Indica si el proveedor está actualmente conectado en la app'),
        ),
        migrations.AddField(
            model_name='taller',
            name='ultima_conexion',
            field=models.DateTimeField(blank=True, help_text='Última vez que el proveedor estuvo conectado en la app', null=True),
        ),
    ]
