# Generated by Django 4.2.7 on 2026-06-22 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_ofertaservicio_tipo_motor'),
        ('usuarios', '0014_notificacion_review_reminder_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('mandante', 'Mandante (dueño)'), ('supervisor', 'Supervisor'), ('mecanico', 'Mecánico')], default='mecanico', help_text='Rol dentro del taller', max_length=20)),
                ('nombre', models.CharField(help_text='Nombre del miembro (necesario para mecánicos sin login)', max_length=150)),
                ('modalidad_tecnico', models.CharField(choices=[('en_taller', 'En taller (lugar físico)'), ('a_domicilio', 'A domicilio'), ('ambas', 'En taller y a domicilio')], default='en_taller', help_text='Modalidad de atención del mecánico: en taller, a domicilio o ambas', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Habilitado por el supervisor. Si es False, no recibe asignaciones ni aporta disponibilidad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'miembro de taller',
                'verbose_name_plural': 'miembros de taller',
                'ordering': ['taller', 'rol', 'nombre'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='horarioproveedor',
            name='horario_debe_tener_taller_o_mecanico',
        ),
        migrations.RemoveConstraint(
            model_name='horarioproveedor',
            name='unique_taller_dia_semana',
        ),
        # En producción (Render) este índice ya fue renombrado por una migración
        # 0014 fantasma (aplicada pero sin archivo en el repo). Hacemos el rename
        # idempotente: en BD nuevas renombra; en Render es no-op.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='webpushsubscription',
                    new_name='usuarios_we_usuario_3ebe70_idx',
                    old_name='usuarios_we_usuario_activo_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS usuarios_we_usuario_activo_idx RENAME TO usuarios_we_usuario_3ebe70_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS usuarios_we_usuario_3ebe70_idx RENAME TO usuarios_we_usuario_activo_idx;",
                ),
            ],
        ),
        migrations.AddField(
            model_name='mechanicservicearea',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='usuarios.taller', verbose_name='Taller'),
        ),
        migrations.AddField(
            model_name='taller',
            name='modalidad_atencion',
            field=models.CharField(choices=[('en_taller', 'En taller (lugar físico)'), ('a_domicilio', 'A domicilio'), ('ambas', 'En taller y a domicilio')], default='en_taller', help_text='Modalidad de atención del proveedor: en taller, a domicilio o ambas', max_length=20),
        ),
        migrations.AddField(
            model_name='taller',
            name='radio_cobertura',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Radio de cobertura en kilómetros para atención a domicilio', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mechanicservicearea',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='usuarios.mecanicodomicilio', verbose_name='Mecánico'),
        ),
        migrations.AddIndex(
            model_name='mechanicservicearea',
            index=models.Index(fields=['taller', 'is_active'], name='usuarios_me_taller__e85de0_idx'),
        ),
        migrations.AddField(
            model_name='horarioproveedor',
            name='miembro_taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_configurados', to='usuarios.miembrotaller'),
        ),
        migrations.AddConstraint(
            model_name='horarioproveedor',
            constraint=models.CheckConstraint(check=models.Q(('taller__isnull', False), ('mecanico__isnull', False), ('miembro_taller__isnull', False), _connector='OR'), name='horario_debe_tener_taller_o_mecanico'),
        ),
        migrations.AddConstraint(
            model_name='horarioproveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('miembro_taller__isnull', True), ('taller__isnull', False)), fields=('taller', 'dia_semana'), name='unique_taller_dia_semana'),
        ),
        migrations.AddConstraint(
            model_name='horarioproveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('miembro_taller__isnull', False)), fields=('miembro_taller', 'dia_semana'), name='unique_miembro_taller_dia_semana'),
        ),
        migrations.AddConstraint(
            model_name='mechanicservicearea',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('mechanic__isnull', False), ('taller__isnull', True)), models.Q(('mechanic__isnull', True), ('taller__isnull', False)), _connector='OR'), name='service_area_xor_proveedor'),
        ),
        migrations.AddField(
            model_name='miembrotaller',
            name='especialidades',
            field=models.ManyToManyField(blank=True, help_text='Especialidades del mecánico', related_name='miembros_taller', to='servicios.categoriaservicio'),
        ),
        migrations.AddField(
            model_name='miembrotaller',
            name='taller',
            field=models.ForeignKey(help_text='Taller al que pertenece el miembro', on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='usuarios.taller'),
        ),
        migrations.AddField(
            model_name='miembrotaller',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario con login (opcional; mecánicos suelen no tener login)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembro_taller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='miembrotaller',
            index=models.Index(fields=['taller', 'rol', 'activo'], name='usuarios_mi_taller__d5f48a_idx'),
        ),
        migrations.AddIndex(
            model_name='miembrotaller',
            index=models.Index(fields=['taller', 'activo'], name='usuarios_mi_taller__852c9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='miembrotaller',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'mandante')), fields=('taller',), name='unique_mandante_por_taller'),
        ),
        migrations.AddConstraint(
            model_name='miembrotaller',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'supervisor')), fields=('taller',), name='unique_supervisor_por_taller'),
        ),
    ]
