# Generated by Django 5.0.13 on 2025-08-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_connectionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionstatus',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Campo booleano para consultas rápidas'),
        ),
        migrations.AddField(
            model_name='connectionstatus',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Último latido del proveedor', null=True),
        ),
        migrations.AddField(
            model_name='connectionstatus',
            name='last_status_change',
            field=models.DateTimeField(auto_now=True, help_text='Último cambio de estado'),
        ),
        migrations.AddField(
            model_name='connectionstatus',
            name='status',
            field=models.CharField(choices=[('online', 'En línea'), ('offline', 'Desconectado'), ('busy', 'En servicio')], default='offline', help_text='Estado actual del proveedor', max_length=20),
        ),
    ]
