# Generated by Django 5.0.13 on 2025-08-02 17:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0024_add_audit_access_model'),
        ('usuarios', '0016_connectionstatus_is_online_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del proveedor', max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='proveedores/')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del proveedor', null=True)),
                ('rut', models.CharField(blank=True, help_text='RUT/CUIT/ID Fiscal', max_length=50, null=True)),
                ('dni', models.CharField(blank=True, help_text='DNI/RUT Personal', max_length=50, null=True)),
                ('experiencia_anos', models.PositiveIntegerField(blank=True, help_text='Años de experiencia', null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Calificación promedio del proveedor', max_digits=3)),
                ('review_count', models.IntegerField(default=0, help_text='Número total de reseñas')),
                ('estado_verificacion', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', help_text='Estado de verificación del proveedor', max_length=20)),
                ('verificado', models.BooleanField(default=False, help_text='Indica si el proveedor ha sido verificado y puede aparecer en la app de clientes')),
                ('onboarding_completado', models.BooleanField(default=False, help_text='Indica si el proveedor completó el proceso de onboarding')),
                ('onboarding_iniciado', models.BooleanField(default=False, help_text='Indica si el proveedor inició el proceso de onboarding')),
                ('fecha_verificacion', models.DateTimeField(blank=True, help_text='Fecha cuando fue verificado el proveedor', null=True)),
                ('descripcion_onboarding', models.TextField(blank=True, help_text='Descripción del proveedor', null=True)),
                ('rut_onboarding', models.CharField(blank=True, help_text='RUT/CUIT/ID Fiscal', max_length=50, null=True)),
                ('dni_onboarding', models.CharField(blank=True, help_text='DNI/RUT Personal', max_length=50, null=True)),
                ('experiencia_anos_onboarding', models.PositiveIntegerField(blank=True, help_text='Años de experiencia', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, help_text='Última vez que el proveedor estuvo conectado en la app', null=True)),
                ('esta_conectado', models.BooleanField(default=False, help_text='Indica si el proveedor está actualmente conectado en la app')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
                ('verificado_por', models.ForeignKey(blank=True, help_text='Usuario administrador que verificó el proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_verificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de proveedor',
                'verbose_name_plural': 'perfiles de proveedores',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Comentario opcional del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Cliente que hizo la reseña', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='Proveedor calificado', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='usuarios.providerprofile')),
                ('service_order', models.OneToOneField(help_text='Orden de servicio asociada', on_delete=django.db.models.deletion.CASCADE, to='ordenes.solicitudservicio')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'provider', 'service_order')},
            },
        ),
    ]
