# Generated by Django 5.0.13 on 2025-08-02 18:16

from django.db import migrations, models
import django.core.validators
import uuid


def migrate_review_provider_data(apps, schema_editor):
    """Migrar datos existentes de Review para usar provider_type y provider_id"""
    Review = apps.get_model('usuarios', 'Review')
    
    # Eliminar registros existentes de Review ya que no hay datos reales
    Review.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_providerprofile_review'),
    ]

    operations = [
        # Primero agregar los nuevos campos
        migrations.AddField(
            model_name='review',
            name='provider_type',
            field=models.CharField(
                choices=[('taller', 'Taller'), ('mecanico', 'Mecánico a Domicilio')],
                help_text='Tipo de proveedor',
                max_length=20,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='review',
            name='provider_id',
            field=models.IntegerField(
                help_text='ID del proveedor (Taller o MecanicoDomicilio)',
                null=True
            ),
        ),
        
        # Ejecutar migración de datos
        migrations.RunPython(migrate_review_provider_data),
        
        # Hacer los campos obligatorios
        migrations.AlterField(
            model_name='review',
            name='provider_type',
            field=models.CharField(
                choices=[('taller', 'Taller'), ('mecanico', 'Mecánico a Domicilio')],
                help_text='Tipo de proveedor',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='provider_id',
            field=models.IntegerField(
                help_text='ID del proveedor (Taller o MecanicoDomicilio)'
            ),
        ),
        
        # Eliminar el campo provider anterior
        migrations.RemoveField(
            model_name='review',
            name='provider',
        ),
        
        # Actualizar unique_together
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('client', 'provider_type', 'provider_id', 'service_order')},
        ),
    ]
