# Generated by Django 4.2.7 on 2026-06-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_migrar_mecanicos_a_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembrotaller',
            name='permisos',
            field=models.JSONField(blank=True, default=dict, help_text='Permisos otorgados a un supervisor (manage por recurso). Vacío para mandante/mecánico.'),
        ),
    ]
