# Generated by Django 5.0.13 on 2025-08-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_remove_provider_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='provider_type',
            field=models.CharField(choices=[('taller', 'Taller'), ('mecanico', 'Mecánico a Domicilio')], help_text='Tipo de proveedor', max_length=20),
        ),
    ]
