# Generated by Django 5.0.13 on 2025-08-28 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_alter_review_provider_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecanicodomicilio',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='direccion',
        ),
    ]
