# Generated by Django 5.0.13 on 2025-11-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_create_tallerdireccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoonboarding',
            name='tipo_documento',
            field=models.CharField(choices=[('dni_frontal', 'DNI/ID Personal (Frontal)'), ('dni_trasero', 'DNI/ID Personal (Trasero)'), ('rut_fiscal', 'RUT/CUIT/ID Fiscal del Negocio'), ('licencia_conducir', 'Licencia de Conducir'), ('curriculum', 'Curriculum Vitae'), ('certificado_antecedentes', 'Certificado de Antecedentes'), ('foto_fachada', 'Foto de la Fachada del Taller'), ('foto_interior', 'Foto del Interior del Taller'), ('foto_equipos', 'Foto de Equipos/Herramientas'), ('foto_herramientas', 'Foto de Herramientas Portátiles'), ('foto_vehiculo', 'Foto de Vehículo de Trabajo')], max_length=50),
        ),
    ]
