# Generated by Django 5.0.13 on 2025-12-04 19:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('freemium', 'Freemium'), ('basica', 'Básica'), ('premium', 'Premium')], help_text='Nombre del plan (freemium, basica, premium)', max_length=50, unique=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio mensual en CLP. 0 para freemium', max_digits=10)),
                ('servicios_incluidos', models.IntegerField(blank=True, help_text='Número de servicios incluidos por mes. null = ilimitado', null=True)),
                ('descripcion', models.TextField(help_text='Descripción del plan y sus beneficios')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el plan está disponible para suscripción')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización en la UI (menor = primero)')),
                ('destacado', models.BooleanField(default=False, help_text='Indica si el plan debe destacarse en la UI')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['orden', 'precio_mensual'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida'), ('pausada', 'Pausada')], default='activa', help_text='Estado actual de la suscripción', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, help_text='Fecha cuando se activó la suscripción', verbose_name='Fecha de Inicio')),
                ('fecha_vencimiento', models.DateTimeField(help_text='Fecha cuando vence la suscripción', verbose_name='Fecha de Vencimiento')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, help_text='Fecha cuando se canceló la suscripción', null=True, verbose_name='Fecha de Cancelación')),
                ('renovacion_automatica', models.BooleanField(default=True, help_text='Indica si la suscripción se renueva automáticamente', verbose_name='Renovación Automática')),
                ('subscription_id_mp', models.CharField(blank=True, help_text='ID de la suscripción en Mercado Pago', max_length=255, null=True, verbose_name='ID Suscripción Mercado Pago')),
                ('payment_method_id_mp', models.CharField(blank=True, help_text='ID del método de pago guardado en Mercado Pago', max_length=255, null=True, verbose_name='ID Método de Pago MP')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='Plan de suscripción activo', on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripciones.plansuscripcion', verbose_name='Plan')),
                ('proveedor', models.OneToOneField(help_text='Usuario proveedor (taller o mecánico)', on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Suscripción de Proveedor',
                'verbose_name_plural': 'Suscripciones de Proveedores',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='UsoServiciosMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(help_text='Mes (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('año', models.IntegerField(help_text='Año (ej: 2024)', validators=[django.core.validators.MinValueValidator(2020)], verbose_name='Año')),
                ('servicios_usados', models.IntegerField(default=0, help_text='Número de ofertas creadas este mes', verbose_name='Servicios Usados')),
                ('servicios_completados', models.IntegerField(default=0, help_text='Número de servicios completados exitosamente este mes', verbose_name='Servicios Completados')),
                ('servicios_adjudicados', models.IntegerField(default=0, help_text='Número de servicios adjudicados (aceptados por cliente) este mes', verbose_name='Servicios Adjudicados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uso_servicios_mensual', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Uso de Servicios Mensual',
                'verbose_name_plural': 'Usos de Servicios Mensuales',
                'ordering': ['-año', '-mes'],
                'indexes': [models.Index(fields=['proveedor', 'año', 'mes'], name='suscripcion_proveed_d68dfd_idx')],
                'unique_together': {('proveedor', 'mes', 'año')},
            },
        ),
    ]
