# Generated by Django 5.0.13 on 2025-12-07 04:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0031_agregar_estados_servicio_y_oferta_proveedor'),
        ('servicios', '0012_fotoservicio'),
        ('suscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCreditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aov_promedio', models.DecimalField(decimal_places=2, default=150000, help_text='Average Order Value promedio en CLP', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='AOV Promedio')),
                ('tasa_comision', models.DecimalField(decimal_places=4, default=0.1, help_text='Tasa de comisión deseada (ej: 0.10 = 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Tasa de Comisión')),
                ('k_promedio', models.IntegerField(default=3, help_text='Créditos promedio consumidos por trabajo', validators=[django.core.validators.MinValueValidator(1)], verbose_name='K Promedio')),
                ('precio_credito_base', models.DecimalField(decimal_places=2, default=5000, help_text='Precio base del crédito calculado automáticamente', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Crédito Base')),
                ('creditos_expiracion_meses', models.IntegerField(default=12, help_text='Meses hasta que los créditos expiren', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Meses de Expiración')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta configuración está activa', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Créditos',
                'verbose_name_plural': 'Configuraciones de Créditos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteCreditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del paquete (ej: "Paquete Básico", "Paquete Premium")', max_length=100, verbose_name='Nombre')),
                ('cantidad_creditos', models.IntegerField(help_text='Número de créditos incluidos en el paquete', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Créditos')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del paquete en CLP', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('bonificacion_creditos', models.IntegerField(default=0, help_text='Créditos extra que se otorgan como bonificación', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bonificación de Créditos')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el paquete está disponible para compra', verbose_name='Activo')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización en la UI (menor = primero)', verbose_name='Orden')),
                ('destacado', models.BooleanField(default=False, help_text='Indica si el paquete debe destacarse en la UI', verbose_name='Destacado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paquete de Créditos',
                'verbose_name_plural': 'Paquetes de Créditos',
                'ordering': ['orden', 'precio'],
                'indexes': [models.Index(fields=['activo', 'orden'], name='suscripcion_activo_98acd1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionCreditosServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditos_requeridos', models.IntegerField(default=2, help_text='Cantidad de créditos que se consumen al adjudicar este servicio', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Créditos Requeridos')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta configuración está activa', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('servicio', models.OneToOneField(help_text='Servicio al que aplica esta configuración', on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_creditos', to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Configuración de Créditos por Servicio',
                'verbose_name_plural': 'Configuraciones de Créditos por Servicio',
                'ordering': ['servicio__nombre'],
                'indexes': [models.Index(fields=['servicio', 'activo'], name='suscripcion_servici_85baf7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsumoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditos_consumidos', models.IntegerField(help_text='Cantidad de créditos consumidos', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Créditos Consumidos')),
                ('precio_credito', models.DecimalField(decimal_places=2, help_text='Precio del crédito al momento del consumo', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio del Crédito')),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True, help_text='Fecha cuando se consumieron los créditos', verbose_name='Fecha de Consumo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('oferta', models.ForeignKey(help_text='Oferta que generó el consumo de créditos', on_delete=django.db.models.deletion.CASCADE, related_name='consumos_credito', to='ordenes.ofertaproveedor', verbose_name='Oferta')),
                ('proveedor', models.ForeignKey(help_text='Proveedor que consumió los créditos', on_delete=django.db.models.deletion.CASCADE, related_name='consumos_creditos', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
                ('servicio', models.ForeignKey(help_text='Servicio por el cual se consumieron los créditos', on_delete=django.db.models.deletion.PROTECT, related_name='consumos_credito', to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Consumo de Crédito',
                'verbose_name_plural': 'Consumos de Créditos',
                'ordering': ['-fecha_consumo'],
                'indexes': [models.Index(fields=['proveedor', 'fecha_consumo'], name='suscripcion_proveed_46317e_idx'), models.Index(fields=['oferta'], name='suscripcion_oferta__6b8bcc_idx'), models.Index(fields=['servicio'], name='suscripcion_servici_b7f29c_idx'), models.Index(fields=['fecha_consumo'], name='suscripcion_fecha_c_365f38_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_creditos', models.IntegerField(default=0, help_text='Cantidad de créditos disponibles', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo de Créditos')),
                ('fecha_ultima_compra', models.DateTimeField(blank=True, help_text='Fecha de la última compra de créditos', null=True, verbose_name='Fecha de Última Compra')),
                ('fecha_ultimo_consumo', models.DateTimeField(blank=True, help_text='Fecha del último consumo de créditos', null=True, verbose_name='Fecha de Último Consumo')),
                ('creditos_expirados', models.IntegerField(default=0, help_text='Cantidad de créditos que han expirado (para tracking)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Créditos Expirados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.OneToOneField(help_text='Usuario proveedor (taller o mecánico)', on_delete=django.db.models.deletion.CASCADE, related_name='credito_proveedor', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Crédito de Proveedor',
                'verbose_name_plural': 'Créditos de Proveedores',
                'ordering': ['-fecha_actualizacion'],
                'indexes': [models.Index(fields=['proveedor'], name='suscripcion_proveed_8c2bb5_idx'), models.Index(fields=['saldo_creditos'], name='suscripcion_saldo_c_cadd18_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompraCreditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_creditos', models.IntegerField(help_text='Cantidad total de créditos (incluye bonificación)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Créditos')),
                ('precio_total', models.DecimalField(decimal_places=2, help_text='Precio total pagado en CLP', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Total')),
                ('metodo_pago', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('transferencia', 'Transferencia Bancaria'), ('migracion', 'Migración de Suscripción')], help_text='Método de pago utilizado', max_length=20, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='pendiente', help_text='Estado de la compra', max_length=20, verbose_name='Estado')),
                ('payment_id_mp', models.CharField(blank=True, help_text='ID del pago en Mercado Pago (si aplica)', max_length=255, null=True, verbose_name='ID Pago Mercado Pago')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, help_text='Fecha cuando se realizó la compra', verbose_name='Fecha de Compra')),
                ('fecha_expiracion_creditos', models.DateTimeField(help_text='Fecha cuando expiran estos créditos', verbose_name='Fecha de Expiración')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(help_text='Usuario proveedor que compra los créditos', on_delete=django.db.models.deletion.CASCADE, related_name='compras_creditos', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
                ('paquete', models.ForeignKey(help_text='Paquete de créditos comprado', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='suscripciones.paquetecreditos', verbose_name='Paquete')),
            ],
            options={
                'verbose_name': 'Compra de Créditos',
                'verbose_name_plural': 'Compras de Créditos',
                'ordering': ['-fecha_compra'],
                'indexes': [models.Index(fields=['proveedor', 'estado'], name='suscripcion_proveed_9d9f9f_idx'), models.Index(fields=['fecha_compra'], name='suscripcion_fecha_c_31d217_idx'), models.Index(fields=['fecha_expiracion_creditos'], name='suscripcion_fecha_e_5d0b96_idx'), models.Index(fields=['estado'], name='suscripcion_estado_8dc483_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProveedorCancelaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelaciones_mes_actual', models.IntegerField(default=0, help_text='Número de cancelaciones en el mes actual', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cancelaciones Mes Actual')),
                ('fecha_reset_cancelaciones', models.DateTimeField(auto_now_add=True, help_text='Fecha del último reset del contador de cancelaciones', verbose_name='Fecha Reset Cancelaciones')),
                ('suspension_temporal', models.BooleanField(default=False, help_text='Indica si el proveedor está suspendido temporalmente', verbose_name='Suspensión Temporal')),
                ('fecha_suspension', models.DateTimeField(blank=True, help_text='Fecha cuando se aplicó la suspensión', null=True, verbose_name='Fecha de Suspensión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.OneToOneField(help_text='Usuario proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='cancelaciones_proveedor', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Cancelaciones de Proveedor',
                'verbose_name_plural': 'Cancelaciones de Proveedores',
                'ordering': ['-fecha_actualizacion'],
                'indexes': [models.Index(fields=['proveedor'], name='suscripcion_proveed_315cba_idx'), models.Index(fields=['suspension_temporal'], name='suscripcion_suspens_8442f9_idx')],
            },
        ),
    ]
