# Generated by Django 5.0.13 on 2026-01-12 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0002_initial'),
        ('servicios', '0002_initial'),
        ('suscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compracreditos',
            name='proveedor',
            field=models.ForeignKey(help_text='Usuario proveedor que compra los créditos', on_delete=django.db.models.deletion.CASCADE, related_name='compras_creditos', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='configuracioncreditosservicio',
            name='servicio',
            field=models.OneToOneField(help_text='Servicio al que aplica esta configuración', on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_creditos', to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='consumocredito',
            name='oferta',
            field=models.ForeignKey(help_text='Oferta que generó el consumo de créditos', on_delete=django.db.models.deletion.CASCADE, related_name='consumos_credito', to='ordenes.ofertaproveedor', verbose_name='Oferta'),
        ),
        migrations.AddField(
            model_name='consumocredito',
            name='proveedor',
            field=models.ForeignKey(help_text='Proveedor que consumió los créditos', on_delete=django.db.models.deletion.CASCADE, related_name='consumos_creditos', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='consumocredito',
            name='servicio',
            field=models.ForeignKey(help_text='Servicio por el cual se consumieron los créditos', on_delete=django.db.models.deletion.PROTECT, related_name='consumos_credito', to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='creditoproveedor',
            name='proveedor',
            field=models.OneToOneField(help_text='Usuario proveedor (taller o mecánico)', on_delete=django.db.models.deletion.CASCADE, related_name='credito_proveedor', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor'),
        ),
        migrations.AddIndex(
            model_name='paquetecreditos',
            index=models.Index(fields=['activo', 'orden'], name='suscripcion_activo_98acd1_idx'),
        ),
        migrations.AddField(
            model_name='compracreditos',
            name='paquete',
            field=models.ForeignKey(help_text='Paquete de créditos comprado', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='suscripciones.paquetecreditos', verbose_name='Paquete'),
        ),
        migrations.AddField(
            model_name='proveedorcancelaciones',
            name='proveedor',
            field=models.OneToOneField(help_text='Usuario proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='cancelaciones_proveedor', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor'),
        ),
        migrations.AddIndex(
            model_name='configuracioncreditosservicio',
            index=models.Index(fields=['servicio', 'activo'], name='suscripcion_servici_85baf7_idx'),
        ),
        migrations.AddIndex(
            model_name='consumocredito',
            index=models.Index(fields=['proveedor', 'fecha_consumo'], name='suscripcion_proveed_46317e_idx'),
        ),
        migrations.AddIndex(
            model_name='consumocredito',
            index=models.Index(fields=['oferta'], name='suscripcion_oferta__6b8bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='consumocredito',
            index=models.Index(fields=['servicio'], name='suscripcion_servici_b7f29c_idx'),
        ),
        migrations.AddIndex(
            model_name='consumocredito',
            index=models.Index(fields=['fecha_consumo'], name='suscripcion_fecha_c_365f38_idx'),
        ),
        migrations.AddIndex(
            model_name='creditoproveedor',
            index=models.Index(fields=['proveedor'], name='suscripcion_proveed_8c2bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='creditoproveedor',
            index=models.Index(fields=['saldo_creditos'], name='suscripcion_saldo_c_cadd18_idx'),
        ),
        migrations.AddIndex(
            model_name='compracreditos',
            index=models.Index(fields=['proveedor', 'estado'], name='suscripcion_proveed_9d9f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='compracreditos',
            index=models.Index(fields=['fecha_compra'], name='suscripcion_fecha_c_31d217_idx'),
        ),
        migrations.AddIndex(
            model_name='compracreditos',
            index=models.Index(fields=['fecha_expiracion_creditos'], name='suscripcion_fecha_e_5d0b96_idx'),
        ),
        migrations.AddIndex(
            model_name='compracreditos',
            index=models.Index(fields=['estado'], name='suscripcion_estado_8dc483_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedorcancelaciones',
            index=models.Index(fields=['proveedor'], name='suscripcion_proveed_315cba_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedorcancelaciones',
            index=models.Index(fields=['suspension_temporal'], name='suscripcion_suspens_8442f9_idx'),
        ),
    ]
