# Generated by Django 5.0.13 on 2025-12-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_crear_modelos_creditos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcionproveedor',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='suscripcionproveedor',
            name='proveedor',
        ),
        migrations.AlterUniqueTogether(
            name='usoserviciosmensual',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usoserviciosmensual',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='PlanSuscripcion',
        ),
        migrations.DeleteModel(
            name='SuscripcionProveedor',
        ),
        migrations.DeleteModel(
            name='UsoServiciosMensual',
        ),
    ]
