# Generated by Django 4.2.7 on 2026-02-20 02:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suscripciones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del plan (ej: "Plan Básico", "Plan Pro")', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del plan y sus beneficios', verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio mensual del plan en CLP', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Mensual (CLP)')),
                ('creditos_mensuales', models.IntegerField(help_text='Cantidad de créditos que se otorgan cada mes al confirmarse el cobro', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Créditos Mensuales')),
                ('mp_preapproval_plan_id', models.CharField(blank=True, help_text='ID del plan de Preapproval en MercadoPago (opcional, si se usan Preapproval Plans)', max_length=255, null=True, verbose_name='ID Plan MercadoPago')),
                ('activo', models.BooleanField(default=True, help_text='Plan disponible para nuevas suscripciones', verbose_name='Activo')),
                ('destacado', models.BooleanField(default=False, help_text='Plan que se destaca visualmente en la UI', verbose_name='Destacado')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización (menor = primero)', verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['orden', 'precio'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='pendiente', help_text='Estado actual de la suscripción', max_length=20, verbose_name='Estado')),
                ('mp_preapproval_id', models.CharField(blank=True, help_text='ID de la suscripción (preapproval) en MercadoPago', max_length=255, null=True, unique=True, verbose_name='ID Preapproval MercadoPago')),
                ('mp_init_point', models.TextField(blank=True, help_text='init_point retornado por MercadoPago para que el proveedor autorice', null=True, verbose_name='URL de Pago Inicial')),
                ('ultimo_charge_id', models.CharField(blank=True, help_text='ID del último cobro procesado (para idempotencia)', max_length=255, null=True, verbose_name='Último Charge ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la suscripción', verbose_name='Fecha de Inicio')),
                ('fecha_proximo_cobro', models.DateTimeField(blank=True, help_text='Fecha estimada del próximo cobro automático', null=True, verbose_name='Próximo Cobro')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, help_text='Fecha en que se canceló la suscripción', null=True, verbose_name='Fecha de Cancelación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='Plan de suscripción contratado', on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripciones.plansuscripcion', verbose_name='Plan')),
                ('proveedor', models.OneToOneField(help_text='Proveedor suscripto', on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion_proveedor', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Suscripción de Proveedor',
                'verbose_name_plural': 'Suscripciones de Proveedores',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='plansuscripcion',
            index=models.Index(fields=['activo', 'orden'], name='suscripcion_activo_db4f89_idx'),
        ),
        migrations.AddIndex(
            model_name='suscripcionproveedor',
            index=models.Index(fields=['proveedor', 'estado'], name='suscripcion_proveed_719e83_idx'),
        ),
        migrations.AddIndex(
            model_name='suscripcionproveedor',
            index=models.Index(fields=['mp_preapproval_id'], name='suscripcion_mp_prea_43ad83_idx'),
        ),
        migrations.AddIndex(
            model_name='suscripcionproveedor',
            index=models.Index(fields=['estado'], name='suscripcion_estado_d30b92_idx'),
        ),
    ]
