# Generated by Django 4.2.7 on 2026-02-26 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0003_add_plan_suscripcion_y_suscripcion_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compracreditos',
            name='paquete',
            field=models.ForeignKey(blank=True, help_text='Paquete de créditos comprado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='suscripciones.paquetecreditos', verbose_name='Paquete'),
        ),
    ]
