# Generated by Django 5.2.1 on 2026-01-30 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0010_ofertavehiculo_conversacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_transferencia', models.CharField(editable=False, max_length=64, unique=True)),
                ('qr_data', models.TextField(help_text='Datos encriptados para generar el QR')),
                ('fecha_expiracion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('EXPIRADO', 'Expirado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_compras', to=settings.AUTH_USER_MODEL)),
                ('oferta_asociada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia', to='vehiculos.ofertavehiculo')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='vehiculos.vehiculo')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transferencia de vehículo',
                'verbose_name_plural': 'transferencias de vehículos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
