# Generated by Django 5.0.13 on 2026-01-12 16:41

import django.contrib.gis.db.models.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaDescartada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('pago_proximo', 'Pago Próximo'), ('pago_expirado', 'Pago Expirado')], max_length=20, verbose_name='Tipo de Alerta')),
                ('fecha_descarte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Descarte')),
            ],
            options={
                'verbose_name': 'Alerta Descartada',
                'verbose_name_plural': 'Alertas Descartadas',
                'ordering': ['-fecha_descarte'],
            },
        ),
        migrations.CreateModel(
            name='AuditAccesoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('tipo_acceso', models.CharField(choices=[('vista_listado', 'Vista de Listado'), ('vista_detalle', 'Vista de Detalle'), ('contacto_directo', 'Contacto Directo'), ('exportacion', 'Exportación de Datos')], max_length=20)),
                ('nivel_informacion', models.CharField(choices=[('parcial', 'Información Parcial'), ('completo', 'Información Completa'), ('restringido', 'Acceso Restringido')], max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('estado_orden_acceso', models.CharField(help_text='Estado de la orden al momento del acceso', max_length=40)),
                ('datos_accedidos', models.JSONField(default=dict, help_text='Lista de campos específicos accedidos')),
                ('justificacion', models.CharField(blank=True, help_text='Justificación automática del acceso', max_length=200, null=True)),
                ('acceso_autorizado', models.BooleanField(default=True, help_text='Si el acceso estaba autorizado según las reglas de negocio')),
                ('requiere_revision', models.BooleanField(default=False, help_text='Si este acceso requiere revisión manual')),
            ],
            options={
                'verbose_name': 'Auditoría de Acceso a Cliente',
                'verbose_name_plural': 'Auditorías de Acceso a Clientes',
                'ordering': ['-fecha_acceso'],
            },
        ),
        migrations.CreateModel(
            name='CarritoAgendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('hora_programada', models.TimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el carrito', null=True)),
            ],
            options={
                'verbose_name': 'carrito de agendamiento',
                'verbose_name_plural': 'carritos de agendamiento',
            },
        ),
        migrations.CreateModel(
            name='ChatSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('es_proveedor', models.BooleanField(default=False, help_text='True si el mensaje es del proveedor, False si es del cliente', verbose_name='Es del Proveedor')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Envío')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='chat_solicitudes/%Y/%m/', verbose_name='Archivo Adjunto')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat de Solicitud',
                'verbose_name_plural': 'Mensajes de Chat de Solicitudes',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=19.0, help_text='Porcentaje de IVA a aplicar', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tarifa_servicio_porcentaje', models.DecimalField(decimal_places=2, default=3.0, help_text='Porcentaje de tarifa de servicio a aplicar', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta configuración está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'configuración de precio',
                'verbose_name_plural': 'configuraciones de precio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleServicioOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_servicio', models.DecimalField(decimal_places=2, help_text='Precio específico de este servicio en la oferta', max_digits=10, verbose_name='Precio')),
                ('tiempo_estimado', models.DurationField(help_text='Tiempo estimado para este servicio específico', verbose_name='Tiempo Estimado')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre este servicio', verbose_name='Notas')),
                ('repuestos_seleccionados', models.JSONField(blank=True, default=list, help_text='Lista de repuestos seleccionados para este servicio en formato JSON', verbose_name='Repuestos Seleccionados')),
            ],
            options={
                'verbose_name': 'Detalle de Servicio en Oferta',
                'verbose_name_plural': 'Detalles de Servicios en Ofertas',
            },
        ),
        migrations.CreateModel(
            name='ItemCarritoAgendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_repuestos', models.BooleanField(default=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_servicio', models.DateField(blank=True, null=True)),
                ('hora_servicio', models.TimeField(blank=True, null=True)),
                ('configuracion_repuestos', models.JSONField(blank=True, help_text='Configuración JSON de repuestos seleccionados', null=True)),
                ('notas_repuestos', models.TextField(blank=True, help_text='Notas adicionales sobre los repuestos', null=True)),
            ],
            options={
                'verbose_name': 'item de carrito de agendamiento',
                'verbose_name_plural': 'items de carrito de agendamiento',
            },
        ),
        migrations.CreateModel(
            name='LineaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_repuestos', models.BooleanField(default=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'línea de servicio',
                'verbose_name_plural': 'líneas de servicio',
            },
        ),
        migrations.CreateModel(
            name='OfertaProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_proveedor', models.CharField(choices=[('taller', 'Taller'), ('mecanico', 'Mecánico a Domicilio')], max_length=20, verbose_name='Tipo de Proveedor')),
                ('precio_total_ofrecido', models.DecimalField(decimal_places=2, help_text='Precio total de la oferta (suma de todos los servicios)', max_digits=10, verbose_name='Precio Total')),
                ('incluye_repuestos', models.BooleanField(default=False, help_text='Indica si el precio incluye repuestos', verbose_name='Incluye Repuestos')),
                ('tiempo_estimado_total', models.DurationField(help_text='Tiempo total estimado para completar todos los servicios', verbose_name='Tiempo Estimado Total')),
                ('descripcion_oferta', models.TextField(help_text='Descripción detallada de la oferta', verbose_name='Descripción')),
                ('garantia_ofrecida', models.CharField(blank=True, help_text='Garantía ofrecida (ej: "6 meses o 10,000 km")', max_length=200, verbose_name='Garantía')),
                ('fecha_disponible', models.DateField(help_text='Fecha en que el proveedor puede realizar el servicio', verbose_name='Fecha Disponible')),
                ('hora_disponible', models.TimeField(help_text='Hora en que el proveedor puede realizar el servicio', verbose_name='Hora Disponible')),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('vista', 'Vista por Cliente'), ('en_chat', 'En Conversación'), ('aceptada', 'Aceptada por Cliente'), ('pendiente_pago', 'Cliente Procesando Pago'), ('pagada_parcialmente', 'Pagada Parcialmente - Pendiente Saldo'), ('pagada', 'Pagada - Listo para Iniciar'), ('en_ejecucion', 'En Ejecución - Servicio en Progreso'), ('completada', 'Completada - Servicio Finalizado'), ('rechazada', 'Rechazada'), ('retirada', 'Retirada por Proveedor'), ('expirada', 'Expirada')], db_index=True, default='enviada', max_length=20, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('fecha_visualizacion_cliente', models.DateTimeField(blank=True, help_text='Momento en que el cliente vio la oferta', null=True, verbose_name='Fecha de Visualización')),
                ('fecha_respuesta_cliente', models.DateTimeField(blank=True, help_text='Momento en que el cliente respondió (aceptó/rechazó)', null=True, verbose_name='Fecha de Respuesta')),
                ('tiempo_respuesta_proveedor', models.DurationField(blank=True, help_text='Tiempo que tardó el proveedor en enviar la oferta desde publicación', null=True, verbose_name='Tiempo de Respuesta del Proveedor')),
                ('es_oferta_secundaria', models.BooleanField(default=False, help_text='Indica si esta es una oferta secundaria (servicio adicional)', verbose_name='Es Oferta Secundaria')),
                ('motivo_servicio_adicional', models.TextField(blank=True, help_text='Explicación del proveedor sobre por qué se requiere este servicio adicional', verbose_name='Motivo del Servicio Adicional')),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de los repuestos cotizados (sin IVA)', max_digits=10, verbose_name='Costo Repuestos')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, help_text='Costo de mano de obra del servicio (sin IVA)', max_digits=10, verbose_name='Costo Mano de Obra')),
                ('costo_gestion_compra', models.DecimalField(decimal_places=2, default=0, help_text='Costo de gestión y traslado para compra de repuestos (sin IVA). Aplica solo cuando incluye_repuestos=True', max_digits=10, verbose_name='Costo Gestión de Compra')),
                ('foto_cotizacion_repuestos', models.URLField(blank=True, help_text='URL de la foto de la cotización de repuestos de la casa de repuestos', max_length=500, null=True, verbose_name='Foto Cotización Repuestos')),
                ('metodo_pago_cliente', models.CharField(choices=[('repuestos_adelantado', 'Repuestos Adelantado + Servicio al Final'), ('todo_adelantado', 'Todo Adelantado'), ('pendiente', 'Pendiente de Selección')], default='pendiente', help_text='Método de pago elegido por el cliente para esta oferta', max_length=25, verbose_name='Método de Pago Cliente')),
                ('estado_pago_repuestos', models.CharField(choices=[('no_aplica', 'No Aplica (Sin Repuestos o Todo Adelantado)'), ('pendiente', 'Pendiente de Pago'), ('pagado', 'Repuestos Pagados')], default='no_aplica', help_text='Estado del pago de repuestos', max_length=20, verbose_name='Estado Pago Repuestos')),
                ('estado_pago_servicio', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Servicio Pagado')], default='pendiente', help_text='Estado del pago del servicio/mano de obra', max_length=20, verbose_name='Estado Pago Servicio')),
            ],
            options={
                'verbose_name': 'Oferta de Proveedor',
                'verbose_name_plural': 'Ofertas de Proveedores',
                'ordering': ['precio_total_ofrecido', '-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='RechazoSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_proveedor', models.CharField(choices=[('taller', 'Taller'), ('mecanico', 'Mecánico a Domicilio')], max_length=20, verbose_name='Tipo de Proveedor')),
                ('motivo', models.CharField(choices=[('ocupado', 'No tengo disponibilidad en esas fechas'), ('lejos', 'La ubicación está muy lejos de mi área'), ('no_servicio', 'No realizo ese tipo de servicio'), ('no_marca', 'No trabajo con esa marca de vehículo'), ('precio', 'El precio esperado no es viable'), ('complejidad', 'El trabajo es muy complejo para mi taller'), ('recursos', 'No cuento con las herramientas/repuestos necesarios'), ('politica', 'No cumplo con políticas del cliente'), ('otro', 'Otro motivo')], max_length=20, verbose_name='Motivo del Rechazo')),
                ('detalle_motivo', models.TextField(blank=True, help_text='Explicación adicional del proveedor', max_length=500, verbose_name='Detalle')),
                ('fecha_rechazo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Rechazo')),
                ('tiempo_respuesta', models.DurationField(blank=True, help_text='Tiempo entre publicación y rechazo', null=True, verbose_name='Tiempo de Respuesta')),
            ],
            options={
                'verbose_name': 'Rechazo de Solicitud',
                'verbose_name_plural': 'Rechazos de Solicitudes',
                'ordering': ['-fecha_rechazo'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_solicitud', models.DateTimeField(auto_now_add=True)),
                ('ubicacion_servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_servicio', models.CharField(choices=[('taller', 'Taller'), ('domicilio', 'Domicilio')], max_length=20)),
                ('fecha_servicio', models.DateField()),
                ('hora_servicio', models.TimeField()),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito'), ('transferencia', 'Transferencia')], max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pago_validado', 'Pago Validado'), ('confirmado', 'Confirmado'), ('pendiente_aceptacion_proveedor', 'Pendiente de Aceptación del Proveedor'), ('aceptada_por_proveedor', 'Aceptada por Proveedor'), ('rechazada_por_proveedor', 'Rechazada por Proveedor'), ('checklist_en_progreso', 'Checklist en Progreso'), ('checklist_completado', 'Checklist Completado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('solicitud_cancelacion', 'Solicitud de Cancelación'), ('pendiente_devolucion', 'Pendiente de Devolución'), ('devuelto', 'Devuelto')], default='pendiente', max_length=40)),
                ('comprobante_pago', models.ImageField(blank=True, help_text='Comprobante de pago subido por el cliente', null=True, upload_to='comprobantes/')),
                ('comprobante_validado', models.BooleanField(default=False, help_text='Indica si el comprobante de pago ha sido validado por un administrador')),
                ('fecha_validacion', models.DateTimeField(blank=True, help_text='Fecha cuando se validó el comprobante de pago', null=True)),
                ('notas_cliente', models.TextField(blank=True, help_text='Notas adicionales del cliente sobre la solicitud', null=True)),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas del administrador', null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, help_text='Motivo de la cancelación proporcionado por el cliente', null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, help_text='Fecha cuando se procesó la cancelación', null=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, help_text='Fecha cuando se procesó la devolución', null=True)),
                ('devolucion_procesada', models.BooleanField(default=False, help_text='Indica si la devolución ha sido procesada')),
                ('requiere_devolucion', models.BooleanField(default=False, help_text='Indica si la solicitud requiere devolución')),
                ('fecha_respuesta_proveedor', models.DateTimeField(blank=True, help_text='Fecha cuando el proveedor respondió a la solicitud', null=True)),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Motivo del rechazo por parte del proveedor', null=True)),
                ('notas_proveedor', models.TextField(blank=True, help_text='Notas adicionales del proveedor sobre la orden', null=True)),
            ],
            options={
                'verbose_name': 'solicitud de servicio',
                'verbose_name_plural': 'solicitudes de servicio',
            },
        ),
        migrations.CreateModel(
            name='SolicitudServicioPublica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion_problema', models.TextField(help_text='Descripción libre del problema o necesidad del cliente', verbose_name='Descripción del Problema')),
                ('urgencia', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Urgencia')),
                ('requiere_repuestos', models.BooleanField(default=True, help_text='Indica si la solicitud requiere repuestos o solo mano de obra', verbose_name='Requiere Repuestos')),
                ('tipo_solicitud', models.CharField(choices=[('global', 'Abierta a Todos'), ('dirigida', 'Solo Proveedores Específicos')], default='global', help_text='Global: broadcast a todos. Dirigida: solo proveedores seleccionados', max_length=20, verbose_name='Tipo de Solicitud')),
                ('ubicacion_servicio', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Coordenadas geográficas del servicio', srid=4326, verbose_name='Ubicación del Servicio')),
                ('direccion_servicio_texto', models.CharField(help_text='Dirección en formato texto legible', max_length=500, verbose_name='Dirección del Servicio')),
                ('detalles_ubicacion', models.CharField(blank=True, help_text='Detalles adicionales (ej: Depto 4B, portón verde)', max_length=255, verbose_name='Detalles de Ubicación')),
                ('fecha_preferida', models.DateField(help_text='Fecha preferida por el cliente', verbose_name='Fecha Preferida')),
                ('hora_preferida', models.TimeField(blank=True, help_text='Hora preferida (opcional)', null=True, verbose_name='Hora Preferida')),
                ('estado', models.CharField(choices=[('creada', 'Creada - Pendiente Servicios'), ('seleccionando_servicios', 'Seleccionando Servicios'), ('publicada', 'Publicada - Esperando Ofertas'), ('con_ofertas', 'Con Ofertas Recibidas'), ('adjudicada', 'Adjudicada a Proveedor'), ('pendiente_pago', 'Cliente Procesando Pago'), ('pagada', 'Pago Completado - Listo para Iniciar'), ('en_ejecucion', 'Servicio en Progreso'), ('completada', 'Servicio Finalizado'), ('expirada', 'Expirada Sin Ofertas'), ('cancelada', 'Cancelada por Cliente')], db_index=True, default='creada', max_length=30, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_publicacion', models.DateTimeField(blank=True, help_text='Momento en que se publicó a proveedores', null=True, verbose_name='Fecha de Publicación')),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha límite para recibir ofertas', verbose_name='Fecha de Expiración')),
                ('fecha_limite_pago', models.DateTimeField(blank=True, help_text='Fecha límite para pagar después de adjudicar (fecha del servicio)', null=True, verbose_name='Fecha Límite de Pago')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('total_ofertas', models.IntegerField(default=0, verbose_name='Total de Ofertas Recibidas')),
                ('total_visualizaciones', models.IntegerField(default=0, help_text='Cuántos proveedores vieron esta solicitud', verbose_name='Total de Visualizaciones')),
                ('total_rechazos', models.IntegerField(default=0, help_text='Total de rechazos recibidos de proveedores', verbose_name='Total de Rechazos')),
            ],
            options={
                'verbose_name': 'Solicitud Pública de Servicio',
                'verbose_name_plural': 'Solicitudes Públicas de Servicio',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
