# Generated by Django 5.0.13 on 2026-01-12 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertadescartada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_descartadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='auditaccesocliente',
            name='usuario_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_auditados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carritoagendamiento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='carritoagendamiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='chatsolicitud',
            name='enviado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados_solicitudes', to=settings.AUTH_USER_MODEL, verbose_name='Enviado Por'),
        ),
        migrations.AddField(
            model_name='detalleserviciooferta',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_en_ofertas', to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='itemcarritoagendamiento',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordenes.carritoagendamiento'),
        ),
        migrations.AddField(
            model_name='itemcarritoagendamiento',
            name='oferta_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='servicios.ofertaservicio'),
        ),
        migrations.AddField(
            model_name='lineaservicio',
            name='oferta_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas_servicio', to='servicios.ofertaservicio'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='oferta_original',
            field=models.ForeignKey(blank=True, help_text='Oferta original a la que está asociada esta oferta secundaria', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_secundarias', to='ordenes.ofertaproveedor', verbose_name='Oferta Original'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='proveedor',
            field=models.ForeignKey(help_text='Usuario proveedor. Debe tener taller o mecanico_domicilio relacionado.', on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='servicios_ofertados',
            field=models.ManyToManyField(related_name='ofertas_que_incluyen', through='ordenes.DetalleServicioOferta', to='servicios.servicio', verbose_name='Servicios Ofertados'),
        ),
        migrations.AddField(
            model_name='detalleserviciooferta',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicios', to='ordenes.ofertaproveedor', verbose_name='Oferta'),
        ),
        migrations.AddField(
            model_name='chatsolicitud',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_chat', to='ordenes.ofertaproveedor', verbose_name='Oferta'),
        ),
        migrations.AddField(
            model_name='rechazosolicitud',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechazos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='usuarios.mecanicodomicilio'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='oferta_proveedor',
            field=models.ForeignKey(blank=True, help_text='Oferta de proveedor que originó esta solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_servicio', to='ordenes.ofertaproveedor', verbose_name='Oferta Proveedor'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='usuarios.taller'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='lineaservicio',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ordenes.solicitudservicio'),
        ),
        migrations.AddField(
            model_name='auditaccesocliente',
            name='solicitud_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_acceso', to='ordenes.solicitudservicio'),
        ),
        migrations.AddField(
            model_name='solicitudserviciopublica',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_publicas', to='usuarios.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='solicitudserviciopublica',
            name='direccion_usuario',
            field=models.ForeignKey(blank=True, help_text='Dirección registrada del usuario para el servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_en_esta_direccion', to='usuarios.direccionusuario', verbose_name='Dirección del Usuario'),
        ),
        migrations.AddField(
            model_name='solicitudserviciopublica',
            name='oferta_seleccionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_ganada', to='ordenes.ofertaproveedor', verbose_name='Oferta Seleccionada'),
        ),
        migrations.AddField(
            model_name='solicitudserviciopublica',
            name='proveedores_dirigidos',
            field=models.ManyToManyField(blank=True, help_text='Proveedores específicos para solicitud dirigida (máx 5). Deben tener taller o mecanico_domicilio relacionado.', related_name='solicitudes_dirigidas_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Proveedores Dirigidos'),
        ),
        migrations.AddField(
            model_name='solicitudserviciopublica',
            name='servicios_solicitados',
            field=models.ManyToManyField(blank=True, help_text='Servicios específicos seleccionados por el cliente', related_name='solicitudes_publicas', to='servicios.servicio', verbose_name='Servicios Solicitados'),
        ),
        migrations.AddField(
            model_name='solicitudserviciopublica',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_publicas', to='vehiculos.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AddField(
            model_name='rechazosolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechazos', to='ordenes.solicitudserviciopublica', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='ordenes.solicitudserviciopublica', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='alertadescartada',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_descartadas', to='ordenes.solicitudserviciopublica', verbose_name='Solicitud'),
        ),
        migrations.AddIndex(
            model_name='carritoagendamiento',
            index=models.Index(fields=['cliente', 'activo'], name='carrito_cliente_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='carritoagendamiento',
            index=models.Index(fields=['vehiculo', 'activo'], name='carrito_vehiculo_activo_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarritoagendamiento',
            unique_together={('carrito', 'oferta_servicio')},
        ),
        migrations.AlterUniqueTogether(
            name='detalleserviciooferta',
            unique_together={('oferta', 'servicio')},
        ),
        migrations.AddIndex(
            model_name='chatsolicitud',
            index=models.Index(fields=['oferta', 'fecha_envio'], name='ordenes_cha_oferta__eac929_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsolicitud',
            index=models.Index(fields=['enviado_por', '-fecha_envio'], name='ordenes_cha_enviado_e7bad0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditaccesocliente',
            index=models.Index(fields=['fecha_acceso'], name='ordenes_aud_fecha_a_35fbd8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditaccesocliente',
            index=models.Index(fields=['usuario_proveedor', 'fecha_acceso'], name='ordenes_aud_usuario_a81460_idx'),
        ),
        migrations.AddIndex(
            model_name='auditaccesocliente',
            index=models.Index(fields=['solicitud_servicio', 'fecha_acceso'], name='ordenes_aud_solicit_3a292c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditaccesocliente',
            index=models.Index(fields=['requiere_revision'], name='ordenes_aud_requier_6bdf5d_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudserviciopublica',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='ordenes_sol_estado_560b60_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudserviciopublica',
            index=models.Index(fields=['cliente', 'estado'], name='ordenes_sol_cliente_e182f0_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudserviciopublica',
            index=models.Index(fields=['fecha_expiracion'], name='ordenes_sol_fecha_e_cf69ed_idx'),
        ),
        migrations.AddIndex(
            model_name='rechazosolicitud',
            index=models.Index(fields=['solicitud', 'proveedor'], name='ordenes_rec_solicit_7b3424_idx'),
        ),
        migrations.AddIndex(
            model_name='rechazosolicitud',
            index=models.Index(fields=['motivo'], name='ordenes_rec_motivo_1cd5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='rechazosolicitud',
            index=models.Index(fields=['fecha_rechazo'], name='ordenes_rec_fecha_r_e75594_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rechazosolicitud',
            unique_together={('solicitud', 'proveedor')},
        ),
        migrations.AddIndex(
            model_name='ofertaproveedor',
            index=models.Index(fields=['solicitud', 'estado'], name='ordenes_ofe_solicit_c58e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='ofertaproveedor',
            index=models.Index(fields=['proveedor', 'estado'], name='ordenes_ofe_proveed_cdb620_idx'),
        ),
        migrations.AddIndex(
            model_name='ofertaproveedor',
            index=models.Index(fields=['precio_total_ofrecido'], name='ordenes_ofe_precio__0c504f_idx'),
        ),
        migrations.AddIndex(
            model_name='ofertaproveedor',
            index=models.Index(fields=['oferta_original', 'es_oferta_secundaria'], name='ordenes_ofe_oferta__a1189b_idx'),
        ),
        migrations.AddIndex(
            model_name='alertadescartada',
            index=models.Index(fields=['usuario', 'solicitud', 'tipo_alerta'], name='ordenes_ale_usuario_4522fb_idx'),
        ),
        migrations.AddIndex(
            model_name='alertadescartada',
            index=models.Index(fields=['fecha_descarte'], name='ordenes_ale_fecha_d_163607_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertadescartada',
            unique_together={('usuario', 'solicitud', 'tipo_alerta')},
        ),
    ]
