# Generated by Django 5.0.13 on 2025-05-16 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='orden',
            name='mecanico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='usuarios.mecanicodomicilio'),
        ),
        migrations.AddField(
            model_name='orden',
            name='servicios',
            field=models.ManyToManyField(related_name='ordenes', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='orden',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='vehiculos.vehiculo'),
        ),
    ]
