# Generated by Django 4.2.7 on 2026-02-02 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0012_componentesalud_reglamantenimientoespecifica_and_more'),
        ('ordenes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='vehiculos.vehiculo'),
        ),
        migrations.AlterField(
            model_name='solicitudserviciopublica',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_publicas', to='vehiculos.vehiculo', verbose_name='Vehículo'),
        ),
    ]
