# Generated by Django 5.0.13 on 2025-05-17 04:43
# MODIFICADO: Los campos precio_servicio_mecanico, precio_servicio_taller y servicio
# nunca se crearon en 0003 (versión modificada), así que no necesitan eliminarse.

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_disponibilidad_solicitudservicio_lineaservicio_and_more'),
    ]

    operations = [
        # NOTA: RemoveField para precio_servicio_mecanico, precio_servicio_taller
        # y servicio fueron eliminados porque estos campos nunca se crearon
        # en 0003 (versión modificada para producción).
        migrations.AddField(
            model_name='lineaservicio',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lineaservicio',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado a esta línea', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
