# Generated by Django 5.0.13 on 2025-05-17 04:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_refactorizacion_fase1'),
        ('servicios', '0006_refactorizacion_fase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaservicio',
            name='oferta_servicio',
            field=models.ForeignKey(blank=True, help_text='La oferta específica seleccionada (incluye servicio y proveedor)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='servicios.ofertaservicio'),
        ),
        migrations.AddField(
            model_name='lineaservicio',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario del servicio (con o sin repuestos según selección)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lineaservicio',
            name='con_repuestos',
            field=models.BooleanField(default=True),
        ),
    ]
