# Generated by Django 5.2.1 on 2025-05-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_merge_20250516_2326'),
        ('servicios', '0008_remove_servicio_marcas_compatibles_and_more'),
        ('usuarios', '0004_merge_20250516_2326'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoAgendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_servicio', models.DateField(blank=True, null=True)),
                ('hora_servicio', models.TimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos_agendamiento', to='usuarios.cliente')),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carritos_agendamiento', to='usuarios.taller')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos_agendamiento', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'carrito de agendamiento',
                'verbose_name_plural': 'carritos de agendamiento',
                'unique_together': {('cliente', 'vehiculo', 'activo')},
            },
        ),
        migrations.CreateModel(
            name='ItemCarritoAgendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_repuestos', models.BooleanField(default=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordenes.carritoagendamiento')),
                ('oferta_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='servicios.ofertaservicio')),
            ],
            options={
                'verbose_name': 'item de carrito de agendamiento',
                'verbose_name_plural': 'items de carrito de agendamiento',
                'unique_together': {('carrito', 'oferta_servicio')},
            },
        ),
        migrations.CreateModel(
            name='SlotDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('ocupado', models.BooleanField(default=False)),
                ('reservado_temporalmente', models.BooleanField(default=False)),
                ('fecha_reserva_temporal', models.DateTimeField(blank=True, null=True)),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='ordenes.disponibilidad')),
                ('solicitud_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots_ocupados', to='ordenes.solicitudservicio')),
            ],
            options={
                'verbose_name': 'slot de disponibilidad',
                'verbose_name_plural': 'slots de disponibilidad',
                'unique_together': {('disponibilidad', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
