# Generated by Django 5.0.13 on 2025-05-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_carritoagendamiento_itemcarritoagendamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='comprobante_validado',
            field=models.BooleanField(default=False, help_text='Indica si el comprobante de transferencia ha sido validado'),
        ),
    ]
