# Generated by Django 4.2.7 on 2026-05-09 23:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_pendiente_firma_cliente_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoSolicitudPublica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='solicitudes_publicas/fotos_necesidad/', verbose_name='Imagen')),
                ('orden', models.PositiveSmallIntegerField(default=1, help_text='Orden de visualización (1–3)', verbose_name='Orden')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_necesidad', to='ordenes.solicitudserviciopublica', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Foto de solicitud pública',
                'verbose_name_plural': 'Fotos de solicitudes públicas',
                'ordering': ['orden', 'fecha_subida'],
                'indexes': [models.Index(fields=['solicitud', 'orden'], name='ordenes_fot_solicit_4db60c_idx')],
            },
        ),
    ]
