# Generated by Django 5.0.13 on 2025-05-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_alter_solicitudservicio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='comentario_cancelacion',
            field=models.TextField(blank=True, help_text='Comentario adicional sobre la cancelación', null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='devolucion_procesada',
            field=models.BooleanField(default=False, help_text='Indica si la devolución ya fue procesada'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se procesó la devolución', null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='fecha_solicitud_cancelacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se solicitó la cancelación', null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, choices=[('cliente_desiste', 'Cliente desiste del servicio'), ('problema_vehiculo', 'Problema con el vehículo'), ('emergencia_personal', 'Emergencia personal'), ('cambio_fecha', 'Necesita cambiar fecha'), ('insatisfaccion_precio', 'Insatisfacción con el precio'), ('otro', 'Otro motivo')], help_text='Motivo de la cancelación si aplica', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='requiere_devolucion',
            field=models.BooleanField(default=False, help_text='Indica si se requiere procesar devolución de dinero'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pago_validado', 'Pago Validado'), ('confirmado', 'Confirmado'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('cancelacion_solicitada', 'Cancelación Solicitada'), ('devolucion_procesada', 'Devolución Procesada')], default='pendiente', max_length=30),
        ),
    ]
