# Generated by Django 5.0.13 on 2025-05-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_fix_carrito_unique_constraint'),
        ('ordenes', '0010_solicitudservicio_comentario_cancelacion_and_more'),
    ]

    operations = [
    ]
