# Generated by Django 5.0.13 on 2025-05-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0011_merge_20250527_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarritoagendamiento',
            name='fecha_servicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcarritoagendamiento',
            name='hora_servicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
