# Generated by Django 5.0.13 on 2025-05-31 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0012_agregar_fecha_hora_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=19.0, help_text='Porcentaje de IVA a aplicar (ej: 19.00 para 19%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tarifa_servicio_porcentaje', models.DecimalField(decimal_places=2, default=3.0, help_text='Porcentaje de tarifa de servicio MecaniMovil (ej: 3.00 para 3%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('activo', models.BooleanField(default=True, help_text='Solo puede haber una configuración activa a la vez')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración de precio',
                'verbose_name_plural': 'configuraciones de precio',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
