# Generated by Django 5.0.13 on 2025-06-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0013_configuracionprecio'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarritoagendamiento',
            name='configuracion_repuestos',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración de repuestos (incluye, tipo, garantía, etc.)'),
        ),
        migrations.AddField(
            model_name='itemcarritoagendamiento',
            name='repuestos_configurados',
            field=models.JSONField(blank=True, default=list, help_text='Lista de repuestos específicos configurados para este servicio'),
        ),
    ]
