# Generated by Django 5.0.13 on 2025-06-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0014_itemcarritoagendamiento_configuracion_repuestos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarritoagendamiento',
            name='repuestos_configurados',
        ),
        migrations.AddField(
            model_name='itemcarritoagendamiento',
            name='notas_repuestos',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre los repuestos', null=True),
        ),
        migrations.AlterField(
            model_name='itemcarritoagendamiento',
            name='configuracion_repuestos',
            field=models.JSONField(blank=True, help_text='Configuración JSON de repuestos seleccionados', null=True),
        ),
    ]
