# Generated by Django 4.2.7 on 2026-06-22 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0014_cita_agenda_personal'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='citaagendapersonal',
            name='cita_xor_proveedor',
        ),
        migrations.RemoveConstraint(
            model_name='citaagendapersonaldetalle',
            name='cita_detalle_servicio_requerido',
        ),
        # En producción (Render) estos índices ya fueron renombrados por una
        # migración 0014 fantasma (aplicada pero sin archivo en el repo). Los
        # renames se hacen idempotentes: en BD nuevas renombran; en Render no-op.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='patronaprendizajenecesidad',
                    new_name='ordenes_pat_fragmen_5a63a6_idx',
                    old_name='ordenes_pat_fragmen_idx',
                ),
                migrations.RenameIndex(
                    model_name='patronaprendizajenecesidad',
                    new_name='ordenes_pat_confirm_e32a22_idx',
                    old_name='ordenes_pat_confirm_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS ordenes_pat_fragmen_idx RENAME TO ordenes_pat_fragmen_5a63a6_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS ordenes_pat_fragmen_5a63a6_idx RENAME TO ordenes_pat_fragmen_idx;",
                ),
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS ordenes_pat_confirm_idx RENAME TO ordenes_pat_confirm_e32a22_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS ordenes_pat_confirm_e32a22_idx RENAME TO ordenes_pat_confirm_idx;",
                ),
            ],
        ),
    ]
