# Generated by Django 5.0.13 on 2025-06-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0015_agregar_campos_repuestos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='fecha_respuesta_proveedor',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando el proveedor respondió a la solicitud', null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Motivo del rechazo por parte del proveedor', null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='notas_proveedor',
            field=models.TextField(blank=True, help_text='Notas adicionales del proveedor sobre la orden', null=True),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pendiente_aceptacion_proveedor', 'Pendiente Aceptación Proveedor'), ('aceptada_por_proveedor', 'Aceptada por Proveedor'), ('rechazada_por_proveedor', 'Rechazada por Proveedor'), ('pago_validado', 'Pago Validado'), ('confirmado', 'Confirmado'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('cancelacion_solicitada', 'Cancelación Solicitada'), ('devolucion_procesada', 'Devolución Procesada')], default='pendiente', max_length=30),
        ),
    ]
