# Generated by Django 4.2.7 on 2026-06-22 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_miembrotaller_and_more'),
        ('ordenes', '0015_remove_citaagendapersonal_cita_xor_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaagendapersonal',
            name='miembro_taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_agenda_personal', to='usuarios.miembrotaller'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='mecanico_asignado',
            field=models.ForeignKey(blank=True, help_text='Mecánico del equipo del taller asignado a esta orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to='usuarios.miembrotaller'),
        ),
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='metodo_pago_cliente',
            field=models.CharField(choices=[('repuestos_adelantado', 'Repuestos Adelantado + Servicio al Final'), ('todo_adelantado', 'Todo Adelantado'), ('cliente_compra_repuestos', 'Cliente Compra sus Propios Repuestos'), ('pendiente', 'Pendiente de Selección')], default='pendiente', help_text='Método de pago elegido por el cliente para esta oferta', max_length=25, verbose_name='Método de Pago Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito'), ('transferencia', 'Transferencia'), ('mercadopago', 'Mercado Pago')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='citaagendapersonal',
            index=models.Index(fields=['miembro_taller', 'fecha_servicio', 'estado'], name='cita_miembro_fecha_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='citaagendapersonal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('mecanico__isnull', True), ('taller__isnull', False)), models.Q(('mecanico__isnull', False), ('taller__isnull', True)), _connector='OR'), name='cita_xor_proveedor'),
        ),
        migrations.AddConstraint(
            model_name='citaagendapersonaldetalle',
            constraint=models.CheckConstraint(check=models.Q(('oferta_servicio__isnull', False), models.Q(('servicio_nombre', ''), _negated=True), _connector='OR'), name='cita_detalle_servicio_requerido'),
        ),
    ]
