# Generated by Django 4.1.3 on 2025-01-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0016_solicitudservicio_fecha_respuesta_proveedor_and_more'),
    ]

    operations = [
        # Eliminar tabla SlotDisponibilidad primero (tiene FK a Disponibilidad)
        migrations.RunSQL(
            "DROP TABLE IF EXISTS ordenes_slotdisponibilidad CASCADE;",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Eliminar tabla Disponibilidad
        migrations.RunSQL(
            "DROP TABLE IF EXISTS ordenes_disponibilidad CASCADE;",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Actualizar campos del CarritoAgendamiento si existen
        migrations.RunSQL(
            """
            ALTER TABLE ordenes_carritoagendamiento 
            DROP COLUMN IF EXISTS fecha_servicio CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        
        migrations.RunSQL(
            """
            ALTER TABLE ordenes_carritoagendamiento 
            DROP COLUMN IF EXISTS hora_servicio CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        
        migrations.RunSQL(
            """
            ALTER TABLE ordenes_carritoagendamiento 
            DROP COLUMN IF EXISTS taller_id CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Agregar nuevos campos al CarritoAgendamiento
        migrations.RunSQL(
            """
            ALTER TABLE ordenes_carritoagendamiento 
            ADD COLUMN IF NOT EXISTS fecha_programada DATE;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        
        migrations.RunSQL(
            """
            ALTER TABLE ordenes_carritoagendamiento 
            ADD COLUMN IF NOT EXISTS hora_programada TIME;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        
        migrations.RunSQL(
            """
            ALTER TABLE ordenes_carritoagendamiento 
            ADD COLUMN IF NOT EXISTS notas TEXT;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Hacer que oferta_servicio en LineaServicio pueda ser nullable temporalmente
        migrations.RunSQL(
            """
            ALTER TABLE ordenes_lineaservicio 
            ALTER COLUMN oferta_servicio_id DROP NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
