# Generated by Django 5.0.13 on 2025-06-05 04:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0017_eliminar_disponibilidad_obsoleta'),
        ('servicios', '0009_repuesto_solicitudrepuesto_serviciorepuesto'),
        ('usuarios', '0011_add_configuracion_semanal_proveedor'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionprecio',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'configuración de precio', 'verbose_name_plural': 'configuraciones de precio'},
        ),
        migrations.AlterUniqueTogether(
            name='carritoagendamiento',
            unique_together={('cliente', 'vehiculo', 'activo')},
        ),
        migrations.RemoveField(
            model_name='configuracionprecio',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='comentario_cancelacion',
        ),
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='devolucion_procesada',
        ),
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='fecha_solicitud_cancelacion',
        ),
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='requiere_devolucion',
        ),
        migrations.AddField(
            model_name='carritoagendamiento',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carritoagendamiento',
            name='hora_programada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carritoagendamiento',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre el carrito', null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='comprobante_pago',
            field=models.ImageField(blank=True, help_text='Comprobante de pago subido por el cliente', null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se procesó la cancelación', null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se validó el comprobante de pago', null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='notas_admin',
            field=models.TextField(blank=True, help_text='Notas internas del administrador', null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='notas_cliente',
            field=models.TextField(blank=True, help_text='Notas adicionales del cliente sobre la solicitud', null=True),
        ),
        migrations.AlterField(
            model_name='carritoagendamiento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='usuarios.cliente'),
        ),
        migrations.AlterField(
            model_name='carritoagendamiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='vehiculos.vehiculo'),
        ),
        migrations.AlterField(
            model_name='configuracionprecio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si esta configuración está activa'),
        ),
        migrations.AlterField(
            model_name='configuracionprecio',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='Porcentaje de IVA a aplicar', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='configuracionprecio',
            name='tarifa_servicio_porcentaje',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Porcentaje de tarifa de servicio a aplicar', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lineaservicio',
            name='con_repuestos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lineaservicio',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lineaservicio',
            name='oferta_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas_servicio', to='servicios.ofertaservicio'),
        ),
        migrations.AlterField(
            model_name='lineaservicio',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='comprobante_validado',
            field=models.BooleanField(default=False, help_text='Indica si el comprobante de pago ha sido validado por un administrador'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pago_validado', 'Pago Validado'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('solicitud_cancelacion', 'Solicitud de Cancelación'), ('pendiente_devolucion', 'Pendiente de Devolución'), ('devuelto', 'Devuelto'), ('pendiente_aceptacion_proveedor', 'Pendiente de Aceptación del Proveedor'), ('aceptada_por_proveedor', 'Aceptada por Proveedor'), ('rechazada_por_proveedor', 'Rechazada por Proveedor')], default='pendiente', max_length=40),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Motivo de la cancelación proporcionado por el cliente', null=True),
        ),
        migrations.RemoveField(
            model_name='carritoagendamiento',
            name='fecha_servicio',
        ),
        migrations.RemoveField(
            model_name='carritoagendamiento',
            name='hora_servicio',
        ),
        migrations.RemoveField(
            model_name='carritoagendamiento',
            name='taller',
        ),
    ]
