# Generated by Django 5.0.13 on 2025-06-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0018_remove_slotdisponibilidad_disponibilidad_and_more'),
    ]

    operations = [
    ]
