# Generated by Django 5.2.1 on 2025-06-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0019_agregar_comprobante_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotdisponibilidad',
            name='disponibilidad',
        ),
        migrations.AlterUniqueTogether(
            name='slotdisponibilidad',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='slotdisponibilidad',
            name='solicitud_servicio',
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='devolucion_procesada',
            field=models.BooleanField(default=False, help_text='Indica si la devolución ha sido procesada'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='requiere_devolucion',
            field=models.BooleanField(default=False, help_text='Indica si la solicitud requiere devolución'),
        ),
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
        migrations.DeleteModel(
            name='SlotDisponibilidad',
        ),
    ]
