# Generated by Django 5.0.13 on 2025-06-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0019_fix_carrito_constraint_sql'),
        ('ordenes', '0020_remove_slotdisponibilidad_disponibilidad_and_more'),
    ]

    operations = [
    ]
