# Generated by Django 5.0.13 on 2025-06-21 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0021_fix_carrito_unique_constraint_final'),
        ('ordenes', '0021_merge_20250620_0556'),
    ]

    operations = [
    ]
