# Generated by Django 5.0.13 on 2025-06-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0022_merge_20250620_2015'),
        ('usuarios', '0011_add_configuracion_semanal_proveedor'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carritoagendamiento',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pago_validado', 'Pago Validado'), ('confirmado', 'Confirmado'), ('pendiente_aceptacion_proveedor', 'Pendiente de Aceptación del Proveedor'), ('aceptada_por_proveedor', 'Aceptada por Proveedor'), ('rechazada_por_proveedor', 'Rechazada por Proveedor'), ('checklist_en_progreso', 'Checklist en Progreso'), ('checklist_completado', 'Checklist Completado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('solicitud_cancelacion', 'Solicitud de Cancelación'), ('pendiente_devolucion', 'Pendiente de Devolución'), ('devuelto', 'Devuelto')], default='pendiente', max_length=40),
        ),
        migrations.AddIndex(
            model_name='carritoagendamiento',
            index=models.Index(fields=['cliente', 'activo'], name='carrito_cliente_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='carritoagendamiento',
            index=models.Index(fields=['vehiculo', 'activo'], name='carrito_vehiculo_activo_idx'),
        ),
    ]
