# Generated by Django 5.0.13 on 2025-06-27 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0023_alter_carritoagendamiento_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAccesoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('tipo_acceso', models.CharField(choices=[('vista_listado', 'Vista de Listado'), ('vista_detalle', 'Vista de Detalle'), ('contacto_directo', 'Contacto Directo'), ('exportacion', 'Exportación de Datos')], max_length=20)),
                ('nivel_informacion', models.CharField(choices=[('parcial', 'Información Parcial'), ('completo', 'Información Completa'), ('restringido', 'Acceso Restringido')], max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('estado_orden_acceso', models.CharField(help_text='Estado de la orden al momento del acceso', max_length=40)),
                ('datos_accedidos', models.JSONField(default=dict, help_text='Lista de campos específicos accedidos')),
                ('justificacion', models.CharField(blank=True, help_text='Justificación automática del acceso', max_length=200, null=True)),
                ('acceso_autorizado', models.BooleanField(default=True, help_text='Si el acceso estaba autorizado según las reglas de negocio')),
                ('requiere_revision', models.BooleanField(default=False, help_text='Si este acceso requiere revisión manual')),
                ('solicitud_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_acceso', to='ordenes.solicitudservicio')),
                ('usuario_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_auditados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Acceso a Cliente',
                'verbose_name_plural': 'Auditorías de Acceso a Clientes',
                'ordering': ['-fecha_acceso'],
                'indexes': [models.Index(fields=['fecha_acceso'], name='ordenes_aud_fecha_a_35fbd8_idx'), models.Index(fields=['usuario_proveedor', 'fecha_acceso'], name='ordenes_aud_usuario_a81460_idx'), models.Index(fields=['solicitud_servicio', 'fecha_acceso'], name='ordenes_aud_solicit_3a292c_idx'), models.Index(fields=['requiere_revision'], name='ordenes_aud_requier_6bdf5d_idx')],
            },
        ),
    ]
