# Generated by Django 5.0.13 on 2025-11-12 19:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0024_add_audit_access_model'),
        ('servicios', '0012_fotoservicio'),
        ('usuarios', '0023_create_tallerdireccion'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleServicioOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_servicio', models.DecimalField(decimal_places=2, help_text='Precio específico de este servicio en la oferta', max_digits=10, verbose_name='Precio')),
                ('tiempo_estimado', models.DurationField(help_text='Tiempo estimado para este servicio específico', verbose_name='Tiempo Estimado')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre este servicio', verbose_name='Notas')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_en_ofertas', to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Servicio en Oferta',
                'verbose_name_plural': 'Detalles de Servicios en Ofertas',
            },
        ),
        migrations.CreateModel(
            name='OfertaProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_proveedor', models.CharField(choices=[('taller', 'Taller'), ('mecanico', 'Mecánico a Domicilio')], max_length=20, verbose_name='Tipo de Proveedor')),
                ('precio_total_ofrecido', models.DecimalField(decimal_places=2, help_text='Precio total de la oferta (suma de todos los servicios)', max_digits=10, verbose_name='Precio Total')),
                ('incluye_repuestos', models.BooleanField(default=False, help_text='Indica si el precio incluye repuestos', verbose_name='Incluye Repuestos')),
                ('tiempo_estimado_total', models.DurationField(help_text='Tiempo total estimado para completar todos los servicios', verbose_name='Tiempo Estimado Total')),
                ('descripcion_oferta', models.TextField(help_text='Descripción detallada de la oferta', verbose_name='Descripción')),
                ('garantia_ofrecida', models.CharField(blank=True, help_text='Garantía ofrecida (ej: "6 meses o 10,000 km")', max_length=200, verbose_name='Garantía')),
                ('fecha_disponible', models.DateField(help_text='Fecha en que el proveedor puede realizar el servicio', verbose_name='Fecha Disponible')),
                ('hora_disponible', models.TimeField(help_text='Hora en que el proveedor puede realizar el servicio', verbose_name='Hora Disponible')),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('vista', 'Vista por Cliente'), ('en_chat', 'En Conversación'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('retirada', 'Retirada por Proveedor'), ('expirada', 'Expirada')], db_index=True, default='enviada', max_length=20, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('fecha_visualizacion_cliente', models.DateTimeField(blank=True, help_text='Momento en que el cliente vio la oferta', null=True, verbose_name='Fecha de Visualización')),
                ('fecha_respuesta_cliente', models.DateTimeField(blank=True, help_text='Momento en que el cliente respondió (aceptó/rechazó)', null=True, verbose_name='Fecha de Respuesta')),
                ('tiempo_respuesta_proveedor', models.DurationField(blank=True, help_text='Tiempo que tardó el proveedor en enviar la oferta desde publicación', null=True, verbose_name='Tiempo de Respuesta del Proveedor')),
                ('proveedor', models.ForeignKey(help_text='Usuario proveedor. Debe tener taller o mecanico_domicilio relacionado.', on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
                ('servicios_ofertados', models.ManyToManyField(related_name='ofertas_que_incluyen', through='ordenes.DetalleServicioOferta', to='servicios.servicio', verbose_name='Servicios Ofertados')),
            ],
            options={
                'verbose_name': 'Oferta de Proveedor',
                'verbose_name_plural': 'Ofertas de Proveedores',
                'ordering': ['precio_total_ofrecido', '-fecha_envio'],
            },
        ),
        migrations.AddField(
            model_name='detalleserviciooferta',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicios', to='ordenes.ofertaproveedor', verbose_name='Oferta'),
        ),
        migrations.CreateModel(
            name='SolicitudServicioPublica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion_problema', models.TextField(help_text='Descripción libre del problema o necesidad del cliente', verbose_name='Descripción del Problema')),
                ('urgencia', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Urgencia')),
                ('tipo_solicitud', models.CharField(choices=[('global', 'Abierta a Todos'), ('dirigida', 'Solo Proveedores Específicos')], default='global', help_text='Global: broadcast a todos. Dirigida: solo proveedores seleccionados', max_length=20, verbose_name='Tipo de Solicitud')),
                ('ubicacion_servicio', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Coordenadas geográficas del servicio', srid=4326, verbose_name='Ubicación del Servicio')),
                ('direccion_servicio_texto', models.CharField(help_text='Dirección en formato texto legible', max_length=500, verbose_name='Dirección del Servicio')),
                ('detalles_ubicacion', models.CharField(blank=True, help_text='Detalles adicionales (ej: Depto 4B, portón verde)', max_length=255, verbose_name='Detalles de Ubicación')),
                ('fecha_preferida', models.DateField(help_text='Fecha preferida por el cliente', verbose_name='Fecha Preferida')),
                ('hora_preferida', models.TimeField(blank=True, help_text='Hora preferida (opcional)', null=True, verbose_name='Hora Preferida')),
                ('estado', models.CharField(choices=[('creada', 'Creada - Pendiente Servicios'), ('seleccionando_servicios', 'Seleccionando Servicios'), ('publicada', 'Publicada - Esperando Ofertas'), ('con_ofertas', 'Con Ofertas Recibidas'), ('adjudicada', 'Adjudicada a Proveedor'), ('expirada', 'Expirada Sin Ofertas'), ('cancelada', 'Cancelada por Cliente')], db_index=True, default='creada', max_length=30, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_publicacion', models.DateTimeField(blank=True, help_text='Momento en que se publicó a proveedores', null=True, verbose_name='Fecha de Publicación')),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha límite para recibir ofertas', verbose_name='Fecha de Expiración')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('total_ofertas', models.IntegerField(default=0, verbose_name='Total de Ofertas Recibidas')),
                ('total_visualizaciones', models.IntegerField(default=0, help_text='Cuántos proveedores vieron esta solicitud', verbose_name='Total de Visualizaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_publicas', to='usuarios.cliente', verbose_name='Cliente')),
                ('direccion_usuario', models.ForeignKey(blank=True, help_text='Dirección registrada del usuario para el servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_en_esta_direccion', to='usuarios.direccionusuario', verbose_name='Dirección del Usuario')),
                ('oferta_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_ganada', to='ordenes.ofertaproveedor', verbose_name='Oferta Seleccionada')),
                ('proveedores_dirigidos', models.ManyToManyField(blank=True, help_text='Proveedores específicos para solicitud dirigida (máx 5). Deben tener taller o mecanico_domicilio relacionado.', related_name='solicitudes_dirigidas_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Proveedores Dirigidos')),
                ('servicios_solicitados', models.ManyToManyField(blank=True, help_text='Servicios específicos seleccionados por el cliente', related_name='solicitudes_publicas', to='servicios.servicio', verbose_name='Servicios Solicitados')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_publicas', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Solicitud Pública de Servicio',
                'verbose_name_plural': 'Solicitudes Públicas de Servicio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='ordenes.solicitudserviciopublica', verbose_name='Solicitud'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleserviciooferta',
            unique_together={('oferta', 'servicio')},
        ),
        migrations.CreateModel(
            name='ChatSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('es_proveedor', models.BooleanField(default=False, help_text='True si el mensaje es del proveedor, False si es del cliente', verbose_name='Es del Proveedor')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Envío')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='chat_solicitudes/%Y/%m/', verbose_name='Archivo Adjunto')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados_solicitudes', to=settings.AUTH_USER_MODEL, verbose_name='Enviado Por')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_chat', to='ordenes.ofertaproveedor', verbose_name='Oferta')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat de Solicitud',
                'verbose_name_plural': 'Mensajes de Chat de Solicitudes',
                'ordering': ['fecha_envio'],
                'indexes': [models.Index(fields=['oferta', 'fecha_envio'], name='ordenes_cha_oferta__eac929_idx'), models.Index(fields=['enviado_por', '-fecha_envio'], name='ordenes_cha_enviado_e7bad0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudserviciopublica',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='ordenes_sol_estado_560b60_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudserviciopublica',
            index=models.Index(fields=['cliente', 'estado'], name='ordenes_sol_cliente_e182f0_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudserviciopublica',
            index=models.Index(fields=['fecha_expiracion'], name='ordenes_sol_fecha_e_cf69ed_idx'),
        ),
        migrations.AddIndex(
            model_name='ofertaproveedor',
            index=models.Index(fields=['solicitud', 'estado'], name='ordenes_ofe_solicit_c58e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='ofertaproveedor',
            index=models.Index(fields=['proveedor', 'estado'], name='ordenes_ofe_proveed_cdb620_idx'),
        ),
        migrations.AddIndex(
            model_name='ofertaproveedor',
            index=models.Index(fields=['precio_total_ofrecido'], name='ordenes_ofe_precio__0c504f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ofertaproveedor',
            unique_together={('solicitud', 'proveedor')},
        ),
    ]
