# Generated by Django 4.2.7 on 2026-07-20 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_omnichannel_fields'),
        ('ordenes', '0025_ensure_cotizacioncanal_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaagendapersonal',
            name='conversation_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_agenda_personal_generadas', to='chat.conversation'),
        ),
    ]
