# Generated by Django 5.0.13 on 2025-11-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0025_sistema_postulaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='estado',
            field=models.CharField(choices=[('enviada', 'Enviada'), ('vista', 'Vista por Cliente'), ('en_chat', 'En Conversación'), ('aceptada', 'Aceptada por Cliente'), ('pendiente_pago', 'Cliente Procesando Pago'), ('pagada', 'Pagada - Servicio Confirmado'), ('rechazada', 'Rechazada'), ('retirada', 'Retirada por Proveedor'), ('expirada', 'Expirada')], db_index=True, default='enviada', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudserviciopublica',
            name='estado',
            field=models.CharField(choices=[('creada', 'Creada - Pendiente Servicios'), ('seleccionando_servicios', 'Seleccionando Servicios'), ('publicada', 'Publicada - Esperando Ofertas'), ('con_ofertas', 'Con Ofertas Recibidas'), ('adjudicada', 'Adjudicada a Proveedor'), ('pendiente_pago', 'Cliente Procesando Pago'), ('pagada', 'Pago Completado'), ('expirada', 'Expirada Sin Ofertas'), ('cancelada', 'Cancelada por Cliente')], db_index=True, default='creada', max_length=30, verbose_name='Estado'),
        ),
    ]
