# Generated by Django 5.0.13 on 2025-11-18 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0026_agregar_estados_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudserviciopublica',
            name='total_rechazos',
            field=models.IntegerField(default=0, help_text='Total de rechazos recibidos de proveedores', verbose_name='Total de Rechazos'),
        ),
        migrations.CreateModel(
            name='RechazoSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_proveedor', models.CharField(choices=[('taller', 'Taller'), ('mecanico', 'Mecánico a Domicilio')], max_length=20, verbose_name='Tipo de Proveedor')),
                ('motivo', models.CharField(choices=[('ocupado', 'No tengo disponibilidad en esas fechas'), ('lejos', 'La ubicación está muy lejos de mi área'), ('no_servicio', 'No realizo ese tipo de servicio'), ('no_marca', 'No trabajo con esa marca de vehículo'), ('precio', 'El precio esperado no es viable'), ('complejidad', 'El trabajo es muy complejo para mi taller'), ('recursos', 'No cuento con las herramientas/repuestos necesarios'), ('politica', 'No cumplo con políticas del cliente'), ('otro', 'Otro motivo')], max_length=20, verbose_name='Motivo del Rechazo')),
                ('detalle_motivo', models.TextField(blank=True, help_text='Explicación adicional del proveedor', max_length=500, verbose_name='Detalle')),
                ('fecha_rechazo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Rechazo')),
                ('tiempo_respuesta', models.DurationField(blank=True, help_text='Tiempo entre publicación y rechazo', null=True, verbose_name='Tiempo de Respuesta')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechazos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechazos', to='ordenes.solicitudserviciopublica', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Rechazo de Solicitud',
                'verbose_name_plural': 'Rechazos de Solicitudes',
                'ordering': ['-fecha_rechazo'],
                'indexes': [models.Index(fields=['solicitud', 'proveedor'], name='ordenes_rec_solicit_7b3424_idx'), models.Index(fields=['motivo'], name='ordenes_rec_motivo_1cd5f2_idx'), models.Index(fields=['fecha_rechazo'], name='ordenes_rec_fecha_r_e75594_idx')],
                'unique_together': {('solicitud', 'proveedor')},
            },
        ),
    ]
