# Generated by Django 5.0.13 on 2025-11-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0027_rechazo_solicitudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleserviciooferta',
            name='repuestos_seleccionados',
            field=models.JSONField(blank=True, default=list, help_text='Lista de repuestos seleccionados para este servicio en formato JSON', verbose_name='Repuestos Seleccionados'),
        ),
    ]
