# Generated by Django 5.0.13 on 2025-11-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0028_agregar_repuestos_detalle_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudserviciopublica',
            name='requiere_repuestos',
            field=models.BooleanField(default=True, help_text='Indica si la solicitud requiere repuestos o solo mano de obra', verbose_name='Requiere Repuestos'),
        ),
    ]
