# Generated by Django 5.0.13 on 2025-11-24 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0029_solicitudserviciopublica_requiere_repuestos'),
        ('servicios', '0012_fotoservicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ofertaproveedor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='es_oferta_secundaria',
            field=models.BooleanField(default=False, help_text='Indica si esta es una oferta secundaria (servicio adicional)', verbose_name='Es Oferta Secundaria'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='motivo_servicio_adicional',
            field=models.TextField(blank=True, help_text='Explicación del proveedor sobre por qué se requiere este servicio adicional', verbose_name='Motivo del Servicio Adicional'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='oferta_original',
            field=models.ForeignKey(blank=True, help_text='Oferta original a la que está asociada esta oferta secundaria', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_secundarias', to='ordenes.ofertaproveedor', verbose_name='Oferta Original'),
        ),
        migrations.AddIndex(
            model_name='ofertaproveedor',
            index=models.Index(fields=['oferta_original', 'es_oferta_secundaria'], name='ordenes_ofe_oferta__a1189b_idx'),
        ),
    ]
