# Generated by Django 5.0.13 on 2025-11-24 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0030_agregar_ofertas_secundarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='oferta_proveedor',
            field=models.ForeignKey(blank=True, help_text='Oferta de proveedor que originó esta solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_servicio', to='ordenes.ofertaproveedor', verbose_name='Oferta Proveedor'),
        ),
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='estado',
            field=models.CharField(choices=[('enviada', 'Enviada'), ('vista', 'Vista por Cliente'), ('en_chat', 'En Conversación'), ('aceptada', 'Aceptada por Cliente'), ('pendiente_pago', 'Cliente Procesando Pago'), ('pagada', 'Pagada - Listo para Iniciar'), ('en_ejecucion', 'En Ejecución - Servicio en Progreso'), ('completada', 'Completada - Servicio Finalizado'), ('rechazada', 'Rechazada'), ('retirada', 'Retirada por Proveedor'), ('expirada', 'Expirada')], db_index=True, default='enviada', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudserviciopublica',
            name='estado',
            field=models.CharField(choices=[('creada', 'Creada - Pendiente Servicios'), ('seleccionando_servicios', 'Seleccionando Servicios'), ('publicada', 'Publicada - Esperando Ofertas'), ('con_ofertas', 'Con Ofertas Recibidas'), ('adjudicada', 'Adjudicada a Proveedor'), ('pendiente_pago', 'Cliente Procesando Pago'), ('pagada', 'Pago Completado - Listo para Iniciar'), ('en_ejecucion', 'Servicio en Progreso'), ('completada', 'Servicio Finalizado'), ('expirada', 'Expirada Sin Ofertas'), ('cancelada', 'Cancelada por Cliente')], db_index=True, default='creada', max_length=30, verbose_name='Estado'),
        ),
    ]
