# Generated by Django 5.0.13 on 2025-12-09 02:54

from django.db import migrations, models
from django.utils import timezone
from datetime import datetime


def calcular_fecha_limite_pago_existentes(apps, schema_editor):
    """
    Calcula fecha_limite_pago para solicitudes adjudicadas existentes
    basándose en la fecha_disponible de la oferta seleccionada.
    """
    SolicitudServicioPublica = apps.get_model('ordenes', 'SolicitudServicioPublica')
    
    solicitudes_adjudicadas = SolicitudServicioPublica.objects.filter(
        estado='adjudicada',
        oferta_seleccionada__isnull=False
    ).select_related('oferta_seleccionada')
    
    for solicitud in solicitudes_adjudicadas:
        if solicitud.oferta_seleccionada and solicitud.oferta_seleccionada.fecha_disponible:
            # Combinar fecha y hora de la oferta para crear datetime
            fecha_disponible = solicitud.oferta_seleccionada.fecha_disponible
            hora_disponible = solicitud.oferta_seleccionada.hora_disponible or timezone.now().time()
            fecha_limite = timezone.make_aware(
                datetime.combine(fecha_disponible, hora_disponible)
            )
            solicitud.fecha_limite_pago = fecha_limite
            solicitud.save(update_fields=['fecha_limite_pago'])


def reverse_calcular_fecha_limite_pago(apps, schema_editor):
    """No hay nada que revertir"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0031_agregar_estados_servicio_y_oferta_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudserviciopublica',
            name='fecha_limite_pago',
            field=models.DateTimeField(blank=True, help_text='Fecha límite para pagar después de adjudicar (fecha del servicio)', null=True, verbose_name='Fecha Límite de Pago'),
        ),
        migrations.RunPython(
            calcular_fecha_limite_pago_existentes,
            reverse_calcular_fecha_limite_pago
        ),
    ]
