# Generated by Django 5.0.13 on 2025-12-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0032_add_fecha_limite_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaproveedor',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de mano de obra del servicio (sin IVA)', max_digits=10, verbose_name='Costo Mano de Obra'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='costo_repuestos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total de los repuestos cotizados (sin IVA)', max_digits=10, verbose_name='Costo Repuestos'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='estado_pago_repuestos',
            field=models.CharField(choices=[('no_aplica', 'No Aplica (Sin Repuestos o Todo Adelantado)'), ('pendiente', 'Pendiente de Pago'), ('pagado', 'Repuestos Pagados')], default='no_aplica', help_text='Estado del pago de repuestos', max_length=20, verbose_name='Estado Pago Repuestos'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='estado_pago_servicio',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Servicio Pagado')], default='pendiente', help_text='Estado del pago del servicio/mano de obra', max_length=20, verbose_name='Estado Pago Servicio'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='foto_cotizacion_repuestos',
            field=models.URLField(blank=True, help_text='URL de la foto de la cotización de repuestos de la casa de repuestos', max_length=500, null=True, verbose_name='Foto Cotización Repuestos'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='metodo_pago_cliente',
            field=models.CharField(choices=[('repuestos_adelantado', 'Repuestos Adelantado + Servicio al Final'), ('todo_adelantado', 'Todo Adelantado'), ('pendiente', 'Pendiente de Selección')], default='pendiente', help_text='Método de pago elegido por el cliente para esta oferta', max_length=25, verbose_name='Método de Pago Cliente'),
        ),
    ]
