# Generated by Django 5.0.13 on 2025-12-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0033_add_desglose_repuestos_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaproveedor',
            name='costo_gestion_compra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de gestión y traslado para compra de repuestos (sin IVA). Aplica solo cuando incluye_repuestos=True', max_digits=10, verbose_name='Costo Gestión de Compra'),
        ),
    ]
