# Generated by Django 5.0.13 on 2026-01-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0034_add_costo_gestion_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaproveedor',
            name='estado',
            field=models.CharField(choices=[('enviada', 'Enviada'), ('vista', 'Vista por Cliente'), ('en_chat', 'En Conversación'), ('aceptada', 'Aceptada por Cliente'), ('pendiente_pago', 'Cliente Procesando Pago'), ('pagada_parcialmente', 'Pagada Parcialmente - Pendiente Saldo'), ('pagada', 'Pagada - Listo para Iniciar'), ('en_ejecucion', 'En Ejecución - Servicio en Progreso'), ('completada', 'Completada - Servicio Finalizado'), ('rechazada', 'Rechazada'), ('retirada', 'Retirada por Proveedor'), ('expirada', 'Expirada')], db_index=True, default='enviada', max_length=20, verbose_name='Estado'),
        ),
    ]
