# Generated by Django 5.0.13 on 2026-01-06 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0035_agregar_estado_pagada_parcialmente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaDescartada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('pago_proximo', 'Pago Próximo'), ('pago_expirado', 'Pago Expirado')], max_length=20, verbose_name='Tipo de Alerta')),
                ('fecha_descarte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Descarte')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_descartadas', to='ordenes.solicitudserviciopublica', verbose_name='Solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_descartadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Alerta Descartada',
                'verbose_name_plural': 'Alertas Descartadas',
                'ordering': ['-fecha_descarte'],
                'indexes': [models.Index(fields=['usuario', 'solicitud', 'tipo_alerta'], name='ordenes_ale_usuario_4522fb_idx'), models.Index(fields=['fecha_descarte'], name='ordenes_ale_fecha_d_163607_idx')],
                'unique_together': {('usuario', 'solicitud', 'tipo_alerta')},
            },
        ),
    ]
