# Generated by Django 4.2.7 on 2026-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0041_preciorepuestoweb_especificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaEspecialistaMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(db_index=True, help_text='Marca del vehículo, normalizada.', max_length=80)),
                ('dominio', models.CharField(max_length=200)),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('aciertos', models.PositiveIntegerField(default=0, help_text='Fichas que nombraron el modelo consultado.')),
                ('apariciones', models.PositiveIntegerField(default=0)),
                ('ultimo_acierto', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tienda especialista por marca',
                'verbose_name_plural': 'tiendas especialistas por marca',
            },
        ),
        migrations.RenameIndex(
            model_name='precioproveedortaller',
            new_name='ordenes_pre_taller__526993_idx',
            old_name='ordenes_pre_taller__2f4a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='precioproveedortaller',
            new_name='ordenes_pre_taller__c0179c_idx',
            old_name='ordenes_pre_taller__9c8e21_idx',
        ),
        migrations.AlterField(
            model_name='cotizacioncanal',
            name='fecha_expiracion_publica',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Vencimiento del enlace público de cotización libre.', null=True),
        ),
        migrations.AlterField(
            model_name='preciorepuestoweb',
            name='clave',
            field=models.CharField(db_index=True, help_text='Clave normalizada nombre+spec+marca+modelo+anio+motor+cilindrada.', max_length=240),
        ),
        migrations.AddIndex(
            model_name='tiendaespecialistamarca',
            index=models.Index(fields=['marca', '-aciertos'], name='ordenes_tem_marca_acierto_idx'),
        ),
        migrations.AddConstraint(
            model_name='tiendaespecialistamarca',
            constraint=models.UniqueConstraint(fields=('marca', 'dominio'), name='ordenes_tiendaespmarca_marca_dominio_uniq'),
        ),
    ]
