# Generated by Django 5.0.13 on 2026-01-12 16:41

import django.core.validators
import mecanimovilapp.apps.personalizacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración de personalización',
                'verbose_name_plural': 'configuraciones de personalización',
            },
        ),
        migrations.CreateModel(
            name='PerfilVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicios_realizados', models.PositiveIntegerField(default=0)),
                ('gasto_promedio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frecuencia_mantenimiento', models.PositiveIntegerField(default=0, help_text='Días promedio entre servicios')),
                ('categorias_frecuentes', models.JSONField(default=dict, help_text='Categorías de servicios más utilizadas con frecuencias')),
                ('talleres_frecuentes', models.JSONField(default=list, help_text='IDs de talleres más utilizados')),
                ('mecanicos_frecuentes', models.JSONField(default=list, help_text='IDs de mecánicos más utilizados')),
                ('km_ultimo_servicio', models.PositiveIntegerField(default=0)),
                ('dias_ultimo_servicio', models.PositiveIntegerField(default=0)),
                ('score_mantenimiento_urgente', models.FloatField(default=0.0, help_text='Score de urgencia de mantenimiento (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'perfil de vehículo',
                'verbose_name_plural': 'perfiles de vehículos',
            },
        ),
        migrations.CreateModel(
            name='RecomendacionPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mantenimiento', 'Mantenimiento Sugerido'), ('proveedor', 'Proveedor Recomendado'), ('servicio_popular', 'Servicio Popular')], max_length=20)),
                ('score_relevancia', models.FloatField(help_text='Score de relevancia de la recomendación (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('razon_recomendacion', models.TextField(help_text='Explicación de por qué se recomienda')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(default=mecanimovilapp.apps.personalizacion.models.get_default_expiration_date)),
                ('activa', models.BooleanField(default=True)),
                ('veces_mostrada', models.PositiveIntegerField(default=0)),
                ('veces_clickeada', models.PositiveIntegerField(default=0)),
                ('convertida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'recomendación personalizada',
                'verbose_name_plural': 'recomendaciones personalizadas',
                'ordering': ['-score_relevancia', '-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='VehiculoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seleccion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vehículo activo',
                'verbose_name_plural': 'vehículos activos',
            },
        ),
    ]
