# Generated by Django 5.0.13 on 2025-05-26 03:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0008_remove_servicio_marcas_compatibles_and_more'),
        ('usuarios', '0004_merge_20250516_2326'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración de personalización',
                'verbose_name_plural': 'configuraciones de personalización',
            },
        ),
        migrations.CreateModel(
            name='PerfilVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicios_realizados', models.PositiveIntegerField(default=0)),
                ('gasto_promedio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frecuencia_mantenimiento', models.PositiveIntegerField(default=0, help_text='Días promedio entre servicios')),
                ('categorias_frecuentes', models.JSONField(default=dict, help_text='Categorías de servicios más utilizadas con frecuencias')),
                ('talleres_frecuentes', models.JSONField(default=list, help_text='IDs de talleres más utilizados')),
                ('mecanicos_frecuentes', models.JSONField(default=list, help_text='IDs de mecánicos más utilizados')),
                ('km_ultimo_servicio', models.PositiveIntegerField(default=0)),
                ('dias_ultimo_servicio', models.PositiveIntegerField(default=0)),
                ('score_mantenimiento_urgente', models.FloatField(default=0.0, help_text='Score de urgencia de mantenimiento (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_analitico', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'perfil de vehículo',
                'verbose_name_plural': 'perfiles de vehículos',
            },
        ),
        migrations.CreateModel(
            name='RecomendacionPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mantenimiento', 'Mantenimiento Sugerido'), ('proveedor', 'Proveedor Recomendado'), ('servicio_popular', 'Servicio Popular')], max_length=20)),
                ('score_relevancia', models.FloatField(help_text='Score de relevancia de la recomendación (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('razon_recomendacion', models.TextField(help_text='Explicación de por qué se recomienda')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('veces_mostrada', models.PositiveIntegerField(default=0)),
                ('veces_clickeada', models.PositiveIntegerField(default=0)),
                ('convertida', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='usuarios.cliente')),
                ('oferta_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.ofertaservicio')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'recomendación personalizada',
                'verbose_name_plural': 'recomendaciones personalizadas',
                'ordering': ['-score_relevancia', '-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='VehiculoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seleccion', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_activo', to='usuarios.cliente', verbose_name='cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activo_para_clientes', to='vehiculos.vehiculo', verbose_name='vehículo activo')),
            ],
            options={
                'verbose_name': 'vehículo activo',
                'verbose_name_plural': 'vehículos activos',
            },
        ),
    ]
