# Generated by Django 5.0.13 on 2025-05-26 04:29

import mecanimovilapp.apps.personalizacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacionpersonalizada',
            name='fecha_expiracion',
            field=models.DateTimeField(default=mecanimovilapp.apps.personalizacion.models.get_default_expiration_date),
        ),
    ]
