# Generated by Django 5.0.13 on 2026-01-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personalizacion', '0001_initial'),
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilvehiculo',
            name='vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_analitico', to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='recomendacionpersonalizada',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='recomendacionpersonalizada',
            name='oferta_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.ofertaservicio'),
        ),
        migrations.AddField(
            model_name='recomendacionpersonalizada',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='recomendacionpersonalizada',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='vehiculoactivo',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_activo', to='usuarios.cliente', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='vehiculoactivo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activo_para_clientes', to='vehiculos.vehiculo', verbose_name='vehículo activo'),
        ),
    ]
