# Generated by Django 5.0.13 on 2026-01-12 16:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0003_initial'),
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo de la marca', null=True, upload_to='marcas/')),
            ],
            options={
                'verbose_name': 'marca de vehículo',
                'verbose_name_plural': 'marcas de vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteSaludConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_medicion', models.CharField(choices=[('KILOMETRAJE', 'Por Kilometraje'), ('TIEMPO', 'Por Tiempo (meses)'), ('MIXTO', 'Kilometraje y Tiempo')], default='KILOMETRAJE', max_length=20)),
                ('beta', models.FloatField(default=2.0, help_text='Factor de forma (1.0-4.0). Mayor = degradación más abrupta', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('eta', models.FloatField(default=20000, help_text='Parámetro de escala (vida característica en km o meses)', validators=[django.core.validators.MinValueValidator(100)])),
                ('km_critico', models.PositiveIntegerField(blank=True, help_text='Kilometraje crítico para reemplazo', null=True)),
                ('meses_critico', models.PositiveIntegerField(blank=True, help_text='Meses críticos para reemplazo', null=True)),
                ('factor_edad_vehiculo', models.FloatField(default=0.05, help_text='Degradación adicional por año del vehículo (0.05 = 5%/año)')),
                ('factor_uso_intensivo', models.FloatField(default=1.2, help_text='Multiplicador para uso intensivo')),
                ('activo', models.BooleanField(default=True)),
                ('orden_visualizacion', models.PositiveIntegerField(default=0)),
                ('icono', models.CharField(default='construct-outline', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('servicio_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes_salud', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Componente de Salud',
                'verbose_name_plural': 'Componentes de Salud',
                'ordering': ['orden_visualizacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vehiculos.marcavehiculo',),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='vehiculos.marcavehiculo')),
            ],
            options={
                'verbose_name': 'modelo',
                'verbose_name_plural': 'modelos',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'marca')},
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cilindraje', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_motor', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diésel', 'Diésel'), ('Eléctrico', 'Eléctrico'), ('Híbrido', 'Híbrido')], default='Gasolina', max_length=20)),
                ('year', models.IntegerField(default=2024, verbose_name='año')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='usuarios.cliente')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='vehiculos.marcavehiculo')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='vehiculos.modelo')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteSaludVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salud_porcentaje', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nivel_alerta', models.CharField(choices=[('OPTIMO', 'Óptimo'), ('ATENCION', 'Atención'), ('URGENTE', 'Urgente'), ('CRITICO', 'Crítico')], max_length=20)),
                ('km_ultimo_servicio', models.PositiveIntegerField(default=0)),
                ('fecha_ultimo_servicio', models.DateTimeField(blank=True, null=True)),
                ('km_estimados_restantes', models.PositiveIntegerField(default=0)),
                ('dias_estimados_restantes', models.PositiveIntegerField(default=0)),
                ('fecha_estimada_servicio', models.DateField(blank=True, null=True)),
                ('requiere_servicio_inmediato', models.BooleanField(default=False)),
                ('mensaje_alerta', models.TextField(blank=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_automaticamente', models.BooleanField(default=True)),
                ('checklist_ultimo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes_actualizados', to='checklists.checklistinstance')),
                ('componente_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.componentesaludconfig')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_salud', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Componente de Salud de Vehículo',
                'verbose_name_plural': 'Componentes de Salud de Vehículos',
                'ordering': ['componente_config__orden_visualizacion'],
            },
        ),
        migrations.CreateModel(
            name='AlertaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('MANTENCION_PREVENTIVA', 'Mantención Preventiva'), ('COMPONENTE_CRITICO', 'Componente Crítico'), ('MANTENCION_POR_KM', 'Mantención por Kilometraje'), ('MANTENCION_POR_TIEMPO', 'Mantención por Tiempo')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.PositiveIntegerField(default=3, help_text='1=Baja, 5=Crítica', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('vista_por_usuario', models.BooleanField(default=False)),
                ('fecha_vista', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('servicios_recomendados', models.ManyToManyField(related_name='alertas_mantenimiento', to='servicios.servicio')),
                ('componente_salud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='vehiculos.componentesaludvehiculo')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_mantenimiento', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Alerta de Mantenimiento',
                'verbose_name_plural': 'Alertas de Mantenimiento',
                'ordering': ['-prioridad', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadoSaludVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salud_general_porcentaje', models.FloatField(help_text='Promedio ponderado de salud de todos los componentes', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kilometraje_snapshot', models.PositiveIntegerField()),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('total_componentes_evaluados', models.PositiveIntegerField(default=0)),
                ('componentes_optimos', models.PositiveIntegerField(default=0)),
                ('componentes_atencion', models.PositiveIntegerField(default=0)),
                ('componentes_urgentes', models.PositiveIntegerField(default=0)),
                ('componentes_criticos', models.PositiveIntegerField(default=0)),
                ('tiene_alertas_activas', models.BooleanField(default=False)),
                ('costo_estimado_mantenimiento', models.DecimalField(decimal_places=2, default=0, help_text='Suma de servicios recomendados', max_digits=10)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_salud', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Estado de Salud de Vehículo',
                'verbose_name_plural': 'Estados de Salud de Vehículos',
                'ordering': ['-fecha_calculo'],
                'indexes': [models.Index(fields=['vehiculo', '-fecha_calculo'], name='vehiculos_e_vehicul_12d462_idx'), models.Index(fields=['tiene_alertas_activas', '-fecha_calculo'], name='vehiculos_e_tiene_a_a4016e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='componentesaludvehiculo',
            index=models.Index(fields=['vehiculo', 'nivel_alerta'], name='vehiculos_c_vehicul_d39f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='componentesaludvehiculo',
            index=models.Index(fields=['requiere_servicio_inmediato', '-salud_porcentaje'], name='vehiculos_c_requier_edfe63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='componentesaludvehiculo',
            unique_together={('vehiculo', 'componente_config')},
        ),
    ]
