# Generated by Django 4.2.7 on 2026-01-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentesaludconfig',
            name='tipo_motor_aplicable',
            field=models.CharField(choices=[('TODOS', 'Todos los motores'), ('GASOLINA', 'Solo Gasolina'), ('DIESEL', 'Solo Diésel')], default='TODOS', help_text='Tipo de motor al que aplica este componente', max_length=20),
        ),
        migrations.AlterField(
            model_name='componentesaludconfig',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_motor',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diésel', 'Diésel')], default='Gasolina', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='componentesaludconfig',
            unique_together={('nombre', 'tipo_motor_aplicable')},
        ),
    ]
