# Generated by Django 4.2.7 on 2026-01-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_add_tipo_motor_to_componentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_motor',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('GASOLINA', 'GASOLINA'), ('BENCINA', 'BENCINA'), ('Diésel', 'Diésel'), ('DIESEL', 'DIESEL'), ('Electric', 'Electric')], default='Gasolina', max_length=20),
        ),
    ]
