# Generated by Django 4.2.7 on 2026-01-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_alter_vehiculo_foto_alter_vehiculo_tipo_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_ultima_tasacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='permiso_circulacion',
            field=models.IntegerField(default=0, help_text='Valor permiso circulación'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='precio_mercado_max',
            field=models.IntegerField(default=0, help_text='Precio mercado máximo (GetAPI)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='precio_mercado_min',
            field=models.IntegerField(default=0, help_text='Precio mercado mínimo (GetAPI)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='precio_mercado_promedio',
            field=models.IntegerField(default=0, help_text='Precio referencia usado'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='precio_retoma',
            field=models.IntegerField(default=0, help_text='Precio sugerido de retoma'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='precio_sugerido_final',
            field=models.IntegerField(default=0, help_text='Precio calculado por nuestro algoritmo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tasacion_fiscal',
            field=models.IntegerField(default=0, help_text='Tasación fiscal del SII'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='year_tasacion_fiscal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
