# Generated by Django 4.2.7 on 2026-01-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculo_fecha_ultima_tasacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0, verbose_name='favoritos'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publicado'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='leads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='interesados'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='precio_venta',
            field=models.IntegerField(blank=True, null=True, verbose_name='precio de venta'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='vistas'),
        ),
    ]
