# Generated by Django 4.2.7 on 2026-01-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_vehiculo_favorites_count_vehiculo_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='transmisión'),
        ),
    ]
