# Generated by Django 4.2.7 on 2026-01-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_vehiculo_color_vehiculo_transmision'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='mes_revision_tecnica',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='mes revisión técnica'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_motor',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='número de motor'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='puertas',
            field=models.IntegerField(blank=True, null=True, verbose_name='puertas'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='versión'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='VIN'),
        ),
    ]
