# Generated by Django 5.2.1 on 2026-01-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_vehiculo_mes_revision_tecnica_vehiculo_numero_motor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje_api',
            field=models.IntegerField(blank=True, help_text='Kilometraje obtenido de API externa', null=True),
        ),
    ]
