# Generated by Django 5.2.1 on 2026-01-29 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_attachment_alter_message_content'),
        ('vehiculos', '0009_ofertavehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertavehiculo',
            name='conversacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oferta_vehiculo', to='chat.conversation'),
        ),
    ]
