# Generated by Django 5.2.1 on 2026-01-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0010_ofertavehiculo_conversacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertavehiculo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('contraoferta', 'Contraoferta'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
    ]
