# Generated by Django 5.2.1 on 2026-01-30 07:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0011_alter_ofertavehiculo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Identificador para iconos y frontend (ej: oil, brakes)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_critico', models.BooleanField(default=False, help_text='Si falla, ¿es crítico para el funcionamiento?')),
                ('icono', models.CharField(default='construct-outline', max_length=50)),
                ('orden_visualizacion', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Componente de Salud (Maestro)',
                'verbose_name_plural': 'Componentes de Salud (Maestro)',
                'ordering': ['orden_visualizacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReglaMantenimientoEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Debe coincidir EXACTAMENTE con vehiculo.marca', max_length=100)),
                ('modelo', models.CharField(help_text='Debe coincidir EXACTAMENTE con vehiculo.modelo', max_length=100)),
                ('vida_util_km', models.PositiveIntegerField(help_text='Vida útil específica en Kilómetros')),
                ('beta', models.FloatField(default=2.0, help_text='Factor de forma Weibull')),
            ],
            options={
                'verbose_name': 'Regla Mantenimiento Específica',
                'verbose_name_plural': 'Reglas Mantenimiento Específicas',
            },
        ),
        migrations.CreateModel(
            name='ReglaMantenimientoGenerica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_motor', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diésel'), ('ELECTRICO', 'Eléctrico'), ('HIBRIDO', 'Híbrido')], max_length=20)),
                ('vida_util_km', models.PositiveIntegerField(help_text='Vida útil estimada en Kilómetros (ETA)')),
                ('beta', models.FloatField(default=2.0, help_text='Factor de forma Weibull (2.0 = desgaste lineal/normal)')),
                ('meses_critico', models.PositiveIntegerField(blank=True, help_text='Límite en meses (opcional)', null=True)),
            ],
            options={
                'verbose_name': 'Regla Mantenimiento Genérica',
                'verbose_name_plural': 'Reglas Mantenimiento Genéricas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='componentesaludconfig',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='componentesaludconfig',
            name='servicio_asociado',
        ),
        migrations.AlterModelOptions(
            name='alertamantenimiento',
            options={'verbose_name': 'Alerta de Mantenimiento', 'verbose_name_plural': 'Alertas de Mantenimiento'},
        ),
        migrations.AlterModelOptions(
            name='componentesaludvehiculo',
            options={'ordering': ['componente__orden_visualizacion'], 'verbose_name': 'Componente de Salud de Vehículo', 'verbose_name_plural': 'Componentes de Salud de Vehículos'},
        ),
        migrations.RemoveIndex(
            model_name='componentesaludvehiculo',
            name='vehiculos_c_vehicul_d39f7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='componentesaludvehiculo',
            name='vehiculos_c_requier_edfe63_idx',
        ),
        migrations.RemoveIndex(
            model_name='estadosaludvehiculo',
            name='vehiculos_e_vehicul_12d462_idx',
        ),
        migrations.RemoveIndex(
            model_name='estadosaludvehiculo',
            name='vehiculos_e_tiene_a_a4016e_idx',
        ),
        migrations.RemoveField(
            model_name='alertamantenimiento',
            name='fecha_resolucion',
        ),
        migrations.RemoveField(
            model_name='alertamantenimiento',
            name='fecha_vista',
        ),
        migrations.RemoveField(
            model_name='alertamantenimiento',
            name='vista_por_usuario',
        ),
        migrations.AddField(
            model_name='componentesaludvehiculo',
            name='es_regla_especifica',
            field=models.BooleanField(default=False, help_text='¿Se usó una regla específica?'),
        ),
        migrations.AddField(
            model_name='componentesaludvehiculo',
            name='vida_util_proyectada',
            field=models.PositiveIntegerField(default=0, help_text='Vida util (eta) usada para el cálculo'),
        ),
        migrations.AlterField(
            model_name='alertamantenimiento',
            name='prioridad',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='alertamantenimiento',
            name='tipo_alerta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estadosaludvehiculo',
            name='costo_estimado_mantenimiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='estadosaludvehiculo',
            name='salud_general_porcentaje',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='componentesaludvehiculo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='componentesaludvehiculo',
            name='componente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.componentesalud'),
        ),
        migrations.AlterUniqueTogether(
            name='componentesaludvehiculo',
            unique_together={('vehiculo', 'componente')},
        ),
        migrations.AddField(
            model_name='reglamantenimientoespecifica',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_especificas', to='vehiculos.componentesalud'),
        ),
        migrations.AddField(
            model_name='reglamantenimientogenerica',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_genericas', to='vehiculos.componentesalud'),
        ),
        migrations.RemoveField(
            model_name='componentesaludvehiculo',
            name='actualizado_automaticamente',
        ),
        migrations.RemoveField(
            model_name='componentesaludvehiculo',
            name='checklist_ultimo_servicio',
        ),
        migrations.RemoveField(
            model_name='componentesaludvehiculo',
            name='componente_config',
        ),
        migrations.RemoveField(
            model_name='componentesaludvehiculo',
            name='dias_estimados_restantes',
        ),
        migrations.RemoveField(
            model_name='componentesaludvehiculo',
            name='fecha_estimada_servicio',
        ),
        migrations.AlterUniqueTogether(
            name='reglamantenimientoespecifica',
            unique_together={('marca', 'modelo', 'componente')},
        ),
        migrations.AlterUniqueTogether(
            name='reglamantenimientogenerica',
            unique_together={('componente', 'tipo_motor')},
        ),
        migrations.DeleteModel(
            name='ComponenteSaludConfig',
        ),
    ]
