# Generated by Django 5.0.13 on 2026-01-12 16:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'detalle de servicio',
                'verbose_name_plural': 'detalles de servicios',
            },
        ),
        migrations.CreateModel(
            name='FotoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Foto del servicio subida por el proveedor', upload_to='servicios_photos/')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional de la foto', max_length=255, null=True)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de esta foto dentro del servicio')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de Servicio',
                'verbose_name_plural': 'Fotos de Servicios',
                'ordering': ['oferta_servicio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='OfertaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proveedor', models.CharField(choices=[('taller', 'Taller'), ('mecanico', 'Mecánico a Domicilio')], max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('duracion_estimada', models.TimeField(blank=True, null=True)),
                ('precio_con_repuestos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')])),
                ('precio_sin_repuestos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')])),
                ('incluye_garantia', models.BooleanField(default=True)),
                ('duracion_garantia', models.PositiveIntegerField(default=30, help_text='Duración de la garantía en días')),
                ('detalles_adicionales', models.TextField(blank=True, null=True)),
                ('tipo_servicio', models.CharField(choices=[('con_repuestos', 'Servicio con repuestos'), ('sin_repuestos', 'Servicio sin repuestos')], default='con_repuestos', help_text='Tipo de servicio ofrecido', max_length=20)),
                ('repuestos_seleccionados', models.JSONField(blank=True, default=list, help_text='Lista de repuestos específicos seleccionados para este servicio')),
                ('costo_mano_de_obra_sin_iva', models.DecimalField(decimal_places=2, default=0, help_text='Costo de mano de obra sin incluir IVA', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_repuestos_sin_iva', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de repuestos sin incluir IVA', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fotos_urls', models.JSONField(blank=True, default=list, help_text='URLs de fotos asociadas al servicio')),
                ('precio_publicado_cliente', models.DecimalField(decimal_places=2, default=0, help_text='Precio final que verá el cliente (con IVA)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('comision_mecanmovil', models.DecimalField(decimal_places=2, default=0, help_text='Comisión del 20% para la plataforma', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('iva_sobre_comision', models.DecimalField(decimal_places=2, default=0, help_text='IVA del 19% sobre la comisión', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ganancia_neta_proveedor', models.DecimalField(decimal_places=2, default=0, help_text='Ganancia final del proveedor después de comisión', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'oferta de servicio',
                'verbose_name_plural': 'ofertas de servicios',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_referencia', models.DecimalField(decimal_places=2, default=0, help_text='Precio de referencia del repuesto', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='repuestos/')),
                ('categoria_repuesto', models.CharField(choices=[('filtros', 'Filtros'), ('aceites', 'Aceites y Lubricantes'), ('frenos', 'Sistema de Frenos'), ('motor', 'Motor'), ('transmision', 'Transmisión'), ('suspension', 'Suspensión'), ('electrico', 'Sistema Eléctrico'), ('carroceria', 'Carrocería'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'repuesto',
                'verbose_name_plural': 'repuestos',
                'ordering': ['categoria_repuesto', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_estimada_base', models.DurationField(blank=True, help_text='Tiempo base estimado para realizar el servicio', null=True)),
                ('calificacion_promedio', models.FloatField(default=0.0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('requiere_repuestos', models.BooleanField(default=True, help_text='Indica si el servicio normalmente requiere repuestos')),
                ('precio_referencia', models.DecimalField(decimal_places=2, default=0, help_text='Precio de referencia general', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='ServicioRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_estimada', models.PositiveIntegerField(default=1, help_text='Cantidad estimada de este repuesto para el servicio')),
                ('es_opcional', models.BooleanField(default=False, help_text='Indica si el repuesto es opcional para el servicio')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el uso de este repuesto', null=True)),
            ],
            options={
                'verbose_name': 'repuesto de servicio',
                'verbose_name_plural': 'repuestos de servicios',
            },
        ),
        migrations.CreateModel(
            name='SolicitudRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario del repuesto en esta solicitud', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_total', models.DecimalField(decimal_places=2, help_text='Precio total de este repuesto (cantidad * precio_unitario)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('incluido_en_garantia', models.BooleanField(default=True, help_text='Indica si este repuesto está cubierto por la garantía')),
            ],
            options={
                'verbose_name': 'repuesto de solicitud',
                'verbose_name_plural': 'repuestos de solicitud',
            },
        ),
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la categoría', null=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre del ícono para representar la categoría', max_length=50, null=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición de la categoría')),
                ('categoria_padre', models.ForeignKey(blank=True, help_text='Categoría principal a la que pertenece esta subcategoría', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='servicios.categoriaservicio', verbose_name='categoría padre')),
            ],
            options={
                'verbose_name': 'categoría de servicio',
                'verbose_name_plural': 'categorías de servicios',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
