# Generated by Django 5.0.13 on 2025-05-16 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'categoría de servicio',
                'verbose_name_plural': 'categorías de servicios',
            },
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'detalle de servicio',
                'verbose_name_plural': 'detalles de servicios',
            },
        ),
        migrations.CreateModel(
            name='PrecioServicioMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_con_repuestos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_sin_repuestos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'precio de servicio (mecánico)',
                'verbose_name_plural': 'precios de servicios (mecánicos)',
            },
        ),
        migrations.CreateModel(
            name='PrecioServicioTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_con_repuestos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_sin_repuestos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'precio de servicio (taller)',
                'verbose_name_plural': 'precios de servicios (talleres)',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_estimada', models.TimeField(blank=True, null=True)),
                ('calificacion_promedio', models.FloatField(default=0.0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='servicios/')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='ServicioAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'servicio asociado',
                'verbose_name_plural': 'servicios asociados',
            },
        ),
        migrations.CreateModel(
            name='ServicioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'categoría de servicio',
                'verbose_name_plural': 'categorías de servicios',
            },
        ),
        migrations.CreateModel(
            name='ServicioMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'compatibilidad con marca',
                'verbose_name_plural': 'compatibilidades con marcas',
            },
        ),
        migrations.CreateModel(
            name='ServicioMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'servicio de mecánico',
                'verbose_name_plural': 'servicios de mecánicos',
            },
        ),
        migrations.CreateModel(
            name='ServicioTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'servicio de taller',
                'verbose_name_plural': 'servicios de talleres',
            },
        ),
    ]
