# Generated by Django 5.0.13 on 2025-05-16 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precioserviciomecanico',
            name='mecanico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_servicios', to='usuarios.mecanicodomicilio'),
        ),
        migrations.AddField(
            model_name='precioserviciotaller',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_servicios', to='usuarios.taller'),
        ),
        migrations.AddField(
            model_name='precioserviciotaller',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_talleres', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='precioserviciomecanico',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_mecanicos', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='detalleservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='servicioasociado',
            name='servicio_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asociado_a', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='servicioasociado',
            name='servicio_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_asociados', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='servicios_relacionados',
            field=models.ManyToManyField(related_name='servicios_que_me_relacionan', through='servicios.ServicioAsociado', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='serviciocategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.categoriaservicio'),
        ),
        migrations.AddField(
            model_name='serviciocategoria',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='categorias',
            field=models.ManyToManyField(related_name='servicios', through='servicios.ServicioCategoria', to='servicios.categoriaservicio'),
        ),
        migrations.AddField(
            model_name='serviciomarca',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.marca'),
        ),
        migrations.AddField(
            model_name='serviciomarca',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='marcas_compatibles',
            field=models.ManyToManyField(related_name='servicios_compatibles', through='servicios.ServicioMarca', to='vehiculos.marca'),
        ),
        migrations.AddField(
            model_name='serviciomecanico',
            name='mecanico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.mecanicodomicilio'),
        ),
        migrations.AddField(
            model_name='serviciomecanico',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='mecanicos',
            field=models.ManyToManyField(related_name='servicios', through='servicios.ServicioMecanico', to='usuarios.mecanicodomicilio'),
        ),
        migrations.AddField(
            model_name='serviciotaller',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='serviciotaller',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.taller'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='talleres',
            field=models.ManyToManyField(related_name='servicios', through='servicios.ServicioTaller', to='usuarios.taller'),
        ),
        migrations.AlterUniqueTogether(
            name='precioserviciotaller',
            unique_together={('taller', 'servicio')},
        ),
        migrations.AlterUniqueTogether(
            name='precioserviciomecanico',
            unique_together={('mecanico', 'servicio')},
        ),
        migrations.AlterUniqueTogether(
            name='servicioasociado',
            unique_together={('servicio_principal', 'servicio_asociado')},
        ),
        migrations.AlterUniqueTogether(
            name='serviciocategoria',
            unique_together={('servicio', 'categoria')},
        ),
        migrations.AlterUniqueTogether(
            name='serviciomarca',
            unique_together={('servicio', 'marca')},
        ),
        migrations.AlterUniqueTogether(
            name='serviciomecanico',
            unique_together={('servicio', 'mecanico')},
        ),
        migrations.AlterUniqueTogether(
            name='serviciotaller',
            unique_together={('servicio', 'taller')},
        ),
    ]
