# Generated by Django 5.0.13 on 2026-01-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0002_initial'),
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaservicio',
            name='marca_vehiculo_seleccionada',
            field=models.ForeignKey(blank=True, help_text='Marca de vehículo específica para la cual el proveedor ofrece este servicio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_servicio', to='vehiculos.marcavehiculo'),
        ),
        migrations.AddField(
            model_name='ofertaservicio',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_servicio', to='usuarios.mecanicodomicilio'),
        ),
        migrations.AddField(
            model_name='ofertaservicio',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_servicio', to='usuarios.taller'),
        ),
        migrations.AddField(
            model_name='fotoservicio',
            name='oferta_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_servicio', to='servicios.ofertaservicio'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='modelos_compatibles',
            field=models.ManyToManyField(blank=True, help_text='Modelos de vehículos compatibles con este repuesto', related_name='repuestos_compatibles', to='vehiculos.modelo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='categorias',
            field=models.ManyToManyField(related_name='servicios', to='servicios.categoriaservicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='modelos_compatibles',
            field=models.ManyToManyField(help_text='Modelos de vehículos con los que este servicio es compatible', related_name='servicios_compatibles', to='vehiculos.modelo', verbose_name='modelos compatibles'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='servicios_relacionados',
            field=models.ManyToManyField(blank=True, related_name='servicios_que_me_relacionan', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='ofertaservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='detalleservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='serviciorepuesto',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_que_lo_usan', to='servicios.repuesto'),
        ),
        migrations.AddField(
            model_name='serviciorepuesto',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_necesarios', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='solicitudrepuesto',
            name='linea_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_incluidos', to='ordenes.lineaservicio'),
        ),
        migrations.AddField(
            model_name='solicitudrepuesto',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='servicios.repuesto'),
        ),
        migrations.AddConstraint(
            model_name='ofertaservicio',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('mecanico__isnull', True), ('taller__isnull', False), ('tipo_proveedor', 'taller')), models.Q(('mecanico__isnull', False), ('taller__isnull', True), ('tipo_proveedor', 'mecanico')), _connector='OR'), name='oferta_servicio_taller_o_mecanico'),
        ),
        migrations.AddConstraint(
            model_name='ofertaservicio',
            constraint=models.CheckConstraint(check=models.Q(('precio_sin_repuestos__lte', models.F('precio_con_repuestos'))), name='precio_sin_repuestos_menor_igual_que_con_repuestos'),
        ),
        migrations.AlterUniqueTogether(
            name='ofertaservicio',
            unique_together={('mecanico', 'servicio'), ('taller', 'servicio')},
        ),
        migrations.AlterUniqueTogether(
            name='serviciorepuesto',
            unique_together={('servicio', 'repuesto')},
        ),
    ]
