# Generated by Django 5.0.13 on 2025-05-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaservicio',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'categoría de servicio', 'verbose_name_plural': 'categorías de servicios'},
        ),
        migrations.AddField(
            model_name='categoriaservicio',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, help_text='Categoría principal a la que pertenece esta subcategoría', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='servicios.categoriaservicio', verbose_name='categoría padre'),
        ),
        migrations.AddField(
            model_name='categoriaservicio',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional de la categoría', null=True),
        ),
        migrations.AddField(
            model_name='categoriaservicio',
            name='icono',
            field=models.CharField(blank=True, help_text='Nombre del ícono para representar la categoría', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='categoriaservicio',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición de la categoría'),
        ),
    ]
