# Generated by Django 5.0.13 on 2025-05-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_categoria_hierarchy'),
        ('servicios', 'remove_especialidad_alias'),
    ]

    operations = [
    ]
