# Generated by Django 5.0.13 on 2025-05-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_merge_20250516_1343'),
        ('servicios', 'eliminar_modelos_antiguos'),
    ]

    operations = [
    ]
