# Generated by Django 5.0.13 on 2025-05-17 04:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_merge_20250516_2236'),
        ('usuarios', '0003_refactorizacion_fase1'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='duracion_estimada',
        ),
        # Los campos 'mecanicos' y 'talleres' nunca se crearon en 0002_initial.py
        # porque los ManyToMany se crearon sin 'through' directamente.
        # No es necesario eliminarlos.
        migrations.AddField(
            model_name='servicio',
            name='duracion_estimada_base',
            field=models.DurationField(blank=True, help_text='Tiempo base estimado para realizar el servicio', null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio_referencia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de referencia general', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='servicio',
            name='requiere_repuestos',
            field=models.BooleanField(default=True, help_text='Indica si el servicio normalmente requiere repuestos'),
        ),
        # Estos campos ya se crearon sin 'through' en 0002_initial.py
        # Los AlterField son redundantes pero no causan problemas
        migrations.AlterField(
            model_name='servicio',
            name='categorias',
            field=models.ManyToManyField(related_name='servicios', to='servicios.categoriaservicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='marcas_compatibles',
            field=models.ManyToManyField(related_name='servicios_compatibles', to='vehiculos.marca'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicios_relacionados',
            field=models.ManyToManyField(blank=True, related_name='servicios_que_me_relacionan', to='servicios.servicio'),
        ),
        migrations.CreateModel(
            name='OfertaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proveedor', models.CharField(choices=[('taller', 'Taller'), ('mecanico', 'Mecánico a Domicilio')], max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('duracion_estimada', models.TimeField(blank=True, null=True)),
                ('precio_con_repuestos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')])),
                ('precio_sin_repuestos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')])),
                ('incluye_garantia', models.BooleanField(default=True)),
                ('duracion_garantia', models.PositiveIntegerField(default=30, help_text='Duración de la garantía en días')),
                ('detalles_adicionales', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_servicio', to='usuarios.mecanicodomicilio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='servicios.servicio')),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_servicio', to='usuarios.taller')),
            ],
            options={
                'verbose_name': 'oferta de servicio',
                'verbose_name_plural': 'ofertas de servicios',
            },
        ),
        migrations.AddConstraint(
            model_name='ofertaservicio',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('mecanico__isnull', True), ('taller__isnull', False), ('tipo_proveedor', 'taller')), models.Q(('mecanico__isnull', False), ('taller__isnull', True), ('tipo_proveedor', 'mecanico')), _connector='OR'), name='oferta_servicio_taller_o_mecanico'),
        ),
        migrations.AddConstraint(
            model_name='ofertaservicio',
            constraint=models.CheckConstraint(check=models.Q(('precio_sin_repuestos__lte', models.F('precio_con_repuestos'))), name='precio_sin_repuestos_menor_igual_que_con_repuestos'),
        ),
        migrations.AlterUniqueTogether(
            name='ofertaservicio',
            unique_together={('mecanico', 'servicio'), ('taller', 'servicio')},
        ),
    ]
