# Generated by Django 5.0.13 on 2025-05-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_merge_20250516_2326'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='marcas_compatibles',
        ),
        migrations.AddField(
            model_name='servicio',
            name='modelos_compatibles',
            field=models.ManyToManyField(help_text='Modelos de vehículos con los que este servicio es compatible', related_name='servicios_compatibles', to='vehiculos.modelo', verbose_name='modelos compatibles'),
        ),
    ]
