# Generated by Django 5.0.13 on 2025-05-25 02:32
# MODIFICADO: Migración más robusta que verifica si el campo existe antes de eliminarlo

from django.db import migrations, models


def remove_marcas_compatibles_if_exists(apps, schema_editor):
    """
    Elimina el campo marcas_compatibles solo si existe.
    En bases de datos nuevas, este campo puede no existir.
    """
    connection = schema_editor.connection
    
    # Verificar si la tabla intermedia existe
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = 'servicios_servicio_marcas_compatibles'
            );
        """)
        table_exists = cursor.fetchone()[0]
    
    if table_exists:
        # Si la tabla existe, eliminarla
        with connection.cursor() as cursor:
            cursor.execute('DROP TABLE IF EXISTS "servicios_servicio_marcas_compatibles" CASCADE;')


def noop(apps, schema_editor):
    """No-op para reversión"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_merge_20250516_2326'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        # En lugar de RemoveField que falla si la tabla no existe,
        # usamos RunPython que verifica primero
        migrations.RunPython(
            remove_marcas_compatibles_if_exists,
            noop,
        ),
        migrations.AddField(
            model_name='servicio',
            name='modelos_compatibles',
            field=models.ManyToManyField(
                help_text='Modelos de vehículos con los que este servicio es compatible',
                related_name='servicios_compatibles',
                to='vehiculos.modelo',
                verbose_name='modelos compatibles'
            ),
        ),
    ]
