# Generated by Django 5.0.13 on 2025-06-02 15:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0013_configuracionprecio'),
        ('servicios', '0008_remove_servicio_marcas_compatibles_and_more'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_referencia', models.DecimalField(decimal_places=2, default=0, help_text='Precio de referencia del repuesto', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='repuestos/')),
                ('categoria_repuesto', models.CharField(choices=[('filtros', 'Filtros'), ('aceites', 'Aceites y Lubricantes'), ('frenos', 'Sistema de Frenos'), ('motor', 'Motor'), ('transmision', 'Transmisión'), ('suspension', 'Suspensión'), ('electrico', 'Sistema Eléctrico'), ('carroceria', 'Carrocería'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('modelos_compatibles', models.ManyToManyField(blank=True, help_text='Modelos de vehículos compatibles con este repuesto', related_name='repuestos_compatibles', to='vehiculos.modelo')),
            ],
            options={
                'verbose_name': 'repuesto',
                'verbose_name_plural': 'repuestos',
                'ordering': ['categoria_repuesto', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario del repuesto en esta solicitud', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_total', models.DecimalField(decimal_places=2, help_text='Precio total de este repuesto (cantidad * precio_unitario)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('incluido_en_garantia', models.BooleanField(default=True, help_text='Indica si este repuesto está cubierto por la garantía')),
                ('linea_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_incluidos', to='ordenes.lineaservicio')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='servicios.repuesto')),
            ],
            options={
                'verbose_name': 'repuesto de solicitud',
                'verbose_name_plural': 'repuestos de solicitud',
            },
        ),
        migrations.CreateModel(
            name='ServicioRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_estimada', models.PositiveIntegerField(default=1, help_text='Cantidad estimada de este repuesto para el servicio')),
                ('es_opcional', models.BooleanField(default=False, help_text='Indica si el repuesto es opcional para el servicio')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el uso de este repuesto', null=True)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_que_lo_usan', to='servicios.repuesto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_necesarios', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'repuesto de servicio',
                'verbose_name_plural': 'repuestos de servicios',
                'unique_together': {('servicio', 'repuesto')},
            },
        ),
    ]
