# Generated by Django 5.0.13 on 2025-08-21 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_repuesto_solicitudrepuesto_serviciorepuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaservicio',
            name='comision_mecanmovil',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisión del 20% para la plataforma', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ofertaservicio',
            name='costo_mano_de_obra_sin_iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de mano de obra sin incluir IVA', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ofertaservicio',
            name='costo_repuestos_sin_iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total de repuestos sin incluir IVA', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ofertaservicio',
            name='fotos_urls',
            field=models.JSONField(blank=True, default=list, help_text='URLs de fotos asociadas al servicio'),
        ),
        migrations.AddField(
            model_name='ofertaservicio',
            name='ganancia_neta_proveedor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ganancia final del proveedor después de comisión', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ofertaservicio',
            name='iva_sobre_comision',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IVA del 19% sobre la comisión', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ofertaservicio',
            name='precio_publicado_cliente',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio final que verá el cliente (con IVA)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ofertaservicio',
            name='repuestos_seleccionados',
            field=models.JSONField(blank=True, default=list, help_text='Lista de repuestos específicos seleccionados para este servicio'),
        ),
        migrations.AddField(
            model_name='ofertaservicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('con_repuestos', 'Servicio con repuestos'), ('sin_repuestos', 'Servicio sin repuestos')], default='con_repuestos', help_text='Tipo de servicio ofrecido', max_length=20),
        ),
    ]
