# Generated by Django 5.0.13 on 2025-08-21 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_ofertaservicio_comision_mecanmovil_and_more'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaservicio',
            name='marca_vehiculo_seleccionada',
            field=models.ForeignKey(blank=True, help_text='Marca de vehículo específica para la cual el proveedor ofrece este servicio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_servicio', to='vehiculos.marcavehiculo'),
        ),
    ]
