# Generated by Django 5.0.13 on 2025-09-02 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_agregar_marca_vehiculo_seleccionada'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Foto del servicio subida por el proveedor', upload_to='servicios_photos/')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional de la foto', max_length=255, null=True)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de esta foto dentro del servicio')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('oferta_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_servicio', to='servicios.ofertaservicio')),
            ],
            options={
                'verbose_name': 'Foto de Servicio',
                'verbose_name_plural': 'Fotos de Servicios',
                'ordering': ['oferta_servicio', 'orden'],
            },
        ),
    ]
