# Generated by Django 5.0.13 on 2026-01-12 16:41

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de inicio'), ('EN_PROGRESO', 'En progreso'), ('PAUSADO', 'Pausado temporalmente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Momento en que se inició el checklist', null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, help_text='Momento en que se completó el checklist', null=True)),
                ('ubicacion_finalizacion', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Ubicación GPS donde se finalizó el checklist', null=True, srid=4326)),
                ('firma_tecnico', models.TextField(blank=True, help_text='Firma digital del técnico en formato Base64', null=True)),
                ('firma_cliente', models.TextField(blank=True, help_text='Firma digital del cliente en formato Base64', null=True)),
                ('progreso_porcentaje', models.PositiveIntegerField(default=0, help_text='Porcentaje de completado del checklist', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tiempo_total_minutos', models.PositiveIntegerField(blank=True, help_text='Tiempo total invertido en completar el checklist (en minutos)', null=True)),
            ],
            options={
                'verbose_name': 'Instancia de Checklist',
                'verbose_name_plural': 'Instancias de Checklist',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificativo del item', max_length=255)),
                ('categoria', models.CharField(choices=[('INFORMACION_GENERAL', 'Información General'), ('DATOS_VEHICULO', 'Datos del Vehículo'), ('INVENTARIO_VEHICULO', 'Inventario del Vehículo'), ('ACCESORIOS_HERRAMIENTAS', 'Accesorios y Herramientas'), ('DOCUMENTOS_VEHICULO', 'Documentos del Vehículo'), ('CARROCERIA_EXTERIOR', 'Carrocería Exterior'), ('CRISTALES_ESPEJOS', 'Cristales y Espejos'), ('LUCES_SENALIZACION', 'Luces y Señalización'), ('NEUMATICOS_LLANTAS', 'Neumáticos y Llantas'), ('INTERIOR_CABINA', 'Interior de Cabina'), ('TABLERO_CONTROLES', 'Tablero y Controles'), ('ASIENTOS_TAPICERIA', 'Asientos y Tapicería'), ('MOTOR_COMPARTIMIENTO', 'Motor y Compartimiento'), ('FLUIDOS_NIVELES', 'Fluidos y Niveles'), ('SISTEMA_ELECTRICO', 'Sistema Eléctrico'), ('SISTEMA_FRENOS', 'Sistema de Frenos'), ('SUSPENSION_DIRECCION', 'Suspensión y Dirección'), ('TRANSMISION_EMBRAGUE', 'Transmisión y Embrague'), ('TIPO_TRABAJO', 'Tipo de Trabajo Realizado'), ('SERVICIOS_APLICADOS', 'Servicios Aplicados'), ('REPUESTOS_UTILIZADOS', 'Repuestos Utilizados'), ('OBSERVACIONES_TECNICO', 'Observaciones del Técnico'), ('RECOMENDACIONES', 'Recomendaciones'), ('FOTOS_FINALES', 'Fotos Finales'), ('FIRMAS_CONFORMIDAD', 'Firmas de Conformidad')], help_text='Categoría a la que pertenece este item', max_length=50)),
                ('tipo_pregunta', models.CharField(choices=[('TEXT', 'Texto libre'), ('NUMBER', 'Número'), ('BOOLEAN', 'Sí/No (Booleano)'), ('SELECT', 'Selección única'), ('MULTISELECT', 'Selección múltiple'), ('PHOTO', 'Fotografía'), ('SIGNATURE', 'Firma digital'), ('LOCATION', 'Ubicación GPS'), ('DATETIME', 'Fecha y hora'), ('RATING', 'Calificación (1-5 estrellas)'), ('KILOMETER_INPUT', 'Entrada de kilometraje'), ('FUEL_GAUGE', 'Medidor de combustible'), ('FLUID_LEVEL', 'Nivel de fluidos'), ('INVENTORY_CHECKLIST', 'Lista de inventario'), ('SERVICE_SELECTION', 'Selección de servicios'), ('VEHICLE_CONDITION', 'Estado del vehículo'), ('VEHICLE_DIAGRAM', 'Diagrama de vehículo'), ('DAMAGE_REPORT', 'Reporte de daños'), ('EXTERIOR_INSPECTION', 'Inspección exterior'), ('INTERIOR_INSPECTION', 'Inspección interior'), ('ENGINE_INSPECTION', 'Inspección del motor'), ('ELECTRICAL_CHECK', 'Verificación eléctrica'), ('BRAKE_CHECK', 'Verificación de frenos'), ('SUSPENSION_CHECK', 'Verificación de suspensión'), ('TIRE_CONDITION', 'Estado de neumáticos'), ('FINAL_NOTES', 'Notas finales'), ('CLIENT_CONFIRMATION', 'Confirmación del cliente'), ('WORK_SUMMARY', 'Resumen del trabajo')], help_text='Tipo de pregunta/input para este item', max_length=30)),
                ('pregunta_texto', models.TextField(help_text='Texto de la pregunta que se mostrará al usuario')),
                ('descripcion_ayuda', models.TextField(blank=True, help_text='Descripción adicional o ayuda para el usuario', null=True)),
                ('placeholder', models.CharField(blank=True, help_text='Texto de ejemplo que se muestra en el campo', max_length=255, null=True)),
                ('es_obligatorio_por_defecto', models.BooleanField(default=True, help_text='Si este item debe ser obligatorio por defecto')),
                ('opciones_seleccion', models.JSONField(blank=True, help_text='Lista de opciones para SELECT y MULTISELECT (formato JSON)', null=True)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor mínimo para tipos numéricos', max_digits=10, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor máximo para tipos numéricos', max_digits=10, null=True)),
                ('min_fotos', models.PositiveIntegerField(blank=True, help_text='Número mínimo de fotos requeridas (para tipo PHOTO)', null=True)),
                ('max_fotos', models.PositiveIntegerField(blank=True, help_text='Número máximo de fotos permitidas (para tipo PHOTO)', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si este item está disponible para usar en templates')),
                ('uso_frecuente', models.BooleanField(default=False, help_text='Marcar si es un item de uso frecuente para facilitar la selección')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item del Catálogo',
                'verbose_name_plural': 'Items del Catálogo',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('respuesta_numero', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('respuesta_booleana', models.BooleanField(blank=True, null=True)),
                ('respuesta_seleccion', models.JSONField(blank=True, help_text='Respuesta para preguntas de selección (simple o múltiple)', null=True)),
                ('respuesta_fecha', models.DateTimeField(blank=True, null=True)),
                ('respuesta_ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('completado', models.BooleanField(default=False, help_text='Indica si esta respuesta está completa y validada')),
                ('fecha_respuesta', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Respuesta de Checklist',
                'verbose_name_plural': 'Respuestas de Checklist',
                'ordering': ['item_template__orden_visual'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_visual', models.PositiveIntegerField(help_text='Orden de aparición en el checklist (1, 2, 3...)')),
                ('es_obligatorio', models.BooleanField(blank=True, help_text='Sobrescribe la configuración del catálogo. Deja vacío para usar valor por defecto.', null=True)),
                ('descripcion_ayuda_custom', models.TextField(blank=True, help_text='Descripción personalizada que sobrescribe la del catálogo', null=True)),
                ('placeholder_custom', models.CharField(blank=True, help_text='Placeholder personalizado que sobrescribe el del catálogo', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Item de Template de Checklist',
                'verbose_name_plural': 'Items de Template de Checklist',
                'ordering': ['checklist_template', 'orden_visual'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Archivo de imagen capturado', upload_to='checklist_photos/')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional de la foto', max_length=255, null=True)),
                ('orden_en_respuesta', models.PositiveIntegerField(default=1, help_text='Orden de esta foto dentro de la respuesta')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de Checklist',
                'verbose_name_plural': 'Fotos de Checklist',
                'ordering': ['response', 'orden_en_respuesta'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del template (ej. "Checklist Cambio de Aceite")', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del checklist', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si este template está disponible para uso')),
                ('version', models.CharField(default='1.0', help_text='Versión del template para control de cambios', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Checklist',
                'verbose_name_plural': 'Templates de Checklist',
                'ordering': ['servicio__nombre', '-version'],
            },
        ),
    ]
