# Generated by Django 5.0.13 on 2026-01-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinstance',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_instance', to='ordenes.solicitudservicio'),
        ),
        migrations.AddIndex(
            model_name='checklistitemcatalog',
            index=models.Index(fields=['categoria', 'tipo_pregunta'], name='checklists__categor_c127ef_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistitemcatalog',
            index=models.Index(fields=['uso_frecuente', 'activo'], name='checklists__uso_fre_faa301_idx'),
        ),
        migrations.AddField(
            model_name='checklistitemresponse',
            name='checklist_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='checklists.checklistinstance'),
        ),
        migrations.AddField(
            model_name='checklistitemtemplate',
            name='catalog_item',
            field=models.ForeignKey(help_text='Item del catálogo en el que se basa este item del template', on_delete=django.db.models.deletion.CASCADE, related_name='template_usages', to='checklists.checklistitemcatalog'),
        ),
        migrations.AddField(
            model_name='checklistitemresponse',
            name='item_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='checklists.checklistitemtemplate'),
        ),
        migrations.AddField(
            model_name='checklistphoto',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='checklists.checklistitemresponse'),
        ),
    ]
