# Generated by Django 5.0.13 on 2026-01-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0002_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='servicio',
            field=models.ForeignKey(help_text='Servicio al que aplica este checklist', on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='checklistitemtemplate',
            name='checklist_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='checklist_template',
            field=models.ForeignKey(help_text='Template utilizado para crear esta instancia', on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='checklists.checklisttemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistitemresponse',
            unique_together={('checklist_instance', 'item_template')},
        ),
        migrations.AlterUniqueTogether(
            name='checklistphoto',
            unique_together={('response', 'orden_en_respuesta')},
        ),
        migrations.AlterUniqueTogether(
            name='checklisttemplate',
            unique_together={('servicio', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='checklistitemtemplate',
            unique_together={('checklist_template', 'orden_visual')},
        ),
    ]
