# Generated by Django 4.2.7 on 2026-07-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0026_citaagendapersonal_conversation_origen'),
        ('checklists', '0006_checklistinstance_fecha_completado_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinstance',
            name='cita_personal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_instance', to='ordenes.citaagendapersonal'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='generado_por_ia',
            field=models.BooleanField(default=False, help_text='True si el template fue generado automáticamente por IA'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='revisado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que un administrador revisó/validó el template generado por IA', null=True),
        ),
        migrations.AlterField(
            model_name='checklistinstance',
            name='orden',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_instance', to='ordenes.solicitudservicio'),
        ),
        migrations.AddConstraint(
            model_name='checklistinstance',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cita_personal__isnull', True), ('orden__isnull', False)), models.Q(('cita_personal__isnull', False), ('orden__isnull', True)), _connector='OR'), name='checklist_instance_exactly_one_parent'),
        ),
    ]
