# Generated by Django 4.2.7 on 2026-07-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente_ia', '0011_agente_aprendizaje_diario'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcalificacion',
            name='motivo_perdida',
            field=models.CharField(blank=True, default='', help_text='Motivo por el cual se perdió el lead (competencia, presupuesto, etc.).', max_length=100),
        ),
        migrations.AddField(
            model_name='leadcalificacion',
            name='perdido_por_competencia',
            field=models.BooleanField(default=False, help_text='True si el cliente indicó que se fue con otro taller/competencia.'),
        ),
    ]
