# Generated by Django 4.2.7 on 2026-09-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente_ia', '0014_sesion_esperando_aceptacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcalificacion',
            name='categoria',
            field=models.CharField(
                choices=[
                    ('sin_calificar', 'Sin calificar'),
                    ('curioso', 'Curioso'),
                    ('comparando', 'Comparando'),
                    ('sin_presupuesto', 'Sin presupuesto'),
                    ('interesado_calificado', 'Interesado calificado'),
                    ('listo_agendar', 'Listo para agendar'),
                    ('no_automotriz', 'No automotriz'),
                    ('cerrado_perdido', 'Cerrado / Perdido'),
                ],
                db_index=True,
                default='sin_calificar',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='talleragenteconfig',
            name='vitrina_repuestos_habilitada',
            field=models.BooleanField(
                default=True,
                help_text='Permite que el taller envíe a mano una vitrina de opciones. El agente no la manda al cotizar.',
            ),
        ),
    ]
