# Generated by Django 5.0.13 on 2025-11-03 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaGuardada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Token de la tarjeta proporcionado por Mercado Pago', max_length=255, unique=True)),
                ('payment_method_id', models.CharField(help_text='ID del método de pago (visa, master, etc.)', max_length=50)),
                ('cardholder_name', models.CharField(help_text='Nombre del titular de la tarjeta', max_length=255)),
                ('last_four_digits', models.CharField(help_text='Últimos 4 dígitos de la tarjeta', max_length=4)),
                ('expiration_month', models.PositiveIntegerField(help_text='Mes de expiración (1-12)')),
                ('expiration_year', models.PositiveIntegerField(help_text='Año de expiración (ej: 2025)')),
                ('card_type', models.CharField(blank=True, choices=[('credit', 'Crédito'), ('debit', 'Débito')], help_text='Tipo de tarjeta', max_length=20, null=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la tarjeta está activa y puede usarse')),
                ('es_principal', models.BooleanField(default=False, help_text='Indica si es la tarjeta principal del usuario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_ultimo_uso', models.DateTimeField(blank=True, help_text='Fecha de último uso de la tarjeta', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_guardadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'tarjeta guardada',
                'verbose_name_plural': 'tarjetas guardadas',
                'ordering': ['-es_principal', '-fecha_ultimo_uso', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_id_mp', models.BigIntegerField(blank=True, help_text='ID del pago en Mercado Pago', null=True, unique=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, help_text='Monto de la transacción', max_digits=10)),
                ('currency_id', models.CharField(default='CLP', help_text='Código de moneda (CLP, USD, etc.)', max_length=3)),
                ('description', models.TextField(help_text='Descripción del pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('authorized', 'Autorizado'), ('in_process', 'En Proceso'), ('in_mediation', 'En Mediación'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('charged_back', 'Contracargo')], default='pending', help_text='Estado del pago', max_length=20)),
                ('status_detail', models.CharField(blank=True, help_text='Detalle del estado del pago', max_length=255, null=True)),
                ('payment_method_id', models.CharField(blank=True, help_text='ID del método de pago usado', max_length=50, null=True)),
                ('payment_type_id', models.CharField(blank=True, help_text='Tipo de pago (credit_card, debit_card, etc.)', max_length=50, null=True)),
                ('payer_email', models.EmailField(help_text='Email del pagador', max_length=254)),
                ('payer_first_name', models.CharField(blank=True, help_text='Nombre del pagador', max_length=255, null=True)),
                ('payer_last_name', models.CharField(blank=True, help_text='Apellido del pagador', max_length=255, null=True)),
                ('payer_identification_type', models.CharField(blank=True, help_text='Tipo de identificación del pagador', max_length=10, null=True)),
                ('payer_identification_number', models.CharField(blank=True, help_text='Número de identificación del pagador', max_length=50, null=True)),
                ('external_reference', models.CharField(blank=True, help_text='Referencia externa (ID de carrito, orden, etc.)', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata adicional del pago')),
                ('receipt_url', models.URLField(blank=True, help_text='URL del comprobante de pago', null=True)),
                ('date_created_mp', models.DateTimeField(blank=True, help_text='Fecha de creación en Mercado Pago', null=True)),
                ('date_approved_mp', models.DateTimeField(blank=True, help_text='Fecha de aprobación en Mercado Pago', null=True)),
                ('date_last_updated_mp', models.DateTimeField(blank=True, help_text='Fecha de última actualización en Mercado Pago', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tarjeta_guardada', models.ForeignKey(blank=True, help_text='Tarjeta guardada usada para el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='pagos.tarjetaguardada')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='WebhookNotificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_id_mp', models.BigIntegerField(blank=True, help_text='ID del pago en Mercado Pago relacionado con la notificación', null=True)),
                ('notification_type', models.CharField(help_text='Tipo de notificación (payment, etc.)', max_length=50)),
                ('data', models.JSONField(default=dict, help_text='Datos completos de la notificación webhook')),
                ('procesado', models.BooleanField(default=False, help_text='Indica si la notificación ya fue procesada')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, help_text='Fecha cuando se procesó la notificación', null=True)),
                ('error_procesamiento', models.TextField(blank=True, help_text='Mensaje de error si hubo problemas procesando la notificación', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'notificación webhook',
                'verbose_name_plural': 'notificaciones webhook',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['payment_id_mp'], name='pagos_webho_payment_a950b0_idx'), models.Index(fields=['procesado', 'fecha_creacion'], name='pagos_webho_procesa_413d88_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tarjetaguardada',
            index=models.Index(fields=['usuario', 'activa'], name='pagos_tarje_usuario_26eb61_idx'),
        ),
        migrations.AddIndex(
            model_name='tarjetaguardada',
            index=models.Index(fields=['token'], name='pagos_tarje_token_5d2fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['usuario', 'status'], name='pagos_pago_usuario_f4edaf_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['payment_id_mp'], name='pagos_pago_payment_50661b_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['external_reference'], name='pagos_pago_externa_20573f_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['status', 'fecha_creacion'], name='pagos_pago_status_f0f98d_idx'),
        ),
    ]
