# Generated by Django 5.0.13 on 2026-01-12 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_id_mp', models.BigIntegerField(blank=True, help_text='ID del pago en Mercado Pago', null=True, unique=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, help_text='Monto de la transacción', max_digits=10)),
                ('currency_id', models.CharField(default='CLP', help_text='Código de moneda (CLP, USD, etc.)', max_length=3)),
                ('description', models.TextField(help_text='Descripción del pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('authorized', 'Autorizado'), ('in_process', 'En Proceso'), ('in_mediation', 'En Mediación'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('charged_back', 'Contracargo')], default='pending', help_text='Estado del pago', max_length=20)),
                ('status_detail', models.CharField(blank=True, help_text='Detalle del estado del pago', max_length=255, null=True)),
                ('payment_method_id', models.CharField(blank=True, help_text='ID del método de pago usado', max_length=50, null=True)),
                ('payment_type_id', models.CharField(blank=True, help_text='Tipo de pago (credit_card, debit_card, etc.)', max_length=50, null=True)),
                ('payer_email', models.EmailField(help_text='Email del pagador', max_length=254)),
                ('payer_first_name', models.CharField(blank=True, help_text='Nombre del pagador', max_length=255, null=True)),
                ('payer_last_name', models.CharField(blank=True, help_text='Apellido del pagador', max_length=255, null=True)),
                ('payer_identification_type', models.CharField(blank=True, help_text='Tipo de identificación del pagador', max_length=10, null=True)),
                ('payer_identification_number', models.CharField(blank=True, help_text='Número de identificación del pagador', max_length=50, null=True)),
                ('external_reference', models.CharField(blank=True, help_text='Referencia externa (ID de carrito)', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata adicional del pago')),
                ('receipt_url', models.URLField(blank=True, help_text='URL del comprobante de pago', null=True)),
                ('date_created_mp', models.DateTimeField(blank=True, help_text='Fecha de creación en Mercado Pago', null=True)),
                ('date_approved_mp', models.DateTimeField(blank=True, help_text='Fecha de aprobación en Mercado Pago', null=True)),
                ('date_last_updated_mp', models.DateTimeField(blank=True, help_text='Fecha de última actualización en Mercado Pago', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preference_id_mp', models.CharField(help_text='ID de la preferencia en Mercado Pago', max_length=255, unique=True)),
                ('init_point', models.URLField(help_text='URL de inicio de Checkout Pro')),
                ('sandbox_init_point', models.URLField(blank=True, help_text='URL de inicio en modo sandbox', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Monto total de la preferencia', max_digits=10)),
                ('currency_id', models.CharField(default='CLP', help_text='Moneda (CLP, USD, etc.)', max_length=3)),
                ('procesada', models.BooleanField(default=False, help_text='Indica si la preferencia ya fue procesada (pago completado)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'preferencia de pago',
                'verbose_name_plural': 'preferencias de pago',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='WebhookNotificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_id_mp', models.BigIntegerField(blank=True, help_text='ID del pago en Mercado Pago relacionado con la notificación', null=True)),
                ('notification_type', models.CharField(help_text='Tipo de notificación (payment, etc.)', max_length=50)),
                ('data', models.JSONField(default=dict, help_text='Datos completos de la notificación webhook')),
                ('procesado', models.BooleanField(default=False, help_text='Indica si la notificación ya fue procesada')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, help_text='Fecha cuando se procesó la notificación', null=True)),
                ('error_procesamiento', models.TextField(blank=True, help_text='Mensaje de error si hubo problemas procesando la notificación', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'notificación webhook',
                'verbose_name_plural': 'notificaciones webhook',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CuentaMercadoPagoProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(help_text='ID del proveedor')),
                ('estado', models.CharField(choices=[('no_configurada', 'Sin configurar'), ('pendiente', 'Pendiente de configuración'), ('conectada', 'Cuenta conectada'), ('desconectada', 'Cuenta desconectada'), ('error', 'Error en la conexión'), ('suspendida', 'Cuenta suspendida')], default='no_configurada', help_text='Estado de la cuenta de Mercado Pago', max_length=20)),
                ('access_token', models.CharField(blank=True, help_text='Access token de Mercado Pago (obtenido vía OAuth)', max_length=500, null=True)),
                ('refresh_token', models.CharField(blank=True, help_text='Refresh token para renovar el access token', max_length=500, null=True)),
                ('public_key', models.CharField(blank=True, help_text='Public key de Mercado Pago', max_length=500, null=True)),
                ('user_id_mp', models.CharField(blank=True, help_text='ID del usuario en Mercado Pago', max_length=100, null=True)),
                ('email_mp', models.EmailField(blank=True, help_text='Email asociado a la cuenta de Mercado Pago', max_length=254, null=True)),
                ('nombre_cuenta', models.CharField(blank=True, help_text='Nombre del titular de la cuenta de Mercado Pago', max_length=255, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del access token', null=True)),
                ('oauth_state', models.CharField(blank=True, help_text='State token para validar callback OAuth', max_length=100, null=True)),
                ('code_verifier', models.CharField(blank=True, help_text='Code verifier para PKCE OAuth flow', max_length=128, null=True)),
                ('fecha_conexion', models.DateTimeField(blank=True, help_text='Fecha cuando se conectó la cuenta', null=True)),
                ('fecha_desconexion', models.DateTimeField(blank=True, help_text='Fecha cuando se desconectó la cuenta', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mensaje_estado', models.TextField(blank=True, help_text='Mensaje descriptivo del estado actual', null=True)),
                ('content_type', models.ForeignKey(help_text='Tipo de proveedor (Taller o MecanicoDomicilio)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Cuenta Mercado Pago Proveedor',
                'verbose_name_plural': 'Cuentas Mercado Pago Proveedores',
            },
        ),
    ]
