# Generated by Django 5.0.13 on 2026-01-12 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0002_initial'),
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentamercadopagoproveedor',
            name='usuario',
            field=models.OneToOneField(help_text='Usuario propietario de la cuenta', on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_mercadopago', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ordenes.carritoagendamiento', verbose_name='Carrito'),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='preferenciapago',
            name='carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_pago', to='ordenes.carritoagendamiento', verbose_name='Carrito'),
        ),
        migrations.AddField(
            model_name='preferenciapago',
            name='solicitud_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_pago', to='ordenes.solicitudservicio', verbose_name='Solicitud de Servicio'),
        ),
        migrations.AddField(
            model_name='preferenciapago',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_pago', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='pago',
            name='preferencia',
            field=models.ForeignKey(blank=True, help_text='Preferencia de pago relacionada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='pagos.preferenciapago'),
        ),
        migrations.AddIndex(
            model_name='webhooknotificacion',
            index=models.Index(fields=['payment_id_mp'], name='pagos_webho_payment_a950b0_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooknotificacion',
            index=models.Index(fields=['procesado', 'fecha_creacion'], name='pagos_webho_procesa_413d88_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentamercadopagoproveedor',
            index=models.Index(fields=['content_type', 'object_id'], name='pagos_cuent_content_c96cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentamercadopagoproveedor',
            index=models.Index(fields=['estado'], name='pagos_cuent_estado_833472_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentamercadopagoproveedor',
            index=models.Index(fields=['usuario'], name='pagos_cuent_usuario_060d43_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentamercadopagoproveedor',
            index=models.Index(fields=['user_id_mp'], name='pagos_cuent_user_id_279167_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cuentamercadopagoproveedor',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='preferenciapago',
            index=models.Index(fields=['usuario', 'procesada'], name='pagos_prefe_usuario_e6e061_idx'),
        ),
        migrations.AddIndex(
            model_name='preferenciapago',
            index=models.Index(fields=['preference_id_mp'], name='pagos_prefe_prefere_731d81_idx'),
        ),
        migrations.AddIndex(
            model_name='preferenciapago',
            index=models.Index(fields=['carrito'], name='pagos_prefe_carrito_6fbe28_idx'),
        ),
        migrations.AddIndex(
            model_name='preferenciapago',
            index=models.Index(fields=['solicitud_servicio'], name='pagos_prefe_solicit_51ff34_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['usuario', 'status'], name='pagos_pago_usuario_f4edaf_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['payment_id_mp'], name='pagos_pago_payment_50661b_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['external_reference'], name='pagos_pago_externa_20573f_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['status', 'fecha_creacion'], name='pagos_pago_status_f0f98d_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['carrito'], name='pagos_pago_carrito_e811c4_idx'),
        ),
    ]
