# Generated by Django 5.0.13 on 2025-11-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetaguardada',
            name='payment_method_id',
            field=models.CharField(blank=True, help_text='ID del método de pago (visa, mastercard, etc.). Se determina automáticamente del token si no se proporciona.', max_length=50, null=True),
        ),
    ]
