# Generated by Django 5.0.13 on 2025-11-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_allow_null_payment_method_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetaguardada',
            name='first_six_digits',
            field=models.CharField(blank=True, help_text='Primeros 6 dígitos de la tarjeta (BIN)', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='tarjetaguardada',
            name='security_code',
            field=models.CharField(blank=True, help_text='Código de seguridad (CVV) - solo para uso en pagos', max_length=4, null=True),
        ),
    ]
