# Generated by Django 5.0.13 on 2025-11-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_add_first_six_digits_and_security_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhookNotificacion',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='TarjetaGuardada',
        ),
    ]
