# Generated by Django 5.0.13 on 2025-11-25 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0031_agregar_estados_servicio_y_oferta_proveedor'),
        ('pagos', '0005_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciapago',
            name='solicitud_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_pago', to='ordenes.solicitudservicio', verbose_name='Solicitud de Servicio'),
        ),
        migrations.AlterField(
            model_name='preferenciapago',
            name='carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_pago', to='ordenes.carritoagendamiento', verbose_name='Carrito'),
        ),
        migrations.AddIndex(
            model_name='preferenciapago',
            index=models.Index(fields=['solicitud_servicio'], name='pagos_prefe_solicit_51ff34_idx'),
        ),
    ]
