# Generated by Django 5.2.1 on 2025-12-19 21:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pagos', '0006_add_solicitud_servicio_to_preferencia_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaMercadoPagoProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(help_text='ID del proveedor')),
                ('estado', models.CharField(choices=[('no_configurada', 'Sin configurar'), ('pendiente', 'Pendiente de configuración'), ('conectada', 'Cuenta conectada'), ('desconectada', 'Cuenta desconectada'), ('error', 'Error en la conexión'), ('suspendida', 'Cuenta suspendida')], default='no_configurada', help_text='Estado de la cuenta de Mercado Pago', max_length=20)),
                ('access_token', models.CharField(blank=True, help_text='Access token de Mercado Pago (obtenido vía OAuth)', max_length=500, null=True)),
                ('refresh_token', models.CharField(blank=True, help_text='Refresh token para renovar el access token', max_length=500, null=True)),
                ('public_key', models.CharField(blank=True, help_text='Public key de Mercado Pago', max_length=500, null=True)),
                ('user_id_mp', models.CharField(blank=True, help_text='ID del usuario en Mercado Pago', max_length=100, null=True)),
                ('email_mp', models.EmailField(blank=True, help_text='Email asociado a la cuenta de Mercado Pago', max_length=254, null=True)),
                ('nombre_cuenta', models.CharField(blank=True, help_text='Nombre del titular de la cuenta de Mercado Pago', max_length=255, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del access token', null=True)),
                ('oauth_state', models.CharField(blank=True, help_text='State token para validar callback OAuth', max_length=100, null=True)),
                ('fecha_conexion', models.DateTimeField(blank=True, help_text='Fecha cuando se conectó la cuenta', null=True)),
                ('fecha_desconexion', models.DateTimeField(blank=True, help_text='Fecha cuando se desconectó la cuenta', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mensaje_estado', models.TextField(blank=True, help_text='Mensaje descriptivo del estado actual', null=True)),
                ('content_type', models.ForeignKey(help_text='Tipo de proveedor (Taller o MecanicoDomicilio)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.OneToOneField(help_text='Usuario propietario de la cuenta', on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_mercadopago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Mercado Pago Proveedor',
                'verbose_name_plural': 'Cuentas Mercado Pago Proveedores',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='pagos_cuent_content_c96cbc_idx'), models.Index(fields=['estado'], name='pagos_cuent_estado_833472_idx'), models.Index(fields=['usuario'], name='pagos_cuent_usuario_060d43_idx'), models.Index(fields=['user_id_mp'], name='pagos_cuent_user_id_279167_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
