# Generated by Django 5.2.1 on 2025-12-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_add_cuenta_mercadopago_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentamercadopagoproveedor',
            name='code_verifier',
            field=models.CharField(blank=True, help_text='Code verifier para PKCE OAuth flow', max_length=128, null=True),
        ),
    ]
