# Generated by Django 5.0.13 on 2026-01-07 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0036_agregar_alerta_descartada'),
        ('pagos', '0008_add_code_verifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ordenes.carritoagendamiento', verbose_name='Carrito'),
        ),
    ]
