"""
Django settings for mecanimovilapp project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import warnings
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k#t34sc+!o_g&y#d^f-jxfh%7u*6ya!rco%v8!c6(0ot8*6u@^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Suprimir warnings conocidos en desarrollo
# El warning de pkg_resources viene de coreapi (dependencia transitiva de djangorestframework)
# y no afecta la funcionalidad del proyecto
if DEBUG:
    warnings.filterwarnings('ignore', message='.*pkg_resources is deprecated.*', category=UserWarning)
    warnings.filterwarnings('ignore', message='.*The pkg_resources package is slated for removal.*', category=UserWarning)

# Para desarrollo: permitir cualquier IP local de la red
if DEBUG:
    ALLOWED_HOSTS = ['*']  # Solo para desarrollo local
else:
    # Para producción: especificar dominios exactos
    ALLOWED_HOSTS = ['api.mecanimovil.com', 'mecanimovil.com', 'www.mecanimovil.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',  # GeoDjango
    # Paquetes de terceros
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_gis',  # GeoDjango para DRF
    'corsheaders',
    'django_filters',  # Para filtrado avanzado
    'channels',  # Django Channels para WebSockets
    # Aplicaciones propias
    'mecanimovilapp.apps.usuarios',
    'mecanimovilapp.apps.servicios',
    'mecanimovilapp.apps.vehiculos',
    'mecanimovilapp.apps.ordenes',
    'mecanimovilapp.apps.personalizacion',  # Nueva app de personalización
    'mecanimovilapp.apps.checklists',  # App de checklist correctamente ubicada
    'mecanimovilapp.apps.pagos',  # App de pagos con Mercado Pago
]

# Configuración del modelo de usuario personalizado
AUTH_USER_MODEL = 'usuarios.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mecanimovilapp.middleware.vehiculo_activo.VehiculoActivoMiddleware',  # Middleware de vehículo activo
]

ROOT_URLCONF = 'mecanimovilapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mecanimovilapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración para PostgreSQL con PostGIS (ahora activa)
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'mecanimovil',
        'USER': 'sebastianm',  # Usuario específico
        'PASSWORD': '',  # Contraseña vacía para desarrollo local
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Configuración con SQLite estándar (para desarrollo sin GIS)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Configuración para desarrollo con GeoDjango/SpatiaLite
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.contrib.gis.db.backends.spatialite',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Rutas a las bibliotecas espaciales (necesarias para SpatiaLite/GDAL)
SPATIALITE_LIBRARY_PATH = '/opt/homebrew/lib/mod_spatialite.dylib'
GDAL_LIBRARY_PATH = '/opt/homebrew/lib/libgdal.dylib'
GEOS_LIBRARY_PATH = '/opt/homebrew/lib/libgeos_c.dylib'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Rest Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Directorios adicionales para archivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Configuración para servir archivos estáticos en desarrollo
if DEBUG:
    STATICFILES_FINDERS = [
        'django.contrib.staticfiles.finders.FileSystemFinder',
        'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    ]

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de CORS para desarrollo
CORS_ALLOW_ALL_ORIGINS = True

# Configuración de CORS para producción
# CORS_ALLOW_ALL_ORIGINS = False
# CORS_ALLOWED_ORIGINS = [
#     "https://mecanimovilapp.com",
# ]

# Admin site configuration
ADMIN_SITE_HEADER = "MecaniMovil Admin"
ADMIN_SITE_TITLE = "MecaniMovil Admin Portal"
ADMIN_SITE_INDEX_TITLE = "Bienvenido al portal de administración de MecaniMovil"

# Configuración para almacenamiento de archivos
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

# Configuración de Django Channels
ASGI_APPLICATION = 'mecanimovilapp.asgi.application'

# Configuración de canales para WebSockets
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Configuración de Mercado Pago Checkout Pro
MERCADOPAGO_ACCESS_TOKEN = config('MERCADOPAGO_ACCESS_TOKEN', default='APP_USR-8802724849942781-110307-59fe720c1df9cf8be417c6acee855ee7-2959448913')
MERCADOPAGO_MODE = config('MERCADOPAGO_MODE', default='test')  # 'test' o 'production'
MERCADOPAGO_WEBHOOK_SECRET = config('MERCADOPAGO_WEBHOOK_SECRET', default='a7934fae72aca801d2bd08aeaa79b0d650c7900c0def8aa559583934d9de44ee')

# Public Key para modo prueba (obtenida del MCP server test)
MERCADOPAGO_PUBLIC_KEY_TEST = config('MERCADOPAGO_PUBLIC_KEY_TEST', default='')
MERCADOPAGO_PUBLIC_KEY_PROD = config('MERCADOPAGO_PUBLIC_KEY_PROD', default='')

# Seleccionar Public Key según el modo
if MERCADOPAGO_MODE == 'production':
    MERCADOPAGO_PUBLIC_KEY = MERCADOPAGO_PUBLIC_KEY_PROD
else:
    MERCADOPAGO_PUBLIC_KEY = MERCADOPAGO_PUBLIC_KEY_TEST

# Configuración de Cache con Redis (DB 1, diferente a WebSockets)
# Si django-redis no está disponible, usar cache local en memoria
try:
    import django_redis
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/1',  # DB diferente a WebSockets
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                'IGNORE_EXCEPTIONS': True,  # No fallar si Redis está down
            },
            'KEY_PREFIX': 'mecanimovil',
            'TIMEOUT': 300,  # 5 minutos por defecto
        }
    }
except ImportError:
    # Fallback a cache local si django-redis no está instalado
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'mecanimovil-cache',
            'TIMEOUT': 300,
        }
    }

# Configuración de Celery (DB 2 para resultados)
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/2'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/2'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = False  # IMPORTANTE: usar async, no ejecutar sincrónicamente
CELERY_TASK_EAGER_PROPAGATES = True