"""
Django settings for mecanimovilapp project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import warnings
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En producción, usar variable de entorno SECRET_KEY
SECRET_KEY = config('SECRET_KEY', default='django-insecure-k#t34sc+!o_g&y#d^f-jxfh%7u*6ya!rco%v8!c6(0ot8*6u@^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Suprimir warnings conocidos en desarrollo
# El warning de pkg_resources viene de coreapi (dependencia transitiva de djangorestframework)
# y no afecta la funcionalidad del proyecto
if DEBUG:
    warnings.filterwarnings('ignore', message='.*pkg_resources is deprecated.*', category=UserWarning)
    warnings.filterwarnings('ignore', message='.*The pkg_resources package is slated for removal.*', category=UserWarning)

# Configuración de hosts permitidos
# Soporta lista separada por comas desde variable de entorno
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*' if DEBUG else '').split(',')
# Limpiar espacios y valores vacíos
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]
# En desarrollo, permitir todo si no hay hosts configurados
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',  # GeoDjango
    # Paquetes de terceros
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_gis',  # GeoDjango para DRF
    'corsheaders',
    'django_filters',  # Para filtrado avanzado
    'channels',  # Django Channels para WebSockets
    'storages',  # django-storages para Cloudflare R2 / S3
    # Aplicaciones propias
    'mecanimovilapp.apps.usuarios',
    'mecanimovilapp.apps.servicios',
    'mecanimovilapp.apps.vehiculos',
    'mecanimovilapp.apps.ordenes.apps.OrdenesConfig',
    'mecanimovilapp.apps.personalizacion',  # Nueva app de personalización
    'mecanimovilapp.apps.checklists',  # App de checklist correctamente ubicada
    'mecanimovilapp.apps.pagos',  # App de pagos con Mercado Pago
    'mecanimovilapp.apps.suscripciones',  # App de suscripciones freemium + planes
    'mecanimovilapp.apps.chat', # Sistema de mensajería contextual
    'mecanimovilapp.apps.omnichannel', # WhatsApp, Messenger, Instagram
    'mecanimovilapp.apps.marketplace', # Marketplace de vehículos y transferencias
    'mecanimovilapp.apps.valoracion_mercado', # Valor real, liquidez y proyección
]

# Configuración del modelo de usuario personalizado
AUTH_USER_MODEL = 'usuarios.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Servir archivos estáticos en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'mecanimovilapp.middleware.unauth_burst.UnauthDashboardBurstMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mecanimovilapp.middleware.vehiculo_activo.VehiculoActivoMiddleware',  # Middleware de vehículo activo
]

ROOT_URLCONF = 'mecanimovilapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'mecanimovilapp' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mecanimovilapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración de base de datos
# Usa DATABASE_URL si está disponible (producción), sino usa configuración local
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Producción: usar DATABASE_URL con PostGIS
    db_config = dj_database_url.config(
        default=DATABASE_URL,
        engine='django.contrib.gis.db.backends.postgis',
        conn_max_age=600,  # 10 minutos - mejor pooling para plan Standard (1GB)
        conn_health_checks=True,  # Verificar salud de conexiones antes de usar
    )
    # Configuración optimizada para Render Standard (1GB RAM)
    db_config['OPTIONS'] = {
        'connect_timeout': 10,  # Timeout de conexión inicial
        'keepalives': 1,  # Habilitar keepalives TCP
        'keepalives_idle': 30,  # Enviar keepalive después de 30s de inactividad
        'keepalives_interval': 10,  # Intervalo entre keepalives
        'keepalives_count': 5,  # Número de keepalives antes de considerar la conexión muerta
    }
    DATABASES = {
        'default': db_config
    }
else:
    # Desarrollo local: PostgreSQL con PostGIS
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': config('DB_NAME', default='mecanimovil'),
            'USER': config('DB_USER', default='sebastianm'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }

# Rutas a las bibliotecas espaciales (necesarias para SpatiaLite/GDAL en desarrollo local)
# En producción (Render), estas se configuran automáticamente
if DEBUG:
    SPATIALITE_LIBRARY_PATH = '/opt/homebrew/lib/mod_spatialite.dylib'
    GDAL_LIBRARY_PATH = '/opt/homebrew/lib/libgdal.dylib'
    GEOS_LIBRARY_PATH = '/opt/homebrew/lib/libgeos_c.dylib'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Rest Framework settings
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'mecanimovilapp.db_exception_handler.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        # SessionAuthentication removed: enforces CSRF independently (DRF interno),
        # no aplica a esta API REST que usa solo TokenAuthentication.
        # BasicAuthentication removed: no se usa en producción.
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# ===========================
# Google OAuth (mobile login)
# ===========================
# Comma-separated list of allowed OAuth client IDs (iOS + Android + Expo/Web if used).
# These are used to validate the `aud` claim of Google id_tokens.
GOOGLE_OAUTH_CLIENT_IDS = [
    cid.strip()
    for cid in config("GOOGLE_OAUTH_CLIENT_IDS", default="").split(",")
    if cid.strip()
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Directorios adicionales para archivos estáticos
# Solo agregar si el directorio existe (evita errores en producción)
_static_dir = os.path.join(BASE_DIR, 'static')
if os.path.exists(_static_dir):
    STATICFILES_DIRS = [_static_dir]
else:
    STATICFILES_DIRS = []

# STORAGES global: whitenoise para archivos estáticos.
# El backend de archivos de media se sobreescribe más abajo según el provider
# configurado (R2, S3, cPanel). NUNCA definir STATICFILES_STORAGE junto a esto.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ============================================
# Configuración de almacenamiento de archivos
# ============================================
# Opciones disponibles (en orden de prioridad):
# 1. Cloudflare R2 (S3-compatible) - RECOMENDADO. Egress gratis, HTTPS nativo, sin FTP.
# 2. AWS S3 - Estándar de la industria, más caro que R2.
# 3. cPanel (FTP) - LEGACY/DEPRECATED. Frágil, propenso a baneos de IP.
# 4. Local - Solo para desarrollo (no funciona en Render).
#
# La selección automática es: r2 > s3 > cpanel > local
# Puedes forzar uno específico con STORAGE_TYPE=r2|s3|cpanel|local

STORAGE_TYPE = config('STORAGE_TYPE', default='').lower()  # vacío = autodetección

if not DEBUG:
    import logging
    _storage_logger = logging.getLogger(__name__)

    # ----- Detectar credenciales de cada provider -----
    # Cloudflare R2
    r2_access_key = config('R2_ACCESS_KEY_ID', default='') or config('CLOUDFLARE_R2_ACCESS_KEY', default='')
    r2_secret_key = config('R2_SECRET_ACCESS_KEY', default='') or config('CLOUDFLARE_R2_SECRET_KEY', default='')
    r2_bucket = config('R2_BUCKET_NAME', default='') or config('CLOUDFLARE_R2_BUCKET', default='')
    r2_endpoint = config('R2_ENDPOINT_URL', default='') or config('CLOUDFLARE_R2_ENDPOINT', default='')
    r2_public_url = config('R2_PUBLIC_URL', default='') or config('CLOUDFLARE_R2_PUBLIC_URL', default='')
    has_r2_config = all([r2_access_key, r2_secret_key, r2_bucket, r2_endpoint])

    # AWS S3
    aws_key = config('AWS_ACCESS_KEY_ID', default='')
    aws_secret = config('AWS_SECRET_ACCESS_KEY', default='')
    aws_bucket = config('AWS_STORAGE_BUCKET_NAME', default='')
    has_s3_config = all([aws_key, aws_secret, aws_bucket])

    # cPanel (legacy)
    cpanel_ftp_host = config('CPANEL_FTP_HOST', default='')
    cpanel_ftp_port = config('CPANEL_FTP_PORT', default=21, cast=int)
    cpanel_ftp_user = config('CPANEL_FTP_USER', default='')
    cpanel_ftp_password = config('CPANEL_FTP_PASSWORD', default='')
    cpanel_ftp_root = config('CPANEL_FTP_ROOT', default='')
    cpanel_media_url = config('CPANEL_MEDIA_URL', default='')
    has_cpanel_config = all([cpanel_ftp_host, cpanel_ftp_user, cpanel_ftp_password, cpanel_ftp_root])

    # ----- Resolver tipo efectivo de storage -----
    if STORAGE_TYPE in ('r2', 's3', 'cpanel', 'local'):
        effective_storage = STORAGE_TYPE
    elif has_r2_config:
        effective_storage = 'r2'
        _storage_logger.info("🔍 [Settings] Detectada configuración R2. Usando Cloudflare R2 automáticamente.")
    elif has_s3_config:
        effective_storage = 's3'
        _storage_logger.info("🔍 [Settings] Detectada configuración S3. Usando AWS S3 automáticamente.")
    elif has_cpanel_config:
        effective_storage = 'cpanel'
        _storage_logger.warning("⚠️ [Settings] Usando cPanel FTP storage (legacy). Considera migrar a Cloudflare R2.")
    else:
        effective_storage = 'local'
        _storage_logger.error("❌ [Settings] Ningún storage configurado. Los uploads fallarán.")

    if effective_storage == 'r2':
        # ============================================
        # Cloudflare R2 (S3-compatible) - RECOMENDADO
        # ============================================
        # ARQUITECTURA DE SEGURIDAD:
        # - Bucket TOTALMENTE PRIVADO en R2 (sin acceso público).
        # - Por defecto, todos los archivos se sirven con URLs firmadas
        #   (presigned URLs) que expiran en R2_URL_EXPIRE_SECONDS (default 7 días).
        # - Solo el backend con las credenciales puede generar URLs válidas.
        # - Cuando un usuario pide los datos de un proveedor/vehículo/etc, el
        #   serializer devuelve URLs firmadas frescas. Cuando expiren, basta
        #   con volver a pedir los datos para regenerarlas.
        # - Esto protege documentos sensibles (cédula, comprobantes, chats,
        #   checklists) sin necesidad de exponer el bucket públicamente.
        #
        # Variables de entorno requeridas:
        #   R2_ACCESS_KEY_ID      - Access Key del API token de R2
        #   R2_SECRET_ACCESS_KEY  - Secret Key del API token de R2
        #   R2_BUCKET_NAME        - Nombre del bucket (ej: 'mecanimovil-media')
        #   R2_ENDPOINT_URL       - https://<account_id>.r2.cloudflarestorage.com
        #
        # Variables opcionales:
        #   R2_PUBLIC_URL         - Solo si activas R2.dev subdomain o dominio custom
        #                            (no recomendado por seguridad)
        #   R2_URL_EXPIRE_SECONDS - Tiempo de validez de URLs firmadas (default: 604800 = 7 días)
        STORAGES['default'] = {'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage'}

        AWS_ACCESS_KEY_ID = r2_access_key
        AWS_SECRET_ACCESS_KEY = r2_secret_key
        AWS_STORAGE_BUCKET_NAME = r2_bucket
        AWS_S3_ENDPOINT_URL = r2_endpoint
        AWS_S3_REGION_NAME = config('R2_REGION', default='auto')
        AWS_S3_SIGNATURE_VERSION = 's3v4'
        AWS_S3_ADDRESSING_STYLE = 'path'  # R2 requiere path-style addressing
        AWS_S3_FILE_OVERWRITE = False
        AWS_DEFAULT_ACL = None  # R2 no soporta ACLs (todo va con bucket policy)
        AWS_S3_OBJECT_PARAMETERS = {
            'CacheControl': 'private, max-age=86400',  # Cache cliente 24h
        }

        if r2_public_url:
            # MODO PÚBLICO: el usuario configuró R2.dev o dominio custom.
            # Las URLs son directas y NO expiran (cache infinito).
            # NO RECOMENDADO si manejas documentos sensibles.
            AWS_QUERYSTRING_AUTH = False
            AWS_S3_CUSTOM_DOMAIN = r2_public_url.replace('https://', '').replace('http://', '').rstrip('/')
            MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
            _storage_logger.warning(
                "⚠️ [Settings R2] Modo PÚBLICO activo (R2_PUBLIC_URL configurado). "
                "Cualquier persona con la URL puede acceder a los archivos. "
                "Si manejas documentos sensibles, REMUEVE R2_PUBLIC_URL."
            )
        else:
            # MODO PRIVADO (DEFAULT): bucket sin acceso público.
            # Las URLs se generan firmadas y expiran. Los serializers regeneran
            # las URLs en cada response.
            AWS_QUERYSTRING_AUTH = True
            AWS_QUERYSTRING_EXPIRE = config('R2_URL_EXPIRE_SECONDS', default=604800, cast=int)  # 7 días
            # Sin AWS_S3_CUSTOM_DOMAIN: las URLs irán al endpoint de R2 firmadas
            MEDIA_URL = '/media/'  # No se usa directamente, las URLs se generan vía boto3
            _storage_logger.info(
                f"🔒 [Settings R2] Modo PRIVADO activo. URLs firmadas con expiración "
                f"de {AWS_QUERYSTRING_EXPIRE}s ({AWS_QUERYSTRING_EXPIRE // 86400} días)."
            )

        _storage_logger.info(f"✅ [Settings R2] Storage configurado: bucket={r2_bucket}")

    elif effective_storage == 's3':
        # ============================================
        # AWS S3
        # ============================================
        STORAGES['default'] = {'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage'}
        AWS_ACCESS_KEY_ID = aws_key
        AWS_SECRET_ACCESS_KEY = aws_secret
        AWS_STORAGE_BUCKET_NAME = aws_bucket
        AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
        AWS_S3_FILE_OVERWRITE = False
        AWS_DEFAULT_ACL = None
        AWS_QUERYSTRING_AUTH = False
        AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'

    elif effective_storage == 'cpanel':
        # ============================================
        # cPanel (FTP) - LEGACY
        # ============================================
        STORAGES['default'] = {'BACKEND': 'mecanimovilapp.storage.cpanel_storage.CPanelStorage'}
        CPANEL_FTP_HOST = cpanel_ftp_host
        CPANEL_FTP_PORT = cpanel_ftp_port
        CPANEL_FTP_USER = cpanel_ftp_user
        CPANEL_FTP_PASSWORD = cpanel_ftp_password
        CPANEL_FTP_ROOT = cpanel_ftp_root

        if cpanel_media_url:
            if 'mecanimovil.cl' in cpanel_media_url and 'www.' not in cpanel_media_url:
                cpanel_media_url = cpanel_media_url.replace('https://mecanimovil.cl', 'https://www.mecanimovil.cl')
                cpanel_media_url = cpanel_media_url.replace('http://mecanimovil.cl', 'http://www.mecanimovil.cl')

        CPANEL_MEDIA_URL = cpanel_media_url
        if CPANEL_MEDIA_URL:
            MEDIA_URL = CPANEL_MEDIA_URL

    # Si STORAGE_TYPE es 'local' o no está configurado, se usa almacenamiento local
    # (solo para desarrollo, no funciona en Render)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de CORS
if DEBUG:
    # Desarrollo: permitir todos los orígenes
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # Producción: solo orígenes permitidos
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = config(
        'CORS_ALLOWED_ORIGINS',
        default='https://mecanimovilapp.com,https://app.mecanimovil.com'
    ).split(',')
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS if origin.strip()]

# Headers permitidos para CORS
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Permitir credenciales en CORS
CORS_ALLOW_CREDENTIALS = True

# Admin site configuration
ADMIN_SITE_HEADER = "MecaniMovil Admin"
ADMIN_SITE_TITLE = "MecaniMovil Admin Portal"
ADMIN_SITE_INDEX_TITLE = "Bienvenido al portal de administración de MecaniMovil"

# Configuración para almacenamiento de archivos
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

# ============================================
# CONFIGURACIÓN DE REDIS
# ============================================
# Usa REDIS_URL si está disponible (producción), sino usa localhost
REDIS_URL = config('REDIS_URL', default='redis://127.0.0.1:6379')

# Configuración de Django Channels
ASGI_APPLICATION = 'mecanimovilapp.asgi.application'

# Configuración de canales para WebSockets
# En producción usa Redis, en desarrollo usa InMemoryChannelLayer
if DEBUG:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_URL],
                "capacity": 1500,
                "expiry": 60,
                "group_expiry": 86400,
            },
        },
    }

# ============================================
# CONFIGURACIÓN DE MERCADO PAGO
# ============================================
MERCADOPAGO_ACCESS_TOKEN = config('MERCADOPAGO_ACCESS_TOKEN', default='APP_USR-8802724849942781-110307-59fe720c1df9cf8be417c6acee855ee7-2959448913')

# MercadoLibre search API (scraper worker). El refresh_token real vive en DB
# (MercadoLibreOAuthToken) una vez autorizado vía /api/valoracion-mercado/ml/oauth/authorize/.
MERCADOLIBRE_ACCESS_TOKEN = config('MERCADOLIBRE_ACCESS_TOKEN', default='')
MERCADOLIBRE_CLIENT_ID = config('MERCADOLIBRE_CLIENT_ID', default='')
MERCADOLIBRE_CLIENT_SECRET = config('MERCADOLIBRE_CLIENT_SECRET', default='')
MERCADOLIBRE_REDIRECT_URI = config('MERCADOLIBRE_REDIRECT_URI', default='')
PLAYWRIGHT_PROXY = config('PLAYWRIGHT_PROXY', default='')
MERCADOPAGO_MODE = config('MERCADOPAGO_MODE', default='test')  # 'test' o 'production'
MERCADOPAGO_WEBHOOK_SECRET = config('MERCADOPAGO_WEBHOOK_SECRET', default='a7934fae72aca801d2bd08aeaa79b0d650c7900c0def8aa559583934d9de44ee')

# Public Key para modo prueba (obtenida del MCP server test)
MERCADOPAGO_PUBLIC_KEY_TEST = config('MERCADOPAGO_PUBLIC_KEY_TEST', default='')
MERCADOPAGO_PUBLIC_KEY_PROD = config('MERCADOPAGO_PUBLIC_KEY_PROD', default='')

# Seleccionar Public Key según el modo
if MERCADOPAGO_MODE == 'production':
    MERCADOPAGO_PUBLIC_KEY = MERCADOPAGO_PUBLIC_KEY_PROD
else:
    MERCADOPAGO_PUBLIC_KEY = MERCADOPAGO_PUBLIC_KEY_TEST

# ============================================
# CONFIGURACIÓN OMNICANAL (Meta)
# ============================================
OMNICHANNEL_ENABLED = config('OMNICHANNEL_ENABLED', default=False, cast=bool)
META_APP_ID = config('META_APP_ID', default='')
META_APP_SECRET = config('META_APP_SECRET', default='')
META_VERIFY_TOKEN = config('META_VERIFY_TOKEN', default='')
META_EMBEDDED_SIGNUP_CONFIG_ID = config('META_EMBEDDED_SIGNUP_CONFIG_ID', default='')
META_OAUTH_REDIRECT_URI = config(
    'META_OAUTH_REDIRECT_URI',
    default='http://localhost:8000/api/omnichannel/oauth/callback/',
)
META_GRAPH_API_VERSION = config('META_GRAPH_API_VERSION', default='v21.0')

# ============================================
# CONFIGURACIÓN DE CACHE CON REDIS
# ============================================
# Configuración de Cache con Redis
# Si django-redis no está disponible, usar cache local en memoria
try:
    import django_redis
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': f'{REDIS_URL}/1',  # DB 1 para cache
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                'IGNORE_EXCEPTIONS': True,  # No fallar si Redis está down
            },
            'KEY_PREFIX': 'mecanimovil',
            'TIMEOUT': 300,  # 5 minutos por defecto
        }
    }
except ImportError:
    # Fallback a cache local si django-redis no está instalado
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'mecanimovil-cache',
            'TIMEOUT': 300,
        }
    }

# Configuración de Celery
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=f'{REDIS_URL}/2')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=f'{REDIS_URL}/2')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = False  # IMPORTANTE: usar async, no ejecutar sincrónicamente
CELERY_TASK_EAGER_PROPAGATES = True

# ============================================
# OPTIMIZACIONES ADICIONALES DE CELERY
# ============================================
# Worker concurrency: número de procesos worker por instancia
# Valor recomendado: 2-4 para desarrollo, CPU cores - 1 para producción
# Por defecto usa número de CPUs, lo cual puede ser demasiado
CELERY_WORKER_CONCURRENCY = 4  # Máximo 4 workers por instancia

# Pool: tipo de pool de workers
# 'prefork' es el default y funciona bien para la mayoría de casos
CELERY_WORKER_POOL = 'prefork'

# Task compression: comprimir mensajes grandes
CELERY_TASK_COMPRESSION = 'gzip'

# Broker connection pool limit: SIN límite para evitar saturación
# None = usa connection pooling de Redis sin límite artificial
CELERY_BROKER_POOL_LIMIT = None  # Era 10, ahora sin límite

# Connection retry settings: reintentar conexiones fallidas
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10

# Result backend optimizations
CELERY_RESULT_BACKEND_MAX_RETRIES = 10
CELERY_RESULT_EXPIRES = 3600  # 1 hora: alineado con celery.py app.conf.result_expires

# Task ignore result: no guardar resultados si no se necesitan (ahorra memoria)
# Se puede configurar por tarea, aquí es el default
CELERY_TASK_IGNORE_RESULT = False  # Mantener True si necesitas resultados

# Task store eager result: guardar resultados incluso en modo eager
CELERY_TASK_STORE_EAGER_RESULT = True

# ============================================
# CONFIGURACIÓN DE SEGURIDAD PARA PRODUCCIÓN
# ============================================
if not DEBUG:
    # HTTPS
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookies seguras
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    
    # Protección adicional
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Proxy headers (para Render y otros servicios)
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True

# ============================================
# LOGGING
# ============================================
# Horas para que el proveedor elegido confirme adjudicación comprando créditos (solicitud pública)
ADJUDICACION_CREDITOS_RESERVA_HORAS = int(config('ADJUDICACION_CREDITOS_RESERVA_HORAS', default=48))

# Asistente IA en creación de solicitudes (catálogo + análisis de necesidad)
AGENDAMIENTO_IA_ASISTIDO = config('AGENDAMIENTO_IA_ASISTIDO', default=False, cast=bool)
# Fase 5: comprensión semántica (sin costo por defecto: proveedor lexico local).
# Proveedores: lexico | gemini | huggingface | ollama | auto
AGENDAMIENTO_IA_SEMANTICO_ENABLED = config('AGENDAMIENTO_IA_SEMANTICO_ENABLED', default=True, cast=bool)
AGENDAMIENTO_IA_SEMANTICO_PROVEEDOR = config('AGENDAMIENTO_IA_SEMANTICO_PROVEEDOR', default='lexico')
AGENDAMIENTO_IA_SEMANTICO_TIMEOUT = config('AGENDAMIENTO_IA_SEMANTICO_TIMEOUT', default=15, cast=int)
# Opcional gratuito: Google AI Studio → https://aistudio.google.com/apikey
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-3.1-flash-lite')
# Opcional gratuito: Hugging Face → https://huggingface.co/settings/tokens
HUGGINGFACE_API_TOKEN = config('HUGGINGFACE_API_TOKEN', default='')
HUGGINGFACE_MODEL = config('HUGGINGFACE_MODEL', default='Qwen/Qwen2.5-1.5B-Instruct')
# Opcional: Ollama en tu propia máquina/servidor
OLLAMA_BASE_URL = config('OLLAMA_BASE_URL', default='')
OLLAMA_MODEL = config('OLLAMA_MODEL', default='llama3.2')

# Asistente IA de guía de reparación para técnicos en órdenes asignadas
# Modelo Gemini para guía de reparación (free tier: preferir gemini-3.1-flash-lite, 500 RPD)
ASISTENTE_DIAGNOSTICO_GEMINI_MODEL = config(
    'ASISTENTE_DIAGNOSTICO_GEMINI_MODEL',
    default='gemini-3.1-flash-lite',
)
ASISTENTE_DIAGNOSTICO_IA_ENABLED = config('ASISTENTE_DIAGNOSTICO_IA_ENABLED', default=False, cast=bool)
ASISTENTE_DIAGNOSTICO_IA_TIMEOUT = config('ASISTENTE_DIAGNOSTICO_IA_TIMEOUT', default=12, cast=int)
ASISTENTE_COTIZACION_GEMINI_MODEL = config(
    'ASISTENTE_COTIZACION_GEMINI_MODEL',
    default='',
)
ASISTENTE_COTIZACION_IA_ENABLED = config('ASISTENTE_COTIZACION_IA_ENABLED', default=False, cast=bool)
ASISTENTE_COTIZACION_IA_TIMEOUT = config('ASISTENTE_COTIZACION_IA_TIMEOUT', default=15, cast=int)
GEMINI_RETRY_MAX = config('GEMINI_RETRY_MAX', default=2, cast=int)
# Cuota mensual de referencia para alertas de uso Gemini (Google AI Studio renueva cada mes calendario)
GEMINI_LIMITE_TOKENS_MENSUAL = config('GEMINI_LIMITE_TOKENS_MENSUAL', default=1_000_000, cast=int)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'suppress_routine_api_401': {
            '()': 'mecanimovilapp.logging_filters.SuppressRoutineHttp401Filter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['suppress_routine_api_401'],
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'channels': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'celery': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'mecanimovilapp': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': True,
        },
    },
}

# ============================================
# WEB PUSH (VAPID / RFC 8030)
# ============================================
VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '')
VAPID_PRIVATE_KEY = os.environ.get('VAPID_PRIVATE_KEY', '')
VAPID_EMAIL = os.environ.get('VAPID_EMAIL', 'mailto:admin@mecanimovil.com')
